examples/naming-conventions/Cargo.toml, examples/naming-conventions/README.md, examples/naming-conventions/build.rs, examples/naming-conventions/example.kts, examples/naming-conventions/example.py, examples/naming-conventions/src/lib.rs, examples/naming-conventions/src/main.rs, examples/naming-conventions/src/naming-conventions.idl, src/bindings/kotlin/gen_kotlin.rs, src/bindings/python/gen_python.rs, src/scaffolding.rs
This PR may not be useful, but starts as a way of exploring the codebase. Absenting some issues ;)
* The IDL may specify method names in camel case or snake case.
* The generated kotlin method names are in camel case. 
* The generated python method names are in snake case.
* The rust method names are in snake case.
Is this useful? 
* If the rust devs are delivering generated APIs to App developers, then yes. 
* If the rust devs are delivering handmade wrappers around the generated APIs, then no. 
This should probably be a candidate for project specific/language specific `uniffi` config.
=> Add name mangling for method and type names to fit foreign language naming conventions

src/scaffolding.rs
Got a couple of compilation errors and thought might as well fix it
=> fixes missing ffi_support in FfiStr<'_>

.circleci/config.yml, Cargo.toml, examples/README.md, examples/todolist/Cargo.toml, examples/todolist/README.md, examples/todolist/build.rs, examples/todolist/src/lib.rs, examples/todolist/src/main.rs, examples/todolist/src/todolist.idl, examples/todolist/tests/bindings/test_todolist.kts, examples/todolist/tests/bindings/test_todolist.py, examples/todolist/tests/bindings/test_todolist.swift, examples/todolist/tests/test_generated_bindings.rs, uniffi/src/bindings/kotlin/gen_kotlin.rs, uniffi/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi/src/bindings/kotlin/templates/RustBufferHelpers.kt, uniffi/src/bindings/python/gen_python.rs, uniffi/src/bindings/python/templates/RustBufferHelper.py, uniffi/src/bindings/swift/gen_swift.rs, uniffi/src/bindings/swift/templates/RustBufferHelper.swift, uniffi/src/bindings/swift/templates/Template-Bridging-Header.h, uniffi/src/interface/mod.rs, uniffi/src/interface/types.rs, uniffi/src/scaffolding.rs, uniffi/src/support/mod.rs, uniffi/src/templates/ObjectTemplate.rs, uniffi/src/templates/RecordTemplate.rs, uniffi/src/templates/TopLevelFunctionTemplate.rs, uniffi/src/templates/scaffolding_template.rs
fixes #3 
Continuation from #22. It got closed since the base branch was deleted, and I couldn't figure out how to re-open it and rebase the PR sooooo here we are.
Anyways, here's the bit of text from that PR: 
- Since we have an asymmetry between arguments and return values, there is some duplication with the `type_c` values
- ~~Another weird side effect of the asymmetry is two `impl`s for ViaFFi, one for the lifting from `FfiStr` to `&str`, and a second for the lowering from `String` to `* mut c_char` there is probably a better way of doing this, but I'm blanking out 😞~~ **Will open an issue to split the `ViaFffi` Trait, I think that will be an awesome first issue for someone else! (I can also do it if it's urgent) Here it is: #26 ** 
- ~~Freeing is **not** implemented yet, I imagine …
=> Adds String support

uniffi/src/support/mod.rs
Changes the size of len back to 4 bytes in the check and removes the extra `check_remaining` (Since len is the number of elements and we get the check for the actual bytes for free in the inner `try_lift_froms`)
=> Fixes check_remaining checks in sequences

Cargo.toml, examples/rondpoint/Cargo.toml, examples/rondpoint/README.md, examples/rondpoint/build.rs, examples/rondpoint/src/lib.rs, examples/rondpoint/src/main.rs, examples/rondpoint/src/rondpoint.idl, examples/rondpoint/tests/bindings/test_rondpoint.kts, examples/rondpoint/tests/bindings/test_rondpoint.swift, examples/rondpoint/tests/test_generated_bindings.rs, uniffi/src/scaffolding.rs, uniffi/src/support/mod.rs, uniffi/src/templates/EnumTemplate.rs
Fixes https://github.com/mozilla/uniffi-rs/issues/36.
Summary of changes:
- Impl Lowerable/Liftable for enums
- `into_ffi_value` does not consume `self` anymore, uses `&self` instead (had to do this because otherwise we would require enums to implement `Copy` or `Clone`)
- Added the `rondpoint` example, it does round-tripping testing.
=> Implement Lowerable/Liftable for enums

examples/arithmetic/tests/bindings/test_arithmetic.swift, examples/geometry/tests/bindings/test_geometry.swift, examples/rondpoint/tests/bindings/test_rondpoint.swift, examples/sprites/tests/bindings/test_sprites.swift, examples/todolist/tests/bindings/test_todolist.swift, uniffi/src/bindings/swift/templates/ObjectTemplate.swift, uniffi/src/bindings/swift/templates/TopLevelFunctionTemplate.swift, uniffi/src/bindings/swift/templates/macros.swift
Clean up after #31.
Removes `throws` from swift functions that don't throw.
=> Removes throws from non-throwing swift functions

examples/sprites/tests/bindings/test_sprites.kts, uniffi/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi/src/bindings/kotlin/templates/Helpers.kt, uniffi/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi/src/bindings/kotlin/templates/macros.kt, uniffi/src/bindings/kotlin/templates/wrapper.kt, uniffi/src/bindings/python/templates/ObjectTemplate.py, uniffi/src/bindings/python/templates/TopLevelFunctionTemplate.py, uniffi/src/bindings/python/templates/macros.py, uniffi/src/bindings/swift/templates/ObjectTemplate.swift, uniffi/src/bindings/swift/templates/TopLevelFunctionTemplate.swift, uniffi/src/bindings/swift/templates/macros.swift, uniffi/src/interface/mod.rs, uniffi/src/templates/ObjectTemplate.rs
Fixes #8.
This PR adds `deinit` and `__del__` calls into a reserved `object_free` method. (aside: this should be one more example for the need for #10.)
For kotlin, the JVM has a long and storied history of destructor not being the right thing.
Our _best_ hope is for `java.lang.ref.Cleaner` to be implemented in Java 9 and then adopted by Android.
Our _second best_ hope is for explicit `destroy` method. Provided here is an abstract class which checks if the object has been destroyed before each call.
=> Add destructors for objects

.circleci/config.yml, examples/arithmetic/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, uniffi/Cargo.toml, uniffi/src/testing.rs, uniffi_bindgen/src/lib.rs, uniffi_build/Cargo.toml, uniffi_build/src/lib.rs
When working on uniffi itself, it's very inconvenient to have to rely
on an externally-installed `uniffi-bindgen` command in order to run the
tests for the in-tree example crates. You basically need to remember to
manually `cargo build -p uniffi_bindgen` anytime you make a change to the
bindings genertor, or the tests won't test what you think they should.
This commit adds a feature-flag to the `uniffi` and `uniffi_build` crates
so that they will use the builtin `unifi_bindgen` module from this workspace
rather than whatever one they find on the system. I think this gives a much
better development experience when working on this repo itself, in particular
by allow `cargo test` to Just Work (tm) and always reflect your latest changes.
On the other hand, it means the examples in this repo …
=> Use our own bindgen when building our crates, rather than system bindgen

uniffi/src/lib.rs
`into_vec` throws a warning at compile time
```sh
warning: use of deprecated item 'ffi_support::ByteBuffer::into_vec': Name is confusing, please use `destroy_into_vec` instead
```
=> Use destroy_into_vec

uniffi/Cargo.toml
As of https://github.com/mozilla/uniffi-rs/pull/210, we depend on `ByteBuffer.destroy_into_vec` which is first available in the 0.4.2 release of `ffi_support`. This uses the tilde syntax to say "any semvar-compatible version that is at least 0.4.2" (which frankly, nothing about `~` makes me think "at least", but ok...)
=> Update version requirement for ffi-support.

README.md
Updates some dead links in our README with the refactoring work that was done.
Also updates the bindings sections in the README to mention `uniffi-bindgen`
relates to #213
=> Updates dead links in readme

examples/todolist/tests/bindings/test_todolist.kts
I noticed that the kotlin tests for the "todolist" example were only
checking that the correct *type* of error is thrown, whereas the
swift tests check for the correct error code/case. This adjusts the
kotlin tests to match.
=> Check for specific error subclasses in the kotlin "todolist" tests.

examples/todolist/tests/bindings/test_todolist.kts, examples/todolist/tests/bindings/test_todolist.swift, uniffi_bindgen/src/templates/ObjectTemplate.rs
The PR fixes a bug which crept in during simultaneous landing of errors and destructors.
Cursory testing of #217 prompted this discovery.
=> Fixup destructor crashes

uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/mod.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/main.rs
Fixes https://github.com/mozilla/uniffi-rs/issues/234.
We auto-format code after generation using:
- `swiftformat` for Swift
- `ktlint` for Kotlin
- `yapf` for Python
This feature is enabled by default, but does not generate a hard error if these tools are not available.
=> Format generated bindings

uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/lib.rs
Java loves folders, and so when running `uniffi-bindgen generate MYPROJECT --language kotlin --out-dir MY_OUT_DIR`, you will have to create `MY_OUT_DIR/uniffi/MYPROJECT` beforehand for it to make sense and point `--out-dir` to `MY_OUT_DIR/uniffi/MYPROJECT`
Note that I'd be cool to be able to specify the package name with an idl directive (kinda like protobufs)
=> Output Kotlin bindings into package path

uniffi/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin.rs, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt, uniffi_bindgen/src/bindings/swift/gen_swift.rs, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift, uniffi_bindgen/src/scaffolding.rs, uniffi_bindgen/src/templates/EnumTemplate.rs, uniffi_bindgen/src/templates/RecordTemplate.rs, uniffi_bindgen/src/templates/RustString.rs
Inspired by the conversation in https://github.com/mozilla/uniffi-rs/pull/214#discussion_r467578565,
here's a PR to try to clarify and simplify some terminology.
Previously, we used a loosely-defined mix of terms like "lower" and "lower into"
to describe passing data across the FFI in two very different ways (the former
by converting to a primitive C type, the later by serializing to a bytebuffer).
Sometimes when we said "lower" we meant the former, and sometimes we meant the
later, and this was not consistent between the different codegen backends.
This commit tries to clean up the terminology and bring the Rust, Kotlin and
Swift code generators into agreement on which activities are called what.
Broadly:
* "Lowering" is now exclusively about converting from a high-level language
type …
=> Clarify terminology around passing values across the FFI.

examples/rondpoint/src/lib.rs, examples/rondpoint/src/rondpoint.idl, examples/rondpoint/tests/bindings/test_rondpoint.kts, examples/rondpoint/tests/bindings/test_rondpoint.swift, uniffi/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin.rs, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt, uniffi_bindgen/src/bindings/python/gen_python.rs, uniffi_bindgen/src/bindings/swift/gen_swift.rs, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift, uniffi_bindgen/src/interface/types.rs, uniffi_bindgen/src/scaffolding.rs, uniffi_bindgen/src/templates/EnumTemplate.rs, uniffi_bindgen/src/templates/RecordTemplate.rs
Fixes https://github.com/mozilla/uniffi-rs/issues/226.
There's some awkwardness in here, but it's not a shower-stopper imo.
=> Implement record type

examples/arithmetic/src/lib.rs, examples/todolist/src/lib.rs, examples/todolist/src/todolist.idl, uniffi_bindgen/src/templates/ErrorTemplate.rs
fixes #245 
Forces errors variants to have an associate type
i.e now all error variants must have some internal thing they are wrapping, example:
```rust
enum Error {
NetworkError, // This is an invalid variant, will not compile
ExperimentError(String), // Valid
DbError(rusqlite::Error), // This is also valid
OtherError {
message: String
} // Invalid will not compile
}
```
I don't like this too much. 
I would prefer it if we were able to let the consumer decide what each variant looks like.
In order to do that we need a way to match against an enum variant's name, regardless if it has an associated type, is a struct, or is just a variant with no other data. Seems like a reasonable thing, except I couldn't for the life of me find a way to do that. What I mean is something like this for the …
=> Allows dynamic error messages

examples/rondpoint/src/lib.rs, examples/rondpoint/src/rondpoint.idl, examples/rondpoint/tests/bindings/test_rondpoint.kts, examples/rondpoint/tests/bindings/test_rondpoint.swift
Fixes #175 
This PR adds a good deal of certainty around the lowering and lifting code for primitives. 
The idea is that roundtripping gives us some confidence that two rounds of lowering/lifting works, but not that the value that rust gets is the value sent by the foreign language.
e.g. 
1. calling round: lower from swift to C then lift from C to rust.
2. returning round: lower from rust to C, then lift from C to swift.
i.e. if we only test by roundtripping, we only verify that the two lowering/lifting rounds are symmetrical, not that they are both correct.
If we can convince ourselves that one round is correct, and that both rounds are symmetrical, then we can say that both are correct.
To do this, we ask rust to transform the received value into a different, but well known …
=> Roundtrip and stringify testing for primitives

examples/rondpoint/src/rondpoint.idl, uniffi_bindgen/src/interface/mod.rs
Fixes #246.
Implement the `Default` trait for `Constructor`, and use it when no constructors are given in the IDL.
Removed the noarg constructors in `rondpoint.idl`.
=> Add a default constructor if none is provided

examples/arithmetic/src/arithmetic.idl, examples/arithmetic/src/lib.rs, examples/arithmetic/tests/bindings/test_arithmetic.kts, examples/arithmetic/tests/bindings/test_arithmetic.py, examples/arithmetic/tests/bindings/test_arithmetic.swift, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/templates/ErrorTemplate.py, uniffi_bindgen/src/bindings/python/templates/macros.py, uniffi_bindgen/src/bindings/python/templates/wrapper.py, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/templates/macros.rs
This commit changes all FFI functions to take an `out_err` param, so
that they're called using `call_with_result`. Any functions that don't
have a `[Throws]` annotation in the IDL will throw a generic
`InternalError` instead.
Closes #32.
=> Ensure panic safety for all FFI methods

examples/todolist/src/lib.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/types.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/templates/ObjectTemplate.rs, uniffi_bindgen/src/templates/RustString.rs, uniffi_bindgen/src/templates/TopLevelFunctionTemplate.rs
fixes #254 
Adds `#[allow(clippy::all)]` in all generated functions.
A WAY nicer way to do this is to add `#![allow(clippy::all)]` but unfortunately that doesn't work because of https://github.com/rust-lang/rfcs/issues/752, although I would be happy if there is a different way to disable clippy on the whole generated file without asking the consumer to do so.
Note: I did not add the `#[allow(clippy::all)]` for anything other than the functions purely because they didn't complain, I'd be happy to go around doing that if we need to.
I also fixed some clippy errors that popped up (not sure if it's because I updated to `1.46`)
=> Fixes clippy for consumers

uniffi_bindgen/src/lib.rs, uniffi_build/src/lib.rs
Also updates other instructions to reflect the name is `uniffi_bindgen`
rather than `uniffi-bindgen`.
=> Mention how to install uniffi-bindgen if we fail to execute it.

examples/arithmetic/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml
We don't want to accidentally publish these to crates.io.
=> Mark example crates as `publish = false`.

uniffi_bindgen/src/lib.rs
Cargo has a tendency to mishandle \\\\?\\ paths on windows.
See: https://github.com/rust-lang/cargo/issues/8626
I was having trouble running `cargo build` on windows to check the generated
code, and this seems to fix the issue?
=> Don't canonicalize paths fed to `cargo metadata`

uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
This PR fixes two sets of annoying warnings seen a lot in the `cargo test`:
```
warning: /Users/jhugman/workspaces/mozilla/uniffi-rs/uniffi_bindgen/Cargo.toml: only one of `license` or `license-file` is necessary
warning: /Users/jhugman/workspaces/mozilla/uniffi-rs/uniffi_macros/Cargo.toml: only one of `license` or `license-file` is necessary
warning: /Users/jhugman/workspaces/mozilla/uniffi-rs/uniffi_build/Cargo.toml: only one of `license` or `license-file` is necessary
warning: /Users/jhugman/workspaces/mozilla/uniffi-rs/uniffi/Cargo.toml: only one of `license` or `license-file` is necessary
```
and 
```
/Users/jhugman/workspaces/mozilla/uniffi-rs/target/debug/rondpoint.swift:127:9: warning: using '_' to ignore the result of a Void-returning function is redundant
_ = withUnsafeBytes(of: …
```
=> No bug - fixup warnings in cargo test

README.md
I'd like to add a omre elaborate contributor guide, but directing folks
to the public chat channel seems like a good first step.
=> Link to our chat channel in the project readme.

uniffi/Cargo.toml, uniffi/src/testing.rs
Updates cargo_metadata to 0.11.3, and reenables some of the code that calls it.
=> Fix #301 cargo tests by updating and reenabling cargo_metadata

uniffi_bindgen/src/bindings/python/gen_python.rs
I should have rebased https://github.com/mozilla/uniffi-rs/pull/214 before merging, as the new python rondpoint tests interacted badly with the concurrent PR to add support for default arguments. This PR does just enough work to unbreak CI, but doesn't add any tests or similar for the actual use of optional args in python. That work is tracked in https://github.com/mozilla/uniffi-rs/issues/300
=> Render all types of literal in the python bindings.

examples/rondpoint/src/lib.rs, examples/rondpoint/src/rondpoint.idl, examples/rondpoint/tests/bindings/test_rondpoint.kts, examples/rondpoint/tests/bindings/test_rondpoint.swift, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/python/gen_python.rs, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/interface/mod.rs
Fixes #188.
This small PR adds to #283.
=> Add defaults for properties in Records

uniffi_bindgen/src/bindings/gecko_js/gen_gecko_js.rs, uniffi_bindgen/src/bindings/gecko_js/templates/InterfaceTemplate.cpp, uniffi_bindgen/src/bindings/gecko_js/templates/RustBufferHelper.h, uniffi_bindgen/src/bindings/gecko_js/templates/macros.cpp, uniffi_bindgen/src/bindings/gecko_js/webidl.rs
Optional arguments and members with a default value are a bag of special cases.
On the C++ side, `optional` arguments with default values are passed as `const T&`, and optional dictionary members are type `T` (for optional arguments, they're `const dom::Optional<T>&` and `dom::Optional<T>`, respectively). But the Rust side is expecting them to be serialized as `Option<T>`. It's basically the same problem as strings, where null and non-null strings have the same `const nsAString&`/`nsString` type—the Rust side is expecting to read `1`/`0` followed by the serialization of the type, but the C++ side isn't passing that `1`/`0`.
So the first commit adds a special `WebIDLType::OptionalWithDefaultValue` that's emitted as `T`, except when we call `ViaFfi`, where it passes `Nullable = true`. It …
=> Special-case "optionals with a default value" and fix compilation errors in Gecko JS

uniffi_bindgen/src/bindings/gecko_js/templates/macros.cpp
I've confirmed this works by re-generating the bindings and building for release.
I'm not sure if this requires a version bump/release since right now the bindings are generated manually.
=> Change MOZ_RELEASE_ASSERT to MOZ_ASSERT. Fixes #326

uniffi/src/ffi/foreignbytes.rs, uniffi/src/ffi/rustbuffer.rs, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt, uniffi_bindgen/src/bindings/python/templates/RustBufferTemplate.py, uniffi_bindgen/src/bindings/swift/templates/RustBufferTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/Template-Bridging-Header.h
The current version of JNA appears to have a bug when passing small structs
as arguments by value, on arm64 platforms, when the function call has too
many arguments to pass the struct in registers. It turns out that our generated
code does this a lot thanks to the way we pass around `RustBuffer` structs.
This commit adds a temporary workaround for the issue, by padding our structs
to be larger than 16 bytes, which causes them to be passed as pointers rather
than by value.
See https://github.com/mozilla/application-services/issues/3646 for investigation
of the JNA issue, and https://github.com/mozilla/uniffi-rs/issues/334 to track
the work of removing this workaround once a fix is released in upstream JNA.
=> Add workaround for JNA bug when passing small structs by value.

uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml
This will avoid us pulling in multiple versions of some of our dependencies when used in conjunction with this PR: https://github.com/mozilla/nimbus-sdk/pull/49#discussion_r517688219
=> Update cargo_metadata dependency.

.circleci/config.yml, docker/Dockerfile-build, docker/README.md, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/interface/mod.rs
The version of Rust in mozilla-central is currently pinned to v1.43.0,
so we need to make sure we're compatible with it as well.
=> Compatibility tweaks for Rust v1.43.0

Cargo.toml, fixtures/regressions/README.md, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/README.md, fixtures/regressions/enum-without-i32-helpers/build.rs, fixtures/regressions/enum-without-i32-helpers/src/lib.rs, fixtures/regressions/enum-without-i32-helpers/src/test.udl, fixtures/regressions/enum-without-i32-helpers/tests/bindings/test.kts, fixtures/regressions/enum-without-i32-helpers/tests/bindings/test.py, fixtures/regressions/enum-without-i32-helpers/tests/bindings/test.swift, fixtures/regressions/enum-without-i32-helpers/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt
Previously, the generated Kotlin code for enums would try to use
helpers from the `Int` companion class, but we would only emit the
code for those helpers if the interface was also using the integer
type.
Now, the generated Kotlin code for enums directly uses lower-level
methods for reading and writing integers, so that it doesn't depend
on other generated code.
Fixes #356.
=> Don't use i32 helpers in generated Enum code.

docs/manual/src/SUMMARY.md, docs/manual/src/internals/lifting_and_lowering.md, docs/manual/src/internals/object_references.md, docs/manual/src/udl/interfaces.md
Specifically:
* What "lifting" and "lowering" are and how they're done.
* The serialization format we use for lowering complex data types.
* How and why we use handlemaps for managing object references.
(These describe the *current* state of the world, but I want to get them into the repo so that I can propose *diffs* to that state of the world in order to resolve the current threading/concurrency issues).
Fixes #297.
=> Add some narrative docs about important internal implementation details.

docs/manual/src/internals/lifting_and_lowering.md, docs/manual/src/internals/object_references.md, docs/manual/src/udl/interfaces.md
I wrote these docs are part of working through the proposal in https://github.com/mozilla/uniffi-rs/pull/368 and figured I may as well push them for visibility. They may or may not turn out to be a useful starting point for the implementation work connected to #370. /cc @jhugman
=> Add narrative docs for threadsafe instances.

docs/adr/0003-threadsafe-interfaces.md
Based on conversations over the last few days, here is a concrete proposal for how we can resolve the underlying issue that casued the [recent Fenix startup regression](https://github.com/mozilla/uniffi-rs/blob/adr-threadsafe-interface/docs/adr/0003-threadsafe-interfaces.md). I hope I have captured the current consensus accurately, but this is an ADR, so please do weigh in if you don't agree with something here or if you've got other considerations to include!
Something new for this ADR: I have included an [implementation sketch](https://github.com/mozilla/uniffi-rs/blob/adr-threadsafe-interface/docs/adr/0003-threadsafe-interfaces.md#implementation-sketch) section with a high-level overview of how I'd go about implementing this. I'm hoping this will empower someone who is not me to …
=> Add an ADR for our "threadsafe interfaces" plan.

uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/templates/CallbackInterfaceTemplate.rs, uniffi_bindgen/src/templates/EnumTemplate.rs, uniffi_bindgen/src/templates/ErrorTemplate.rs, uniffi_bindgen/src/templates/ObjectTemplate.rs, uniffi_bindgen/src/templates/RecordTemplate.rs, uniffi_bindgen/src/templates/RustBuffer.rs, uniffi_bindgen/src/templates/TopLevelFunctionTemplate.rs
I've been experimenting with using `cargo doc` as the canonical source
of documentation for a UniFFI component, and I quite like it so far,
except for the way that it currently documents all the autogenerated
helper functions and traint impls. So, let's hide those using the
nice `#[doc(hidden)]` annotation.
=> Hide Rust scaffolding from `cargo doc`.

docs/manual/src/internals/lifting_and_lowering.md, uniffi_bindgen/src/bindings/gecko_js/gen_gecko_js.rs
Weedle special-cases `record<K,V>` to ensure that the keys are one of its
known string types, so when we write record syntax in UDL is needs to be
`record<DOMString, T>` rather than `record<string, T>`. Bleh.
=> Fix documentation about `record<>` syntax.

docs/manual/src/udl/interfaces.md, examples/sprites/src/lib.rs, examples/sprites/src/sprites.udl, examples/sprites/tests/bindings/test_sprites.kts, examples/sprites/tests/bindings/test_sprites.py, examples/sprites/tests/bindings/test_sprites.swift, examples/sprites/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/gecko_js/templates/InterfaceTemplate.cpp, uniffi_bindgen/src/bindings/gecko_js/templates/WebIDLTemplate.webidl, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/python/gen_python.rs, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/object.rs
This is an alternative approach to factory methods, based on feedback from #384. It also fixes #37.
It's a fairly common pattern for object-oriented interfaces to have
static methods that act as named "factories" for producing object
instances in ways that differ from the default constructor.
This commit adds basic support for such named alternate constructors:
* In the UDL, declare additional constructors with a [Name=Value]
attribute to tell the tool what name should be exposed under.
* In the Rust code, implement a corresponding method on the struct
that acts as a constructor (no `self` parameter, `Self` return type).
* In the foreign-language code, expect a static method on the
resulting class with name matching the one provided in Rust.
We continue to reserve the name "new" to refer …
=> Add support for named alternate constructors.

uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt
While trying to uniffi the fxa-client crate, I discovered some linter errors in the generated Kotlin saying "`Error: Call requires API level 24 (current min is 21)`". A bit of ducking-and-going led me to the tweaks here which silence the warnings. For good measure, I've also avoided generating helper code when it won't be used by the bindings.
=> Tweak generated Kotlin for compatibility with Android API 21.

examples/arithmetic/Cargo.toml, examples/arithmetic/uniffi.toml, uniffi_bindgen/src/bindings/kotlin/gen_kotlin.rs, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/python/gen_python.rs, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py, uniffi_bindgen/src/bindings/swift/gen_swift.rs, uniffi_bindgen/src/bindings/swift/mod.rs
When building uniffi components in the application-services monorepo,
we know that they're all going to want to load their FFI symbols from
the combined "libmegazord.so". This adds a config option so that
the generated code can use this cdylib name by default, rather
than having to specify it as an override at runtime.
Ref https://github.com/mozilla/application-services/issues/3874
=> Add config option to set the cdylib name for backends that use it.

uniffi_bindgen/Cargo.toml
The latest release of `nom` seems to have fixed the dependency issue so this is no longer required.
This basically reverts the version pin from https://github.com/mozilla/uniffi-rs/pull/382, and I'm counting on CI to confirm my "no longer required" hypothesis with a clean build...
=> Remove version pin of `funty`, which is no longer required.

uniffi/src/testing.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py, uniffi_bindgen/src/bindings/python/templates/wrapper.py
Fixes https://github.com/mozilla/uniffi-rs/issues/391.
I have no intention of messing around with Swift or Kotlin on Windows, but this at least makes `cargo test py` run successfully.
=> Get `cargo test py` passing on Window.

docs/manual/src/tutorial/Rust_scaffolding.md, examples/arithmetic/src/lib.rs, uniffi_macros/src/lib.rs
Smaller and simpler than https://github.com/mozilla/uniffi-rs/pull/386, this is a macro to include the generated Rust scaffolding by name, without having to know the precise details of where and how it gets generated.
=> Add a small convenience macro for including generated scaffolding.

.circleci/config.yml, uniffi_bindgen/src/templates/EnumTemplate.rs
Otherwise clippy yells at me when trying to use this feature in the fxa-client crate:
```
error: the `v @ _` pattern can be written as just `v`
```
=> Fix a clippy lint in the generated scaffolding for enums with associated data

examples/app/ios/IOSApp-Bridging-Header.h, examples/app/ios/IOSApp/ContentView.swift, examples/app/ios/README.md
The iOS app is not on CI, so suffers from bit rot. 
This is the occasional fix for that bit rot.
=> No bug - Fix up iOS example app.

uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
Swift struct fields default to `internal` visibility, loosly
analogous to Rust's `pub(crate)`. That's clearly enough for them
to work fine in our tests, but when I tried out using these
across Swift module boundaries, I got errors about being able
to access to fields.
Since the whole point of record types is to make structured
data available, I think it makes sense for their fields to be
marked public.
=> Mark record fields as `public` in Swift bindings.

examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/threadsafe/Cargo.toml, examples/todolist/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
(A friendly reminder that if you merge this, please create a merge commit rather than squashing or rebasing, since the release tag is associated with the exact commit staged in this PR).
=> (cargo-release) version v0.7.2

uniffi_bindgen/src/bindings/kotlin/mod.rs
Thanks to `ankhers` for pointing out the buggy behavior here in Matrix.
=> Fix generation of kotlin module path on Windows.

examples/app/ios/IOSApp-Bridging-Header.h, examples/app/ios/IOSApp.xcodeproj/project.pbxproj, examples/app/ios/IOSApp/ContentView.swift, examples/arithmetic/Cargo.toml, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift, uniffi_bindgen/src/bindings/swift/templates/RustBufferTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/Template-Bridging-Header.h, uniffi_bindgen/src/bindings/swift/templates/macros.swift
Fixes #408.
This PR:
* hides all helpers in swift protocols and extensions behind `fileprivate` access modifiers.
* protects redefinition of C structs with header guards.
=> Eliminate duplicate declarations of helper structs and extensions in Swift

docker/Dockerfile-build, uniffi/Cargo.toml, uniffi/src/lib.rs, uniffi/src/testing.rs, uniffi/tests/ui/version_mismatch.rs, uniffi/tests/ui/version_mismatch.stderr, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/scaffolding.rs, uniffi_bindgen/src/templates/scaffolding_template.rs, uniffi_build/src/lib.rs
(I know I said over in https://github.com/mozilla/uniffi-rs/issues/413#issuecomment-790259989 that this may not be too much of a problem
in practice, but I suddenly realised what a good fix would look like and decided to
try it out).
Fixes #413.
Prior to this commit, the `uniffi-bindgen` command would use `cargo metadata`
to discover the version of uniffi being used by the target crate, and would
error out if did not match the version of uniffi-bindgen itself.
Unfortunately, this approach is not reliable when the target crate is being
compiled as a dependency rather than as the primary crate. The build process
may pick a version of uniffi based on the `Cargo.lock` of the primary crate
or based on resolving compatible versions with other dependencies, while
while `cargo metadata` will …
=> Use static assertions to check uniffi/uniffi-bindgen version compatibility.

examples/todolist/src/lib.rs, examples/todolist/src/todolist.udl
For demonstration purposes we mark the interface as threadsafe,
meaning we need to drop all `&mut self` functions and wrap
`self.items` in a suitable wrapper - `RwLock` in this case.
This is done in support of [ADR-0004](
https://github.com/mozilla/uniffi-rs/blob/main/docs/adr/0004-only-threadsafe-interfaces.md),
which will contain a link to this PR/commit to show an example of the
kind of modifications interfaces  need to become threadsafe.
This seems worthwhile even if we don't adopt ADR-0004, as it becomes a reasonably real-world threadsafe example which we don't really have at the moment.
=> Convert the todolist example to be threadsafe.

uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift
Hey!
First, thanks for your work on this project. I've been having fun trying to integrate it into a personal app I've been working on.
Hopefully this is a minor thing. I'm trying to use a sequence of dictionaries that contain enums with associated values. Tests will fail for this case for Swift because those enums do not conform to `Hashable`. 
```
error: instance method 'combine' requires that 'Relationship' conform to 'Hashable'
hasher.combine(relationship)
^
Swift.Hasher:3:37: note: where 'H' = 'Relationship'
@inlinable public mutating func combine<H>(_ value: H) where H : Hashable
```
It looks like ![record types conform to `Hashable` by default](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift#L1) so perhaps the same …
=> Make Swift enums Hashable

uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
This reduces swiftformat noise in generated files by moving the extension access modifier to the extension declaration and removing it from the function declarations. The functions should inherit the fileprivate access from the extension declaration.
=> Fix swiftformat issues with Swift extension template

docs/adr/0004-only-threadsafe-interfaces.md
This attempts to the document the reasons why we think removing
support for uniffi managing thread-safety is a bad idea and
formalizes a decision to remove that support.
=> Add an ADR to remove support for non-threadsafe interfaces.

uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/interface/types/resolver.rs
The set of types is used in multiple places during FFI creation. When
the data structure does not guarantee the order of elements, such as
HashSet, the resulting generated source code is not deterministic. Using
a BTreeSet resolves this issue by providing a well-defined element order
over which the the set may be iterated.
=> Store the universe of known types in an ordered BTreeSet (#374)

examples/todolist/tests/test_generated_bindings.rs
Not clear why is was disabled, but it passes locally and python tests remain enabled for all other ones. Let's see what CI says.
=> re-enable python tests for the todolist example.

.circleci/config.yml, docs/policies/README.md, docs/policies/rust-versions.md, examples/callbacks/src/lib.rs, rust-toolchain.toml, uniffi/src/lib.rs, uniffi_bindgen/src/bindings/gecko_js/webidl.rs, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/error.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/literal.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/namespace.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/finder.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/interface/types/resolver.rs
Clippy is getting upset because it's running 1.5x, but we have an [informal policy](https://github.com/mozilla/uniffi-rs/blob/a7ddeed2ab555f684d521dded9d049145901dcee/uniffi_bindgen/src/interface/literal.rs#L67-L68) of tracking mozilla-central's version - let's formalize that.
=> Define our rust version policy

Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/coverall/README.md, fixtures/coverall/build.rs, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/test_generated_bindings.rs
This is similar to our examples, but it's intended to be contrived and to
ensure we get good test coverage of all possible options - particularly for
future changes.
It's in the "fixtures" directory so it doesn't even need to make a cursory
effort to be a "good example"; it intentionally panics, asserts params are
certain values, has no-op methods etc. If you're trying to get your head
around uniffi then the "examples" directory will be a much better bet.
=> New 'coverall' fixture to test coverage and edge-cases.

uniffi/tests/ui/version_mismatch.stderr
I recently updated the docker image that we use to run CI, which
seems to have perturbed the version of Rust being used, which has
subtly changed the expected error output from `trybuild`. This
should get CI passing again.
=> Adjust expected `trybuild` error output for new rust version.

.circleci/config.yml, README.md, uniffi_bindgen/src/templates/ObjectTemplate.rs
Now that [adr-0004](https://github.com/mozilla/uniffi-rs/blob/main/docs/adr/0004-only-threadsafe-interfaces.md)
has been approved, we should deprecate non-threadsafe interfaces ASAP,
to ensure that consumers have as much time as possible to migrate
before we drop support for non-threadsafe interfaces entirely.
=> Issue deprecation warning for non-Threadsafe interfaces

examples/callbacks/src/callbacks.udl, examples/callbacks/src/lib.rs, examples/rondpoint/src/rondpoint.udl, examples/sprites/src/lib.rs, examples/sprites/src/sprites.udl
We are leaving the Threadsafe example as the only one
which supports a non-threadsafe interface until we actually
remove support for non-theadsafe interfaces.
I guess this is the next logical step after #429? Note I can't yet remove the `-A deprecated` because one non-threadsafe interface remains.
=> Make all examples, other than Threadsafe, Threadsafe.

README.md, docs/manual/book.toml, docs/manual/src/Getting_started.md, docs/manual/src/Overview.md, docs/manual/src/SUMMARY.md, docs/manual/src/internals/lifting_and_lowering.md, docs/manual/src/internals/object_references.md, docs/manual/src/kotlin/gradle.md, docs/manual/src/tutorial/Rust_scaffolding.md, docs/manual/src/tutorial/foreign_language_bindings.md, docs/manual/src/udl/errors.md, docs/manual/src/udl/interfaces.md
We don't currently have much consistency around how we capitalize the name of this project. I'd like to propose "UniFFI" as the preferred rendering, as both a Proper Noun and containing a correctly capitalized embedded acronym "FFI". My preference for this particular rendering is weakly held, I just want to pick *something* that we can use consistently :-)
=> Try to consistently capitalize "UniFFI" in consumer docs.

fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt
Seems like you can't use `v=== null` on when `v` is an optional primitive type like `UByte?`. I noticed this while working on something else, but figured it would be simpler as a standalone PR. Also, a good excuse to get started on a Kotlin coveralls file.
=> Fix Kotlin codegen for writing optional integers.

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, uniffi/src/ffi/handle_maps.rs, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/templates/macros.rs
As of ADR-0005, the use of `Arc<T>` for passing object instances will
be part of the official Rust-facing  API of UniFFI rather than being
a private implementation detail. A full implementation of that ADR is
still in progress, but in the meantime we can get a relatively easy
implementation of one small part of it: support for `Arc<Self>` as
method receiver.
This commit implements support for the `[ByArc]` annotation on method
definitions, indicating they the underlying Rust code will accept
`self: Arc<Self>` rather than `self: &Self` as method receiver. This
only works for `[Threadsafe]` interfaces since they are the only ones
that use `Arc<Self>` internally, but that's OK because we intend to
require that all interfaces are threadsafe in the near future.
The implementation is small, but …
=> Implement `[Self=ByArc]` annotation for methods on threadsafe objects.

CHANGELOG.md, README.md, release.toml
If we're going to be issuing deprecation notices and such, we really ought to
be keeping a changelog. This commit adds one, with some retroactive notes from
the `v0.9.0` release.
I had hoped to be able to automatically manage updating the section headers
in the changelog using `cargo release`, but that doesn't seem to work as I
hoped when releasing multiple crates in a single workspace. Still, let's
organize it as though we'll be using `cargo release` for this one day.
=> Start keeping a changelog.

CHANGELOG.md, examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/threadsafe/Cargo.toml, examples/todolist/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/uniffi-fixture-time/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
This is a semver breaking change because of the introduction of new builtin types, which might conflict with user-defined types of the same name.
=> Release v0.10.0

release.toml
This was accidentally left in as a result of my testing
from https://github.com/mozilla/uniffi-rs/pull/459
=> Re-enable publishing in cargo-release configuration.

.circleci/config.yml, .dockerignore, docker/Dockerfile-build, docker/README.md, docs/policies/rust-versions.md, examples/sprites/src/lib.rs, examples/todolist/src/lib.rs, rust-toolchain.toml, uniffi/tests/ui/version_mismatch.rs, uniffi/tests/ui/version_mismatch.stderr, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/literal.rs, uniffi_bindgen/src/interface/namespace.rs, uniffi_bindgen/src/interface/types/mod.rs
[Rendered version](https://github.com/mhammond/uniffi-rs/blob/update-rust-policy/docs/policies/rust-versions.md)
Ryan and I have come up with this policy for our rust components. We want uniffi and app-services to have the same policy, and because this repo already had a documented I figured I'd start here, then once approved, copy it into the app-services repo.
This updates #432 - @dmose reviewed/approved that, but he's out, so I'm going with just @rfk
=> Update our rust policy to match mozilla-central's 'uses' version

CHANGELOG.md, fixtures/coverall/tests/bindings/test_handlerace.kts, fixtures/coverall/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/wrapper.kt
Currently just a test case that reproduces the issue on my machine, but I'm thinking about a fix.
(Depends on the Kotlin codegen fix from https://github.com/mozilla/uniffi-rs/pull/451)
=> Guard against race between Kotlin method calls and object destruction

CHANGELOG.md, examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/uniffi-fixture-time/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
This is a semver breaking change due to interface implementations must now be `Sync + Send` and deprecating `[Threadsafe]`. Also kotlin and swift generation for dictionaries now make it mutable by default.
=> (cargo-release) version v0.11.0

uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt, uniffi_bindgen/src/bindings/python/templates/RustBufferBuilder.py, uniffi_bindgen/src/bindings/python/templates/RustBufferStream.py, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferStream.rb
There's a fair bit of copy/pasted "this type not supported" boilerplate in the bindings that would be simplified using `{% else %}` - when I found myself adding copy/pasting the same boilerplate in these locations I figured I'd see if it could be avoided.
=> Remove lots of boilerplate from bindings by using askama's 'else'

.circleci/config.yml, .gitignore, docs/contributing.md, docs/manual/src/SUMMARY.md, docs/manual/src/internals/crates.md, uniffi/src/lib.rs, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/interface/types/resolver.rs, uniffi_bindgen/src/lib.rs
Rust has great tooling for API docs, and I think we should try to
get into the habit of using it. This commit generates API docs for
our main crates and includes them in the published UniFFI manual,
which will hopefully help folks onboarding into the codebase.
=> Publish auto-generated Rust API docs as part of the UniFFI manual.

.circleci/config.yml
The docs-publishing CircleCI task is using a node-based docker image,
which means it doesn't have the necessary tooling to build the API
docs. Let's use the same docker image as the other tasks for simplicity.
=> Use rusty docker image for building API docs in CI.

uniffi/src/lib.rs, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs
This is a followup to the upgrade of our `bytes` dependency from #454.
Our use of the `bytes::Buf` trait assumes that `Buf::chunks` will return
all the remaining data. This is not guaranteed by the trait, but it is
guaranteed in practice by its implementation on the concrete types that
we use.
Since we don't really work with any generic `Buf` impl anyway, this commit
removes the generics from `ViaFfi::try_read` and `ViaFii:write`, replacing
them with the single concrete type that we actually ues in practice. This
should reduce potential for future confusion, and also make compilation
slightly easier on the Rust compiler.
=> Implement try_read/write for concrete types, not Buf/BufMut generics.

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift
fixes #485 
As a follow-up I'll take a look at the other bindings and make sure this behaviour is consistent. I'll file an issue to add a coverall.falliblePanic test for the other bindings (which will include figuring out if this behaviour is also wrong there), ref for follow up: #487
=> Fixes mismatch in kotlin panic exceptions

docs/manual/src/internals/crates.md, examples/README.md
Couple documentation updates based on my trying to get started with uniffi coding.
- Updated ruby dependencies
- Updated cargo commands
- Link to the examples dir from the manual.  These were really helpful
for me and I think it would be great to link for others.  Is there a
better way that a direct github link?
=> Updating the examples documentiation

docs/contributing.md
~~I remember having to install ktlint to have the kotlin tests pass on my local environment~~ Looks like it just emits a message saying that that the files couldn't be formated, nevertheless, we should probably add it to our docs so adding that to the `contributing.md`
(as a side point, when picking who to review this, should I be picking `uniffi-devs` or `uniffi-review`? I notice `uniffi-devs` is the more complete list?)
=> Adds ktlint to kotlin requirements in contributing.md

uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/TopLevelFunctionTemplate.rs, uniffi_bindgen/src/scaffolding/templates/macros.rs
fixes #257 
We had two main issues with the generated code clippy-wise:
- We had a `-> ()` on ffi functions that don't have a return value, clippy prefers if you simply omit that. For example:
```rust
pub exter "C" fn func() -> () {  // clippy prefers if we remove the "-> ()"
.
.
}
```
- We had a `let` binding to functions that don't return `Result`, clippy wanted us to simply return the called library function. For example:
```rust
uniffi::deps::ffi_support::call_with_output(err, || {
let _retval = rust_library_func();
_retval // clippy prefers if instead of those two lines, we just did "rust_library_func()" and returned that
}
```
Before merging, I'll try this out on `fxa_client` and make sure that it indeed generates clippy safe code. I manually installed `uniffi-bindgen` from local …
=> Generates cargo clippy safe code

CHANGELOG.md, fixtures/uniffi-fixture-time/tests/bindings/test_chronological.py, uniffi_bindgen/src/bindings/python/templates/RustBufferBuilder.py, uniffi_bindgen/src/bindings/python/templates/RustBufferStream.py
I'm not totally sure about this one, but I believe it's an improvement.  Here's snippet showing how the two pieces of code are different (NOTE, the same snippet may give you a different result if you're not in the Eastern timezone):
```
>>> print(datetime.datetime.fromtimestamp(1623965559))
2021-06-17 17:32:39
>>> print(datetime.datetime.fromtimestamp(0) + datetime.timedelta(seconds=1623965559))
2021-06-17 16:32:39
```
OTOH, I don't like the way we have to catch all ValueErrors and convert them to OverflowErrors.  [The python docs say that this was changed in version 3.3](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp).  They also say that there's some errors that get classified as OSErrors.  With this code, they will get misclassified as OverflowErrors. …
=> Fixed timestamp conversion during DST

CHANGELOG.md, uniffi/src/lib.rs, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs
I'm not totally sure about this one, but it seems like it could be an improvement.  What do you all think?
The main motivation is to eliminate the possibility of calling
`try_lift_from_buffer()` on a `RustBuffer` that wasn't created with
`lower_into_buffer()`.  For example, this code seems reasonable, but it
totally fails:
```
let buf: RustBuffer = ViaFfi::lower("Test".to_string());
assert_eq!(try_lift_from_buffer::<String>(buf).unwrap(), "Test")
```
This is because Strings have an asymmetry between `lower()` and
`write()`.  `write()` needs to write out the string length, but
`lower()` can optimize to avoid that and just use `RustBuffer.len`.
It also reduces some boilerplate code, which is nice too.
=> Replace lower_into_buffer and try_lift_from_buffer with a trait

docs/manual/src/udl/functions.md, docs/manual/src/udl/structs.md
While playing around with UniFFI, in order to figure out how we can use it in Glean, I came across these essential things for us: default values.
While implemented it lacks documentation, so I went ahead and added that.
=> Document optional fields & arguments

uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift, uniffi_bindgen/src/interface/mod.rs
Fixes #362 by conditionally providing swift binding depending on the types included in the component interface.
=> Prevent generation of unused swift bindings

CHANGELOG.md, docker/Dockerfile-build, docs/manual/src/kotlin/gradle.md, uniffi/src/ffi/foreignbytes.rs, uniffi/src/ffi/rustbuffer.rs, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt, uniffi_bindgen/src/bindings/python/templates/RustBufferTemplate.py, uniffi_bindgen/src/bindings/ruby/templates/RustBufferTemplate.rb, uniffi_bindgen/src/bindings/swift/templates/BridgingHeaderTemplate.h, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RustBufferTemplate.swift
This (partially) reverts commit 937f9b76f56e52247bb9a53d281554bacba2553e
The upstream JNA bug[1] has been resolved.
JNA 5.7 includes the fix.
We're upgrading our Docker test image to 5.8 already.
Fixes #334
[1]: https://github.com/java-native-access/jna/issues/1259
=> Remove workaround for JNA bug when passing small structs by value.

uniffi/src/ffi/rustcalls.rs, uniffi/src/lib.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs
This makes sense since the idea is that code in FFI-land is taking
ownership of the value.  I think that some of my next work is going to
be easier if write() and lower() both have the same self type.
=> Make `ViaFfi.write()` input an owned value instead of a reference

CHANGELOG.md, uniffi/Cargo.toml, uniffi/src/ffi/ffidefault.rs, uniffi/src/ffi/foreigncallbacks.rs, uniffi/src/ffi/mod.rs, uniffi/src/ffi/rustbuffer.rs, uniffi/src/ffi/rustcalls.rs, uniffi/src/lib.rs, uniffi/src/panichook.rs
This seems like a nice little cleanup.  The `rustcalls` mod was importing
`IntoFfi`, but only using a trivial part of the interface.  Now we just
define our own trait to do that.
I was a slightly worried about this when I initially implemented the
`rustcalls` module, because I was concenced about uniffi consumers defining their own
`ViaFfi` implementation with some other `FfiType`.  However I now realize
this is impossible, we have a `FfiType` enum in the scaffolding code that
spells out the possible types.
The last bit of functionality was the panic handling hook, I just copied
the code for that.
=> Drop ffi-support dependency

uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/error.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/mod.rs
We currently have several methods that want to be able to recurse
through all the types contained within a particular item, such as
`type_contains_object_references` and `type_contains_unsigned_types`.
These methods duplicate the logic for recursing into our various
types of struct and are a bit weird to use.
This commit proposes a cleanup to make these methods appear more
consistent to the caller, and reduce code duplication in their
implementation.
The core idea is a new trait `IterTypes`. It can be implemented by
anything that contains instances of the `Type` enum, and provides a
single method `iter_types` to iterate over the the contained types.
It's designed to encapsulate the recursion logic, e.g. the `IterTypes`
impl for `Object` knows that it needs to recurse into each of the …
=> Add a re-usable abstraction for iterating over contained types.

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.rb, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/scaffolding/templates/macros.rs
This fixes a subtle regression from #983. Prior to that change, we
were returning errors using Rust's builtin `?` operator and thus
performing an implicit `Into::into` conversion on the error value.
This meant that the underlying implementation of a `[Throws=MyErr]`
function could return anything that was `Into<MyErr>` and our scaffolding
would do the right thing.
In #983 we switched to doing an explicit `.map_err` rather than using
the `?` operator, losing the implicit `Into::into` and causing a
subtle breaking change for any consumers that were relying on the
old behaviour. It turns out our Logins component was relying on it.
This commit restores the previous behaviour by adding an explicit
`Into::into`, and a coveralls testcase to prevent regressing it
in future. I think it's worth …
=> Restore implicit `Into` conversion when throwing errors.

CHANGELOG.md, Cargo.toml, fixtures/regressions/fully-qualified-types/Cargo.toml, fixtures/regressions/fully-qualified-types/README.md, fixtures/regressions/fully-qualified-types/build.rs, fixtures/regressions/fully-qualified-types/src/lib.rs, fixtures/regressions/fully-qualified-types/src/test.udl, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs
This fixes #1015, which was a regression in the v0.13.0 release.
Where possible we should be robust against changes in the details of
the Rust code that implements a UniFFI component, but the generated
Rust scaffolding accidentally started assuming that the `HashMap` type
would be in scope for any interface using a map. This turned out not
to be true in practice.
To improve things, this commit makes the generated scaffolding use
fully-qualified type names for `HashMap`, `Vec` and `Option`. There
is probably more we could do on this front (e.g. the `String` type)
but these were low-hanging fruit that fixed a concrete regression,
so that's where I started.
=> Use fully-qualified type names in generated scaffolding code.

uniffi_bindgen/src/scaffolding/templates/macros.rs
Fixes #1018. I didn't make a regression test for this but I did
test it locally against a consume crate that was triggering this
warning.
=> Ignore clippy "redundant closure" warnings in our scaffolding.

uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/interface/types/resolver.rs
This seems required in every iteration of the "external types" effort and can't cause harm, so here I am. Flagging Ryan as he suggested adding `Error` etc in another WIP patch, so is somewhat familiar.
=> Use a predictable canonical_name for types which support being imported

uniffi_bindgen/src/bindings/python/templates/ErrorTemplate.py, uniffi_bindgen/src/bindings/python/templates/RustBufferBuilder.py, uniffi_bindgen/src/bindings/python/templates/RustBufferStream.py, uniffi_bindgen/src/bindings/python/templates/RustBufferTemplate.py, uniffi_bindgen/src/bindings/python/templates/wrapper.py
This came out of a discussion Ryan and I had last week for external types. The idea is that by splitting the "type reader/writer" from the buffer ownership we can support external types in our buffers. For example, external types will end up generating code that looks like:
```python
@staticmethod
def readSomeExternalType(stream):
from some_module import RustBufferTypeReader;
return RustBufferTypeReader.readSomeExternalType(stream)
```
ie, uses the reader from a different module with a stream that we own.
=> Split buffer from the type reader/writer for python.

uniffi/src/testing.rs, uniffi_bindgen/src/lib.rs, uniffi_macros/src/lib.rs
This is a change only for the test runners. It's not clear the semantics are quite correct yet in terms of config file overrides etc, but it should help the "external types" effort keep moving.
=> Allow multiple .udl files in test fixtures

CHANGELOG.md, examples/arithmetic/src/lib.rs, examples/rondpoint/src/lib.rs, examples/todolist/src/lib.rs, fixtures/coverall/src/lib.rs, fixtures/uniffi-fixture-time/src/lib.rs
The "external types" effort will cause us to generate code that will fail
to build if they aren't, and over #1023 @rfk and I agreed this was a
reasonable requirement.
Note this patch doesn't actually enforce the new rule - it was
generated by sprinkling
```
pub struct {{ e.name() }}Wrapper(pub {{ e.name() }});
```
around scaffolding_template.rs and fixing the build errors.
=> The Rust impls of all `dictionary`, `enum` or `error` types must be pub

CHANGELOG.md, docs/contributing.md, uniffi_build/src/lib.rs, uniffi_macros/src/lib.rs
In my local environment I can execute:
```shell
UNIFFI_TESTS_DISABLE_EXTENSIONS=swift:rb cargo test
```
output is nicely:
```
test uniffi_foreign_language_testcase_test_chronological_swift ... ignored
Compiling uniffi-fixture-time v0.13.1 (/mnt/c/src/moz/uniffi-rs/fixtures/uniffi-fixture-time)
Finished dev [unoptimized + debuginfo] target(s) in 3.62s
test uniffi_foreign_language_testcase_test_chronological_kts ... ok
test uniffi_foreign_language_testcase_test_chronological_py ... ok
test result: ok. 2 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 12.16s
```
(as opposed to now, when it's lots of noise about failing to execute ruby and swift)
I think we can declare this as fixing #466 too - that suggests a more automated approach, but I'm not sure that will be …
=> Specifying $UNIFFI_TESTS_DISABLE_EXTENSIONS can skip foreign tests.

CHANGELOG.md, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.rb, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/python/templates/ErrorTemplate.py, uniffi_bindgen/src/bindings/python/templates/RustBufferStream.py, uniffi_bindgen/src/bindings/ruby/templates/ErrorTemplate.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferStream.rb, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs
Sam Edit: Taken over by @skhamis (but don't want to make a new PR for now). Continuing the work Ryan did on this after having a sync before he left. The current best plan is to leverage the `is_flat()` to determine if it's a simple enum vs the new complex error handling. Issue linked below has more details on the matter:
Fixes #1024 by restoring the behaviour of "flat" error enums declared
with the `[Error] enum` syntax. The generated bindings of these errors
will now carry a single `message` field giving the stringified Rust
error.
=> Make "flat" error enums carry a stringified error message.

Cargo.toml, examples/sprites/src/lib.rs, examples/todolist/src/lib.rs, fixtures/uitests/Cargo.toml, fixtures/uitests/README.md, fixtures/uitests/build.rs, fixtures/uitests/src/counter.udl, fixtures/uitests/src/lib.rs, fixtures/uitests/tests/ui/interface_cannot_use_mut_self.rs, fixtures/uitests/tests/ui/interface_cannot_use_mut_self.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.rs, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_macros/Cargo.toml, uniffi_macros/src/lib.rs
We require the implementation of all object structs to be Sync+Send,
and the generated Rust scaffolding will fail to compile if this
requirement is not met. Unfortunately, the failure is currently
triggered via some trait bounds on `FfiConverter` for `Arc<T>`,
so the error message it produces is quite inscrutable and doesn't
help the user debug the underlying issue.
This commit adds an explicit static assertion about the Sync+Send
requirement, which helps the Rust compiler to emit the proper diagnostic
about why the underlying struct is not `Sync` or `Send`. It also has
the added benefit of guarding against any future refactor of the
code that might accidentally factor away the Sync+Send requirement.
Fixes #1048. (Well, not really *fixes* I guess because the code in
experience of …
=> Improve error reporting when an object impl isn't Sync+Send.

uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/swift/gen_swift/compounds.rs, uniffi_bindgen/src/bindings/swift/gen_swift/error.rs, uniffi_bindgen/src/bindings/swift/templates/ArrayTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/DictionaryTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/OptionalTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift
Re-write read and write Swift template calls to go through filters:
* needed to make wrapped types possible in Swift
* needed to land the Callback Interfaces (#1045)
This necessitated moving the structural types to where they are unrolled
(as seen in Kotlin). This, in turn, meant making an `FfiConverter` enum for
each concrete implementation of the structural type declared in the UDL.
This is could also be seen as part of #1047, but not quite.
=> Re-write read and write Swift template calls to go through filters

uniffi/src/testing.rs
Without this, the error message would literally be "Error while running tests: {}" with curly braces in it instead of the exit status.
=> Fix missing fmt argument in error message

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/error.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt, uniffi_bindgen/src/bindings/kotlin/templates/MapTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/OptionalTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/SequenceTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
More changes extracted out of the `uoc-macro-dispatch` PR.  These change how we name things on Kotlin.  If this seems good, then we can do something similar for Python/Swift.
There's a couple changes here.  The goal is to make generating names in the template code simple and consistent.
- Use "name" in general rather than "label".  I'm definitely open to changing this one, but in my mind "label" to signifies something human to read rather than a machine name.
- Remove the "_kt" suffix at the end of template function names.  This seems like extra typing without much benefit.
- Added a `name` filter function.  The idea is that you send it some `ComponentInterface` item and it generates the proper name for it.  It works with `Record`, `Enum`, etc. as well as `Field` and `Argument`.  Added …
=> Naming refactor

uniffi_bindgen/src/bindings/python/gen_python/compounds.rs, uniffi_bindgen/src/bindings/python/gen_python/enum_.rs, uniffi_bindgen/src/bindings/python/gen_python/error.rs, uniffi_bindgen/src/bindings/python/gen_python/external.rs, uniffi_bindgen/src/bindings/python/gen_python/function.rs, uniffi_bindgen/src/bindings/python/gen_python/miscellany.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/object.rs, uniffi_bindgen/src/bindings/python/gen_python/primitives.rs, uniffi_bindgen/src/bindings/python/gen_python/record.rs, uniffi_bindgen/src/bindings/python/gen_python/wrapped.rs
This was done in #1091, but missed in the recent Python UoC work
=> Use correct path to backend module

uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt
I want to check out a hunch that this is returning null sometimes, which
causes issues like
https://github.com/mozilla/application-services/issues/4640.
=> Added a check on Kotlin for RustBuffer.alloc()

CHANGELOG.md, docs/release-process.md, release.toml, uniffi/release.toml
This seems to work well with a newer `cargo-release` - so well I accidentally published 0.15.0 to crates.io 😅 which I've since yanked.
(I'd like to make a new 0.15.1 for use by app-services, so after approval and landing, feel free to test it out! Otherwise I'll cut a new release tomorrow.)
=> Update to new version of cargo release which has better workspace support

uniffi_bindgen/src/backend/types.rs, uniffi_bindgen/src/bindings/python/gen_python/compounds.rs, uniffi_bindgen/src/bindings/python/gen_python/enum_.rs, uniffi_bindgen/src/bindings/python/gen_python/error.rs, uniffi_bindgen/src/bindings/python/gen_python/external.rs, uniffi_bindgen/src/bindings/python/gen_python/miscellany.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/object.rs, uniffi_bindgen/src/bindings/python/gen_python/primitives.rs, uniffi_bindgen/src/bindings/python/gen_python/record.rs, uniffi_bindgen/src/bindings/python/gen_python/wrapped.rs
Now every type knows how to coerce itself.
So far only Python needs that (Kotlin/Swift rely on the type system,
Ruby hasn't been migrated to UoC yet)
---
Follow up to #1081
=> Python: Extract type coercing into a `CodeType` method

uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt
Fixes #1098, closes #1099 to allow interop with Java.
This is really #1099 with some light rebasing. I've already asked external contributor @l-maia to rebase once, and I don't think it's fair to ask him a second time. I've approved his work already, so a rubber stamp approval is needed to make github happy.
=> Add throws annotation to kotlin exceptions [originally 1099]

uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs
fixes #1123 
Noticed that a bunch of the FfiConverterTypes sneak their way into the `cargo doc` of the consumer, eg: https://mozilla.github.io/application-services/book/rust-docs/fxa_client/index.html#structs
Consumers of libraries that use `uniffi` shouldn't need to know about those structs and can cause some mild confusion
=> Hides FFIConverterTypes from cargo doc

uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
This causes a whole bunch of Swift warnings during the build:
'fileprivate' modifier is redundant for static method declared in a fileprivate extension
=> Remove 'fileprivate' modifier inside a fileprivate extension.

CHANGELOG.md, docs/manual/src/udl/ext_types_wrapped.md, fixtures/ext-types/guid/Cargo.toml, fixtures/ext-types/guid/src/guid.udl, fixtures/ext-types/guid/src/lib.rs, fixtures/ext-types/guid/tests/bindings/test_guid.py, fixtures/uitests/tests/ui/interface_cannot_use_mut_self.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_bindgen/src/scaffolding/templates/macros.rs
This gets close, but strikes a mismatch between the `Err` types.
=> Allow errors converting custom types to propagate

docs/contributing.md
`gem install FFI` doesn't work, the gem should install via `gem install ffi` according to [here](https://github.com/ffi/ffi).
```
➜  uniffi-rs gem install FFI
Ignoring iStats-1.6.1 because its extensions are not built. Try: gem pristine iStats --version 1.6.1
ERROR:  Could not find a valid gem 'FFI' (>= 0) in any repository
```
=> Update FFI Ruby gem install command

CHANGELOG.md, Cargo.toml, docs/manual/src/SUMMARY.md, docs/manual/src/swift/configuration.md, docs/manual/src/swift/overview.md, fixtures/swift-omit-labels/Cargo.toml, fixtures/swift-omit-labels/README.md, fixtures/swift-omit-labels/build.rs, fixtures/swift-omit-labels/src/lib.rs, fixtures/swift-omit-labels/src/omit_argument_labels.udl, fixtures/swift-omit-labels/tests/bindings/test_omit_argument_labels.swift, fixtures/swift-omit-labels/tests/test_generated_bindings.rs, fixtures/swift-omit-labels/uniffi.toml, uniffi_bindgen/src/bindings/swift/gen_swift/callback_interface.rs, uniffi_bindgen/src/bindings/swift/gen_swift/function.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/object.rs, uniffi_bindgen/src/bindings/swift/templates/macros.swift
PR is a strawman. See the details first:
For the default function definition, e.g. `myfun(parameterName: Int)`, Swift requires passing in named parameters: `myfun(parameterName: 3)`.
This can be changed by either adding another label `myfun(newLabel parameterName: Int)` and be called like `myfun(newLabel: 3)`.
Or you can omit the label with `myfun(_ parameterName: Int)` and call it like `myfun(3)`.
Currently UniFFI always generates the first form.
Sometimes that makes the functions read better when called.
But for Glean's API it makes it slightly awkward because now these labels become required:
```swift
GleanMetrics.cat.myCounter.add(amount: 1)
```
It also means that the names we define in the UDL are part of the public API and so changing them will break users.
For Glean I now have 4 …
=> [Swift] Omit argument labels in functions

uniffi/src/lib.rs, uniffi_bindgen/src/scaffolding/templates/macros.rs
As @bendk suggested in #1126, we can move lots of the generated boilerplate into the uniffi crate. This almost works - it's types all the way down and my brain is melting :)
I think the failure to handle `Arc` is tractable, but I guess my biggest concern are the `uitest` changes - it makes user-facing error messages intractable. I'll keep playing, but thoughts welcome about whether this is actually an improvement or not? The generated+formatted code without this patch isn't *that* bad - one `match` per arg still leaves it readable, just verbose. I'm on the fence.
=> Move generated arg lowering/error code into a helper function

CHANGELOG.md, examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, examples/wrapper-types/Cargo.toml, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/ext-types/guid/Cargo.toml, fixtures/ext-types/lib/Cargo.toml, fixtures/ext-types/uniffi-one/Cargo.toml, fixtures/external-types/crate-one/Cargo.toml, fixtures/external-types/crate-two/Cargo.toml, fixtures/external-types/lib/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/regressions/fully-qualified-types/Cargo.toml, fixtures/regressions/kotlin-experimental-unsigned-types/Cargo.toml, fixtures/swift-omit-labels/Cargo.toml, fixtures/uitests/Cargo.toml, fixtures/uniffi-fixture-time/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
Releases version 0.16.0, versions already pushed to crate.io
=> (cargo-release) version 0.16.0

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
#1102 
...or we'd better pretend **ALL** local variables and paramaters with `_`?
=> add `_` for local variables for kotlin template when necessary

.circleci/config.yml, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py
First of the `*.so` file extension is valid on more than just Linux,
e.g. on BSD and Solaris too.
We can just consider it the default case and only change it for Windows
and macOS.
Next, for final deployment the compiled library can be placed next to
the Python code and that way the wrapper code can find it by its
absolute path.
---
this is what we currently [do support Glean Python](https://github.com/mozilla/glean/blob/b2f72f861f17339689f7c6881bd8471bbcd79b88/glean-core/python/glean/_ffi.py#L21-L36).
=> Load Python library from absolute path

fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi/src/ffi/rustbuffer.rs, uniffi_bindgen/src/scaffolding/templates/RustBuffer.rs
This is to help support the desktop JS bindings that we're currently working on.  See #1153 for more details.
=> Add top-level "C" functions for RustBuffer (#1153)

fixtures/ext-types/guid/src/guid.udl, fixtures/ext-types/guid/src/lib.rs, fixtures/ext-types/guid/tests/bindings/test_guid.py, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/callback_interface.rs, uniffi_bindgen/src/scaffolding/mod.rs
We just needed to implement `type_rs()`.  Amazingly, we were able to get away
with not defining this filter until now.
The other issue was that the Kotlin callback interface code depends on
AtomicLong, but it doesn't import that type.  I guess we were able to
get away with this because callback interfaces were always paired with
objects, which do import AtomicLong.
=> Added support for custom types in callback interfaces (#1178)

examples/app/ios/README.md
Thank you for providing a great library!
I am honored to have you confirm the Pull Request!
I look forward to your review.
I fixed ios/README.md.
While creating the library for iOS application, I noticed the README typo.
I changed it because the Shell Script inside the directory is not called.
=> [FIX] fix typo README ios/app. univeral->universal

Cargo.toml, docs/manual/src/tutorial/Rust_scaffolding.md, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/reexport-scaffolding-macro/Cargo.toml, fixtures/reexport-scaffolding-macro/src/lib.rs, uniffi/src/ffi/rustcalls.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/scaffolding/templates/ReexportUniFFIScaffolding.rs, uniffi_bindgen/src/scaffolding/templates/scaffolding_template.rs
This can be used to work around [rust-lang#50007](https://github.com/rust-lang/rust/issues/50007), which is getting to be more and more of an issue on the desktop JS project.
=> Added the `uniffi_reexport_scaffolding` macro

uniffi/src/lib.rs, uniffi_bindgen/src/lib.rs
These are the first bits needed to implement an external binding generator that lives in an outside crate.
Most of the changes are in the `uniffi_bindgen/src/lib.rs` to define a trait `BindingGenerator` that an external crate can use to take advantage of the logic in `uniffi` to parse the `udl` into a `ComponentInterface`.
This is not a breaking change, and only exposes the functionality (it doesn't change the existing crates)
cc @bendk @mhammond
=> Allow external crates to write their own binding generators

CHANGELOG.md, docs/manual/src/udl/custom_types.md, fixtures/ext-types/lib/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/custom.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/external.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/CustomTypeTemplate.kt, uniffi_bindgen/src/bindings/python/gen_python/custom.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/CustomType.py, uniffi_bindgen/src/bindings/swift/gen_swift/custom.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/CustomType.swift, uniffi_bindgen/src/interface/types/mod.rs
(This is like a mini version of #1189.  That one contains more changes.  I like the changes, but others may not or just want time to review them.  I don't want to block the desktop JS project, so I'm making a smaller PR that can get approved quicker).
Removed the `Config` field from the `CodeOracle` structs.  This allows the struct to be state-less, which makes the filter code threadsafe (#1188).
The main thing we were using the config for was custom types, since the type name depeneded on a config value.  Changed that so we always use the name from the UDL file as the type name, then create a type alias in the helper code.  PR #1189 takes this idea a lot further, this is like a mini version of that.
The other type that needed changes was external types.  But this was much simpler, we …
=> Make binding generation threadsafe (#1188)

Cargo.toml, examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/custom-types/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/ext-types/guid/Cargo.toml, fixtures/ext-types/lib/Cargo.toml, fixtures/ext-types/uniffi-one/Cargo.toml, fixtures/external-types/lib/Cargo.toml, fixtures/reexport-scaffolding-macro/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/regressions/fully-qualified-types/Cargo.toml, fixtures/regressions/kotlin-experimental-unsigned-types/Cargo.toml, fixtures/swift-omit-labels/Cargo.toml, fixtures/uniffi-fixture-time/Cargo.toml, uniffi_testing/Cargo.toml, uniffi_testing/README.md, uniffi_testing/src/lib.rs
Added code to allow external bindings crates to find the UDL files and cdylibs for examples/fixtures.  Made a new crate for this, since I didn't want to pull in `serde` as a dependency for `uniffi`. Eventually, this can replace `uniffi/testing.rs` and we can remove some other dependencies from `uniffi` like `cargo_metadata`.
This commit adds a testing framework that works with external bindings, but we're not actually using it yet.  The plan is to use is for the desktop JS bindings, whose code will live in moz-central.
For an example of how this code would be use, take a look at #1205.  It moves the existing bindings to separate crates and switches them to using this testing framework.
=> Adding support for external fixture/example tests

fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/reexport-scaffolding-macro/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/swift-omit-labels/Cargo.toml, fixtures/uitests/Cargo.toml, uniffi_testing/Cargo.toml
cc @bendk 
Firefox desktop won't let us vendor crates without licenses (I think crates.io will also complain), so I added them wherever I saw them missing
=> Adds missing licenses and authors

docs/manual/src/Overview.md
I was looking at some docs from Ben, which had a link to https://mozilla.github.io/uniffi-rs/, and I noticed that page didn't actually link to uniffi itself - this PR fixes that.
=> Have the manual link back to the repo

uniffi_bindgen/src/interface/object.rs
This function is useful for external bindgen tools.  I want to use it
for the gecko-js bindings. I think it makes sense for this constructor
to be public, since the `primary_constructor` and
alternate_constructors()` functions are public.
=> Make is_primary_constructor() public

uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/lib.rs
This upgrades `clap` to version 3.0 via "derive" macros. It seems a bit cleaner to me, and it also seems less error prone, as it highlighted the fact that a `--manifest-path` option was specified for the `generate` command but it was unused.
It enabled more features of `clap` and no longer specifies `default-features = false` - so we get color options etc. I can't see a good reason to avoid that for this use-case, but I might be missing the reason it was done this way in the first place.
I *think* it's complete, but have a local test failure I can't explain, so we'll see what CI says. There's also another PR which sticks with the `builder` interface which I'll put up for comparison, but I'm leaning towards this being the better option.
=> Update to clap v3 using derive macros

uniffi/src/ffi/rustbuffer.rs
I think we're better off without these tests for a few reasons:
- I don't have confidence that these tests are testing what they say
they are.  It also seems likely that the panics are caused by a)
trying to allocate a 2GB Vec and b) trying to use a Vec with
`len > capacity`.
- The code they're testing is hard to get wrong.  If we're trying to
coerce a `u32` into an `i32` and the value overflows, it seems like you
would have to go out of your way not to panic.
- jplatte pointed out that having even `u8` data that's uninitialized
causes undefined behavior (https://github.com/mozilla/uniffi-rs/pull/1215/files/bc655fc8fc2b67b3d2090659ba9bb254e5ea6866#r850255739)
I'm definitely open to a conversation about this though.  I know there are lots of philosophies on unit testing.
=> Removing a couple of RustBuffer tests

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.swift, fixtures/uitests/src/records.udl, fixtures/uitests/tests/ui/non_hashable_record_key.rs, fixtures/uitests/tests/ui/non_hashable_record_key.stderr, uniffi/src/lib.rs, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/backend/types.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/compounds.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/MapTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/python/gen_python/compounds.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/MapTemplate.py, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferStream.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferTemplate.rb, uniffi_bindgen/src/bindings/swift/gen_swift/compounds.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/MapTemplate.swift, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/interface/types/resolver.rs, uniffi_bindgen/src/scaffolding/mod.rs
Right now UniFFI only supports `record<DOMString, T>`, that is maps with a string key.
These are expressed as `HashMap<String, T>` on the Rust side and `[String: T]` on the Swift side.
All languages we target can easily support non-string keys.
Only weedle (the UDL parser) has it hardcoded to `DOMString` (and 2 other string types). 
We could losen this restriction and allow arbitrary key types (as long as they can be hashed).
This requires a single extra commit in Weedle: https://github.com/badboy/weedle/commit/90031e37d491104b9cd9572e7c3d6d214da39fa0
~~The commits here are not perfect yet, so treat them as a prototype (they certainly lack tests for the other languages).~~
~~Right now it's also not doing any checks on the key type, so you could specify even floats or nested records as …
=> Allow integer keys in records (hashmaps)

uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift
Somehow this now breaks for me on swiftlang-5.6.0.323.62 clang-1316.0.20.8 for the callback example tests.
=> Do not provide library link search path

fixtures/uitests/tests/ui/non_hashable_record_key.stderr, uniffi_bindgen/src/interface/types/resolver.rs, uniffi_bindgen/src/scaffolding/templates/scaffolding_template.rs
This removes the explicit type check in code,
moving the assertion to the generated scaffolding code,
in order to improve the error message.
Fixes #1221
---
I'm not perfectly happy with this solution, but it's the best I could do for now.
=> Assert that record keys satisfy HashMap requirements (Eq & Hash)

fixtures/uitests/tests/ui/non_hashable_record_key.stderr
Seems like the output changed in some version between Rust 1.57 and 1.60
=> Re-generate expected output for non_hashable_record_key test

uniffi_bindgen/Cargo.toml
3.0 to <=3.0.14 do not work
It will fail with something like this:
error[E0405]: cannot find trait `CommandFactory` in crate `clap`
--> uniffi_bindgen/src/lib.rs:499:10
|
499 | #[derive(Parser)]
|          ^^^^^^ not found in `clap`
|
= note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)
This seems to have been fixed in 3.1
Changelog is here: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#310---2022-02-16
=> Require at least clap v3.1

fixtures/reexport-scaffolding-macro/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/mod.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/ruby/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_build/Cargo.toml, uniffi_build/src/lib.rs, uniffi_macros/Cargo.toml, uniffi_macros/src/lib.rs, uniffi_testing/Cargo.toml, uniffi_testing/src/lib.rs, weedle2/Cargo.toml, weedle2/tests/webidl.rs
Basically a follow-up to #1235.
The main commits are the final two: the first one introduces `camino`s `Utf8Path(Buf)` types in more places and the second one replaces `std::fs` by the `fs_err` crate, which improves error messages by attaching the file or directory path upon which an operation was attempted.
The first three commits are just drive-by improvements that should be obvious 🙂
=> Further improve fs / path code

fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/regressions/fully-qualified-types/Cargo.toml, fixtures/regressions/kotlin-experimental-unsigned-types/Cargo.toml, fixtures/swift-omit-labels/Cargo.toml
This might improve test compilation times. At worst, it's only a small simplification of a few manifests.
=> Remove crate-lib = "lib" from some fixtures that don't need it

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs
All push(_str) chains started off with an empty string and were really just assignments spread out over multiple lines.
=> Replace uses of String::push_str

uniffi_bindgen/src/interface/object.rs
A patch for #1263 
The name of the return type of constructors was not correct
=> Fixes name of RustArcPointer on constructors

.circleci/config.yml, docs/policies/rust-versions.md
As noted in #1242, our Rust policy wasn't as clear as it could be, so I attempted to fix it. I also changed the language about uniffi not currently being in mozilla-central - while that's true today, it look like landing very soon, so I tried to future-proof that. @jplatte, I can't add you as a reviewer, but would like your feedback anyway.
=> Clarify our Rust version policy

uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/lib.rs
Fixes #1272, [edit to remove references to bumping the clap version]
=> Pin to clap 3.1 and modernize some aspects of clap usage.

.gitignore, Cargo.toml, fixtures/reexport-scaffolding-macro/src/lib.rs, fixtures/simple-fns/Cargo.toml, fixtures/simple-fns/README.md, fixtures/simple-fns/build.rs, fixtures/simple-fns/src/lib.rs, fixtures/simple-fns/src/simple-fns.udl, fixtures/simple-fns/tests/bindings/test_simple_fns.kts, fixtures/simple-fns/tests/bindings/test_simple_fns.py, fixtures/simple-fns/tests/bindings/test_simple_fns.swift, fixtures/simple-fns/tests/test_generated_bindings.rs, fixtures/simple-fns/uniffi.toml, uniffi/Cargo.toml, uniffi/src/lib.rs, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/macro_metadata.rs, uniffi_macros/Cargo.toml, uniffi_macros/src/export.rs, uniffi_macros/src/export/metadata.rs, uniffi_macros/src/export/metadata/function.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/util.rs, uniffi_meta/Cargo.toml, uniffi_meta/src/lib.rs
Based on #1258.
First part of #1257.
=> Add initial proc-macro frontend bits

examples/rondpoint/src/lib.rs, fixtures/coverall/src/lib.rs, fixtures/reexport-scaffolding-macro/src/lib.rs, uniffi/src/ffi/rustcalls.rs, uniffi/src/lib.rs, uniffi/src/panichook.rs, uniffi/src/testing.rs, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/macro_metadata.rs, uniffi_build/src/lib.rs, uniffi_macros/src/export/metadata/function.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/util.rs, uniffi_testing/src/lib.rs
=> Make use of implicit format string arguments

CHANGELOG.md, examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/custom-types/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/ext-types/guid/Cargo.toml, fixtures/ext-types/lib/Cargo.toml, fixtures/ext-types/uniffi-one/Cargo.toml, fixtures/external-types/crate-one/Cargo.toml, fixtures/external-types/crate-two/Cargo.toml, fixtures/external-types/lib/Cargo.toml, fixtures/reexport-scaffolding-macro/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/regressions/fully-qualified-types/Cargo.toml, fixtures/regressions/kotlin-experimental-unsigned-types/Cargo.toml, fixtures/swift-omit-labels/Cargo.toml, fixtures/uitests/Cargo.toml, fixtures/uniffi-fixture-time/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml, uniffi_testing/Cargo.toml
Merging back the 0.19.0 release changes.
I had some issues using `cargo release` for this one.  The `uniffi_macros` changes depended on a change in `uniffi_build`, which lead to an error when I tried the dry run.  I ended up creating 2 commits for the release and also needing to manually run `cargo publish` a couple times.  AFAICT this all worked out and everything is correct, there's just 2 commits instead of one.
=> Release v0.19.x

uniffi_bindgen/Cargo.toml, uniffi_meta/Cargo.toml
This isn't published yet, but the version needs to match the other
crate's Cargo.toml files.
=> Changing uniffi_meta version to 0.19.0

uniffi_bindgen/Cargo.toml
The problematic deprecation warnings are now opt-in.
=> Unpin clap

Cargo.toml, fixtures/regressions/missing-newline/Cargo.toml, fixtures/regressions/missing-newline/README.md, fixtures/regressions/missing-newline/build.rs, fixtures/regressions/missing-newline/src/lib.rs, fixtures/regressions/missing-newline/src/test.udl, fixtures/regressions/missing-newline/tests/bindings/test.py, fixtures/regressions/missing-newline/tests/test_generated_bindings.rs
This is already fixed in `main`, but was an issue in 0.19.1
=> New regression test: We missed a newline

CHANGELOG.md, fixtures/uniffi-fixture-time/tests/bindings/test_chronological.rb, fixtures/uniffi-fixture-time/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferStream.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferTemplate.rb
This PR fixes #469. Both `Timestamp` and `Duration` are implemented through ruby `Time` class for the lack of better way to represent `Duration`. Please have a look at your convenience and let me know if you need more details.
=> Implement Timestamp and Duration types in Ruby backend

uniffi_bindgen/src/lib.rs
Badboy's fix for sccache builds (https://bugzilla.mozilla.org/show_bug.cgi?id=1774585).
I'm hoping to get r+ on this, but let's wait to merge it until we get approval in that thread that the fix is going to work for moz-central.
=> Include the askama config file into the build

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/interface/record.rs
As noted in #1058, our [documentation](https://mozilla.github.io/uniffi-rs/udl/structs.html) promises dictionaries can have fields which are interfaces, so long as they are behind an `Arc`. It turns out this works fine in the scaffolding and even in all the bindings [edit: removed references to "bindings generate invalid code" - turns out I used a kotlin keyword - that's now supported!]
Fixes #1058
=> Allow dictionaries to have fields which are interfaces

docs/manual/src/udl/callback_interfaces.md
I got thrown off trying to follow these examples. This PR updates the documentation to match what worked for us!
=> Fix types in the callback interfaces examples

CHANGELOG.md, fixtures/callbacks/src/callbacks.udl, fixtures/callbacks/src/lib.rs, fixtures/callbacks/tests/bindings/test_callbacks.kts, fixtures/callbacks/tests/bindings/test_callbacks.py, fixtures/callbacks/tests/bindings/test_callbacks.swift, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift
There was a mismatch in swift in the arguments of the callback interface, when calling the callback interface, the swift code generates snake_case arguments instead of camelcase.
I could define a unique test for this, but I changed the existing test instead, happy to go back and make a regression test for it though!
=> Fixes argument names for callback interfaces in swift to be camelcase

Cargo.toml, fixtures/regressions/swift-callbacks-omit-labels/Cargo.toml, fixtures/regressions/swift-callbacks-omit-labels/README.md, fixtures/regressions/swift-callbacks-omit-labels/build.rs, fixtures/regressions/swift-callbacks-omit-labels/src/lib.rs, fixtures/regressions/swift-callbacks-omit-labels/src/test.udl, fixtures/regressions/swift-callbacks-omit-labels/tests/bindings/test.swift, fixtures/regressions/swift-callbacks-omit-labels/tests/test_generated_bindings.rs, fixtures/regressions/swift-callbacks-omit-labels/uniffi.toml, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift
This also adds a test to make sure we're not breaking it again.
Fixes #1312
=> Apply `omit_argument_labels` option when calling into a callback

examples/callbacks/Cargo.toml, examples/callbacks/uniffi.toml
I want to use this to test callbacks on desktop JS. This makes it
consistent with other examples.
=> Adding `uniffi_` prefix to the callback example

.circleci/config.yml, examples/sprites/src/lib.rs, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, fixtures/uitests/tests/ui/non_hashable_record_key.stderr, rust-toolchain.toml, uniffi_bindgen/src/interface/types/resolver.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs
As per our [Rust version policy](https://github.com/mozilla/uniffi-rs/blob/main/docs/policies/rust-versions.md)
Requires some clippy fixes. Also fixed some clippy complaints in nightly.
=> Update Rust to 1.63, MSR to 1.61.0

uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs
The bindings were sending a `RustCallbackStatus` out param that the
scaffolding didn't have.  This worked out okay in practice, but we
should have the signatures match.
=> Fix callback interface init signature #1325

fixtures/callbacks/Cargo.toml, fixtures/external-types/crate-one/Cargo.toml, fixtures/external-types/crate-two/Cargo.toml, fixtures/simple-fns/Cargo.toml, fixtures/uitests/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_macros/Cargo.toml, uniffi_meta/Cargo.toml, uniffi_meta/src/lib.rs
I feel like this dependency doesn't really carry its weight.
=> Drop the dependency on `enum_variant_macros` used for a single `From` implementation

uniffi_bindgen/src/macro_metadata/extract.rs
I had `uniffi-fixture-simple-fns` fail locally (M1 macbook) because it encountered every function twice. It seems the code was set up to avoid that, but never actually stored the name and so ran into this.
=> Cache an extracted item name after parsing it from the library file

uniffi_macros/src/export.rs, uniffi_macros/src/export/metadata.rs, uniffi_macros/src/export/metadata/function.rs, uniffi_macros/src/export/scaffolding.rs
With this PR, serializing and emitting the generated metadata is no longer part of collecting the metadata and generating the scaffolding code, respectively.
=> Clearly separate different parts of the exports macro

uniffi_bindgen/src/lib.rs
I want to use this in the FF desktop code and in general it seems useful for external bindings.
=> Make guess-crate-root public

CHANGELOG.md
I'm hoping to release v0.20.0, this updates the changelog with the breaking changes.
=> Updating the changelog in preparation of v0.20.0

CHANGELOG.md
The change was introduced here: https://github.com/mozilla/uniffi-rs/commit/16ac8d6937550a74e79c824896e1cbb0279130e3#diff-522f0ef157bc0a32453bafd790a9058a35cbb8a721df58a9b51b1ec6b74db5caR263
We're noticing it in here: https://github.com/mozilla-mobile/android-components/pull/12781
=> Adding a note on a 0.19.0 breaking change that we didn't notice.

CHANGELOG.md, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/macros.rb, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/object.rs
Added a bool function that returns if a function throws or not. Named this one "throws" and renamed the old method to "throws_name". We could almost get rid of that one, but it's still used by the Ruby code
This is just a bit of prep work for getting callback interface errors working.
=> Refactored the throws code

CHANGELOG.md, Cargo.toml, fixtures/keywords/README.md, fixtures/keywords/swift/Cargo.toml, fixtures/keywords/swift/build.rs, fixtures/keywords/swift/src/keywords.udl, fixtures/keywords/swift/src/lib.rs, fixtures/keywords/swift/tests/bindings/test_keywords.swift, fixtures/keywords/swift/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs
This change is based on #1237 but isn't quite as complete. I wasn't able to get reserved words working as a pub fn in the namespace. I need this fix to to expose an API in a project I'm working on that is using a Swift reserved word (`internal`) as an enum variant name. 
If I can get this PR ready to merge I'm also happy to do a corresponding change for the master branch. If you'd rather I do the master branch change first I can do it that way, I started with 0.19 because that the version of uniffi my project is currently using.
=> Add Swift bindings generation support for reserved words

fixtures/simple-fns/src/lib.rs, uniffi_bindgen/src/interface/types/mod.rs
For some reason the fix didn't work when I tried it on matrix-rust-sdk last week, but now I've added a dedicated test to UniFFI directly and that works. So this at least partially fixes the broken bindings I've been having issues with.
=> Update add_known_type to add inner types of generic builtins

fixtures/callbacks/Cargo.toml, fixtures/callbacks/src/callbacks.udl, fixtures/callbacks/tests/bindings/test_callbacks.kts, fixtures/callbacks/tests/bindings/test_callbacks.py, fixtures/callbacks/tests/bindings/test_callbacks.swift, fixtures/reexport-scaffolding-macro/src/lib.rs
This changes the fixtures/callbacks library name so that it doesn't collide with examples/callbacks.  It prevents `output filename collision` warnings when running `cargo build`
=> Remove a library namespace collition

Cargo.toml, fixtures/proc-macro/Cargo.toml, fixtures/proc-macro/README.md, fixtures/proc-macro/build.rs, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/src/proc-macro.udl, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, fixtures/proc-macro/tests/test_generated_bindings.rs, fixtures/proc-macro/uniffi.toml, uniffi/src/lib.rs, uniffi_bindgen/src/backend/types.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/metadata.rs, uniffi_macros/src/export/metadata/convert.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/record.rs, uniffi_meta/src/lib.rs
Part of #1257.
Adds a `#[derive(uniffi::Record)]` macro and updates `#[uniffi::export]` to allow usage of arbitrary types as long as they don't have generics and are available under `crate::uniffi_types` and have the right trait implementation.
Outside of `uniffi::export`, when generating bindings, the names of such types are resolved against the known type definitions from both UDL and derives like `Record` (`Enum` might come next).
=> Add support for records (dictionaries / structs) to the proc-macro frontend

docs/manual/src/udl/callback_interfaces.md
Updated the trait interface example to match current practice.
=> docs: Fix trait definition in callback interface

docs/manual/src/udl/callback_interfaces.md, examples/callbacks/Cargo.toml, examples/callbacks/src/callbacks.udl, examples/callbacks/src/lib.rs, examples/callbacks/tests/bindings/test_callbacks.kts, examples/callbacks/tests/bindings/test_callbacks.py, examples/callbacks/tests/bindings/test_callbacks.swift, fixtures/callbacks/Cargo.toml, fixtures/callbacks/src/callbacks.udl, fixtures/callbacks/src/lib.rs, fixtures/callbacks/tests/bindings/test_callbacks.kts, fixtures/callbacks/tests/bindings/test_callbacks.py, fixtures/callbacks/tests/bindings/test_callbacks.swift, fixtures/uitests/src/errors.udl, fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.rs, fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.stderr, uniffi/src/ffi/foreigncallbacks.rs, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceTemplate.py, uniffi_bindgen/src/bindings/python/templates/ErrorTemplate.py, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs
This is a work-in-progress for handling exceptions in callback interfaces.  It changes a few things:
- The `Throws` attribute is now offecially supported on CallbackInterface methods, allowing callback interfaces to specify which errors they will throw.  If we catch one of those exceptions, we serialize it to the `RustBuffer` that's normally used for the return value and send it back to Rust.
- On the Rust side, this means the callback interface trait methods need to change to return `Result<T>` instead of `T`.
- For now, `Throws` is optional and we fall back on the old behavior if it's not present.  But this is deprecated.
- We also handle unexpected exceptions in callback interface.  If we see one of those, we stringify it and serialize it to the `RustBuffer`.  This gets converted into …
=> Callback exceptions

uniffi/src/lib.rs, uniffi/tests/ui/proc_macro_arc.stderr, uniffi_bindgen/src/lib.rs, uniffi_macros/src/export.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
We have this lint enabled in our project and for some reason while it doesn't trigger for generated code in one crate, it does in another. This should clean that up.
=> proc-macro: unused-qualifications lint cleanup

CHANGELOG.md, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.rb, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/ruby/templates/ErrorTemplate.rb
Improved stringifying errors defined interfaces in the UDL.
- Added message method in Kotlin and a test for it
- Added to_s method in Ruby and a test for it
- Swift already supported this, added tests for it
- Python already supported this and had tests
I'm hoping to switch the application-services errors to using this style, but don't want it to be a downgrade in the quality of our log messages.
=> Better stringify support for fielded errors

uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs
We can't control where `eprintln` goes (heck, I saw it fail and blow up things). We already have logging, so let's use that.
=> Use the log facade instead of directly error printing

docs/manual/src/udl/callback_interfaces.md
This was brought up as an issue from the DOM team when discussing the JS implementation, but it's really a general issue for all bindings.  It seems like a good idea to add this warning to the docs.
=> Adding a warning about circular references with callback interfaces

docs/manual/src/udl/errors.md
Fixes #1380
When `[Enum]` is used, the Rust code compiles fine and the code generation completes, but it leads to an error in Swift:
```
...: error build: Global function 'rustCallWithError' requires that 'FfiConverterTypeLeadsError.SwiftType' (aka 'LeadsError') conform to 'Error'
```
Changing the annotation to `[Error]` works as expected (in v 0.21).
... and a small typo fixed.
=> Use [Error] rather than [Enum] on rich errors.

fixtures/proc-macro/src/proc-macro.udl, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/literal.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/macro_metadata/ci.rs
… as long as all definitions are exactly the same. Required to use an enum or record in the signatures of both proc-macro-exported functions as well as UDL functions within one API.
Related to #1257.
=> Permit redundant definition of records and enums

docs/manual/src/udl/callback_interfaces.md, examples/callbacks/tests/bindings/test_callbacks.kts, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceTemplate.kt, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs
The recent failures of [updating Glean in Focus](https://github.com/mozilla-mobile/focus-android/pull/7902) were a bit harder to debug than I would have liked to.
The UniFFI update caused a new panic due to some bad interaction of the code (an uncaught exception), but that exception was no where visible.
This PR adds the exception message to the panic message, see the last commit.
Along the way I fixed some typos and docs.
(Note that the _correct_ solution for Glean will be to return a Result, that will be handled in [bug 1797262](https://bugzilla.mozilla.org/show_bug.cgi?id=1797262)).
https://github.com/mozilla/uniffi-rs/commit/909e70a92ca6db10d2a194f8ca2bc6a9be5913a2 has an example to trigger the panic. Probably can't add that as a proper test because ... well, can't catch that panic …
=> Try adding callback error to panic message

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/macro_metadata/ci.rs
=> proc-macro: Some improvements to unresolved types

docs/adr/0001-mvp-webidl.md, docs/adr/0002-serialize-complex-datatypes.md, docs/adr/0004-only-threadsafe-interfaces.md, docs/adr/0005-arc-pointers.md, docs/adr/0006-wrapping-types.md, docs/adr/0007-enable-implementing-bindings-seperately.md, docs/manual/src/tutorial/Rust_scaffolding.md
"focussed" is technically an accepted spelling, but it's rather uncommon, so I changed that too.
=> Fix some typos in ADRs and manual

uniffi_bindgen/src/scaffolding/templates/macros.rs
Callback interfaces with long names break formatting with the latest version of `uniffi_bindgen` and `rustfmt`.
Example `.udl` file:
```
callback interface CallbackWithALongName {
void test();
};
namespace test {
void test(CallbackWithALongName callback);
};
```
```sh
$ uniffi-bindgen scaffolding src/test.udl
error[internal]: left behind trailing whitespace
--> .../src/test.uniffi.rs:71:71:1
|
71 |         
| ^^^^^^^^
|
error[internal]: left behind trailing whitespace
--> .../src/test.uniffi.rs:73:73:1
|
73 |         
| ^^^^^^^^
|
warning: rustfmt has failed to format. See previous 2 errors.
Error: rustmt failed when formatting scaffolding. Note: --no-format can be used to skip formatting
$ uniffi-bindgen --version
uniffi-bindgen 0.21.0
$ rustfmt --version
rustfmt 1.5.1-stable (a55dd71d …
```
=> Remove trailing spaces that break rustfmt

uniffi_bindgen/src/scaffolding/templates/macros.rs
One more fix like #1399. It breaks with multiple arguments that are too long.
=> Fix another case where trailing space that breaks rustfmt

fixtures/reexport-scaffolding-macro/Cargo.toml, uniffi/Cargo.toml, uniffi_testing/Cargo.toml
https://github.com/mozilla/uniffi-rs/pull/1357 didn't upgrade all of them.
=> Upgrade cargo_metadata to 0.15

docs/manual/src/proc_macro/index.md
Follow-up to #1392, cc @bendk @Hywan.
=> Add a warning and build workflow section to proc-macro documentation

docs/diplomat-and-macros.md, docs/manual/src/internals/rendering_foreign_bindings.md, uniffi_bindgen/src/backend/oracle.rs, uniffi_bindgen/src/backend/types.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/Helpers.py, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/ffi.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs
In accordance with the Rust API Guidelines: https://rust-lang.github.io/api-guidelines/naming.html
If you agree with this, I'm happy to update this PR to also change `FFIArgument`, `FFIFunction` and any others.
=> Change FFI to Ffi in type names

uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/lib.rs, uniffi_build/Cargo.toml
A less disruptive approach compared to #1416, same as https://github.com/eqrion/cbindgen/pull/363
=> Make clap optional in uniffi_bindgen

docs/release-process.md, release.toml, uniffi_testing/Cargo.toml
v0.22 removed some config options (as they are now the default or not needed)
=> Require later cargo-release

.circleci/config.yml
The new key is already added in Circle and in github's deploy keys. Old key is already invalidated
=> Rotates the Circle CI key used to deploy docs

fixtures/uitests/Cargo.toml, fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.rs, fixtures/uitests/tests/ui/interface_cannot_use_mut_self.rs, fixtures/uitests/tests/ui/interface_not_sync_and_send.rs, fixtures/uitests/tests/ui/non_hashable_record_key.rs, uniffi_core/Cargo.toml
This is the same as in uniffi_testing and thus avoids a dependency duplication.
=> Update to cargo_metadata 0.15

docs/manual/src/SUMMARY.md, docs/manual/src/kotlin/lifetimes.md
As noted in https://github.com/mozilla/application-services/pull/5326, it probably makes sense for us to document how our Kotlin wrappers use `AutoClosable`. This is very short and sweet, but that seems OK to me.
=> Add a small note to the manual about Kotlin lifetimes

.cargo/config.toml, .gitignore, CHANGELOG.md, docs/manual/src/tutorial/Prerequisites.md, docs/manual/src/tutorial/foreign_language_bindings.md, docs/release-process.md, release.toml, uniffi/Cargo.toml, uniffi/release.toml, uniffi/run-uniffi-bindgen.rs, uniffi_core/release.toml
- Added CHANGELOG sections to describe the new crate structure and breaking changes from PR #1374
- Updated the manual sections describing how to set up `uniffi-bindgen` binaries.  In particular, we're now suggesting naming the binaries `uniffi-bindgen` instead of `run-uniffi-bindgen`.  The "run" part seemed unnecessary to me, especially since `uniffi-bindgen` no longer provides a standalone binary.
My plan is to make a new UniFFI release once this is approved and merged.
=> CHANGELOG/documentation updates for 0.23

uniffi/Cargo.toml, uniffi/src/lib.rs
This allows consumers to avoid the clap dependency if they don't require the full CLI (with argument parsing).
Fixes #1416
=> Split out bindgen feature from full CLI

docs/manual/src/udl/ext_types_external.md, fixtures/ext-types/lib/src/ext-types-lib.udl, fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/uniffi-one/src/lib.rs, fixtures/ext-types/uniffi-one/src/uniffi-one.udl, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/python/templates/Types.py, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/types/finder.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs
I though #1444 might fix this, since it improves some of the `FfiConverter` name handling, but there was a bigger issue:  interfaces have fundamental differences compared to enums/records when it comes to moving them across the FFI since. Interfaces use `Arc<>` on the Rust side and `void *` on the FFI side.
Added way to flag that external types are interfaces, updated the code to handle these correctly.
This feels a little hacky to me, but I think this won't be needed once we move to proc-macros:
-   The proc-macros see the type names used in the function, so they can always figure out the correct `FfiConverter`
- Using the `FfiConverter`, they can always know the correct argument and return types.  ([example](https://github.com/mozilla/uniffi-rs/blob/670eb225ab1742af44ab93c3e378ecd2c64243 …
=> Make external types work with interfaces (#1435)

uniffi_bindgen/src/macro_metadata/extract.rs
=> Add more error context for proc-macro metadata extraction

fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi/src/lib.rs, uniffi/tests/ui/proc_macro_arc.stderr, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/lib.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
* Split out the proc-macro code to generate `FfiConverter` implementations and added standalone macros for that.
* Removed the `FfiConverter` implementations from the Askama template code.  Instead, the templates now invoke the macros.
* Removed the blanket `Arc<T>` impl from `uniffi_core` and made it so we invoke a macro for each interface.
The reason for this is:
* I want to add some more functionality to `FfiConverter`, but don't want to implement it twice and test it two different ways.
* Removing the blanket `Arc<T>` implementation allows us to customize the `FfiConverter` code for each interface.  I think this makes #1457 easier.
* Everything goes through one code path, which should give us some more confidence as we migrate to proc-macros.  This change caused me to fix some bugs …
=> Make the proc-macro FfiConverter impls canonical

uniffi_bindgen/src/scaffolding/templates/ReexportUniFFIScaffolding.rs, uniffi_bindgen/src/scaffolding/templates/RustBuffer.rs, uniffi_bindgen/src/scaffolding/templates/macros.rs
- https://github.com/mozilla/uniffi-rs/issues/1476
- The problem here is that rust scaffolding has to be directly included into the module where the implementation is defined or else is it wont compile. This means that a consumer's code cant have stricter clippy rules than the generated scaffolding.
- Theres not really a way to deal with this except to make the generated scaffolding pass all possible clippy rules
- I think this is fair because consumers of uniffi - I dont have control over the generated code so it should have no impact over their code formatting
- Add exceptions of fix all clippy errors that fired with 
```
cargo clippy -- --all-targets --all-features -- \
-D warnings \
-D clippy::all \
-D missing_docs \
-D clippy::missing_docs_in_private_items \
-D clippy::pedantic \
-W …
```
=> [CLIPPY] Update templates to allow generated scaffolding to pass pedantic clippy

fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.stderr, fixtures/uitests/tests/ui/interface_cannot_use_mut_self.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
About the first commit: I think down the line it makes sense to support `#[uniffi(tag = Tag)]` on fields to support pulling in an `FfiConverter` impl from another crate, but I don't think this is currently required anywhere, right?
=> Improve UniFFI tag handling in macros

fixtures/uniffi-fixture-time/Cargo.toml, fixtures/uniffi-fixture-time/src/chronological.udl, fixtures/uniffi-fixture-time/src/lib.rs
`to_string_timestamp` and `get_pre_epoch_timestamp` separate 2-way back and forth conversion process, making it possible to test 1-way conversion.
`to_string_timestamp` ensures that foreign language bindings lower the timestamp correctly, and that foreign language bindings interpret the timestamp the same way that Rust does.
`get_pre_epoch_timestamp` ensures that foreign language bindings lift the timestamp correctly, and that Rust interprets the timestamp the same way that foreign language bindings do.
=> Add additional functions to uniffi-fixture-time

fixtures/benchmarks/benches/benchmarks.rs, fixtures/benchmarks/src/cli.rs, uniffi_bindgen/src/bindings/kotlin/test.rs, uniffi_bindgen/src/bindings/mod.rs, uniffi_bindgen/src/bindings/python/test.rs, uniffi_bindgen/src/bindings/swift/test.rs
After this merged into main the performance tests failed because of a clap issue.  I'm really not sure why this was, I don't think we upgraded clap since I started the branch.  In any case, this fixes the issue.
Also, the `--compiler-messages` flag was not being honored.  Updated the code to use this by replacing `RunScriptMode` enum, with `RunScriptOptions`.  I think this makes more sense since we want the performance test mode to have options.  I also think this will be easier to extend going forward.
=> Fixes after the callback interface speedup merge

uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/Helpers.swift
Hello again. I have another one. This time I've encountered an issue that would lead to a Rust panic when interacting with callback interfaces in Swift code in a multi-threaded environment.
The generated output from the panic was
```
Bug: call set_callback multiple times. This is likely a uniffi bug<unnamed>' panicked at 'thread 'Bug: call set_callback multiple times. This is likely a uniffi bug
```
which originates from [here](https://github.com/mozilla/uniffi-rs/blob/e5b99ac2630e7f70e9ae89405ecfd2305e7ab276/uniffi_core/src/ffi/foreigncallbacks.rs#L198).
The issue was in this generated code
```swift
// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceClientDelegate {
// Initialize our callback method with the scaffolding code
private static var …
```
=> Fix race condition affecting callback interfaces in generated Swift code

uniffi_bindgen/src/scaffolding/templates/namespace_metadata.rs
Before this, including the scaffolding in a crate with `#[warn(missing_docs)]` generated an unnecessary warning.
=> Apply doc(hidden) attribute to public static UNIFFI_META_NAMESPACE_*

.circleci/config.yml
There's no latest, only version-tagged ones
=> CI: Use fully-qualified image name

Cargo.toml, fixtures/regressions/unary-result-alias/Cargo.toml, fixtures/regressions/unary-result-alias/README.md, fixtures/regressions/unary-result-alias/build.rs, fixtures/regressions/unary-result-alias/src/lib.rs, fixtures/regressions/unary-result-alias/src/unary-result-alias.udl, fixtures/regressions/unary-result-alias/tests/bindings/test.kts, fixtures/regressions/unary-result-alias/tests/bindings/test.py, fixtures/regressions/unary-result-alias/tests/bindings/test.swift, fixtures/regressions/unary-result-alias/tests/test_generated_bindings.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_core/src/lib.rs
PR #1469 introduced an incompatibility with a local `type Result<T> = std::result::Result<T, MyError>` type alias. As can be seen with the included test without the fix applied:
```
error[E0107]: this type alias takes 1 generic argument but 2 generic arguments were supplied
--> /mounted_workdir/target/debug/build/unary-result-alias-f408c03f1955dadd/out/unary-result-alias.uniffi.rs:79:1
|
79 | / #[::uniffi::ffi_converter_error(
80 | |     tag = crate::UniFfiTag,
81 | |     flat_error,
82 | |
83 | | )]
| |  ^
| |  |
| |__expected 1 generic argument
|    help: remove this generic argument
|
note: type alias defined here, with 1 generic parameter: `T`
--> fixtures/regressions/unary-result-alias/src/lib.rs:7:10
|
7  | pub type Result<T> = std::result::Result<T, MyError>;
|          ^^^^^^ -
= …
```
=> Fully qualify uses of `Result` in scaffolding/macro code

Cargo.toml, fixtures/swift-bridging-header-compile/Cargo.toml, fixtures/swift-bridging-header-compile/README.md, fixtures/swift-bridging-header-compile/build.rs, fixtures/swift-bridging-header-compile/src/lib.rs, fixtures/swift-bridging-header-compile/src/swift-bridging-header-compile.udl, fixtures/swift-bridging-header-compile/tests/clang.rs, uniffi_bindgen/src/bindings/swift/templates/macros.swift
Compiling my swift project I am seeing:
```
Generated/mycrateFFI.h:75:45: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
```
for the `ffi_mycrate_uniffi_contract_version` and
`uniffi_mycrate_checksum_func_myfun` declarations.
This is because they take no arguments which is emitted as `()`, for C `(void)` is required, C++ is happy with either.
Add a specific case to `swift::arg_list_ffi_decl` to handle this. The resulting diff is:
```
--- mycrateFFI.h	2023-04-06 10:38:25.645130502 +0100
+++ mycrateFFI.h	2023-04-06 11:01:12.415958817 +0100
@@ -73,9 +73,11 @@ RustBuffer ffi_mycrate_rustbuffer_reserv
);
uint32_t ffi_mycrate_uniffi_contract_version(
+    void
);
uint16_t uniffi_mycrate_checksum_func_myfun(
+    void
);
```
---
=> Ensure bridging header function prototypes are valid

uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs
=> Fix typo in swift support

docs/manual/src/proc_macro/index.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_macros/src/export/scaffolding.rs
=> Fix proc-macro constructor support and document it

fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.swift, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs
The newly added test previously failed with:
```
/mounted_workdir/target/tmp/uniffi-fixture-futures-33456a6570cdb80a/uniffi_futures.swift:1024:62: error: '>' is not a postfix unary operator
let polledResult = UnsafeMutablePointer<void*_Nonnull>.allocate(capacity: 1)
^
/mounted_workdir/target/tmp/uniffi-fixture-futures-33456a6570cdb80a/uniffi_futures.swift:1024:54: error: cannot find '_Nonnull' in scope
let polledResult = UnsafeMutablePointer<void*_Nonnull>.allocate(capacity: 1)
^~~~~~~~
test uniffi_foreign_language_testcase_test_futures_swift ... FAILED
```
Fixes: #1505 /cc @Hywan @conanoc.
=> swift: Correct lowered type for returning an `Arc<_>`.

fixtures/proc-macro/src/lib.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/macro_metadata/ci.rs
Fixes #1527
The other alternative is to lean into the fact it's unused meaning we optimize the object out entirely, but I'm not sure that's wise.
=> Ensure unused `#[derive(uniffi::Object)]`'s don't break things

uniffi_bindgen/src/interface/mod.rs
Oops, a conflict that didn't actually conflict means main is broken - this fixes it.
=> Fix breakage from conflict introduced with trait support

fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.kts, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt
The newly added test case previously failed with:
```
target/tmp/uniffi-fixture-futures-a3d73500fcde9679/uniffi/fixture/futures/uniffi_futures.kt:1638:63: error: type mismatch: inferred type is RustFutureWakerEnvironment<Megaphone?> but RustFutureWakerEnvironment<out Any> was expected
_UniFFILib.FUTURE_WAKER_ENVIRONMENTS.put(envHash, env)
^
test uniffi_foreign_language_testcase_test_futures_kts ... FAILED
```
=> Support returning an `Option<Object>` from an async function

fixtures/callbacks/src/callbacks.udl, fixtures/callbacks/src/lib.rs, fixtures/callbacks/tests/bindings/test_callbacks.kts, fixtures/callbacks/tests/bindings/test_callbacks.py, fixtures/callbacks/tests/bindings/test_callbacks.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_core/src/ffi/foreigncallbacks.rs, uniffi_core/src/ffi/rustfuture.rs, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/lib.rs
Refactoring the callback interface return code
Added a `FfiConverter` method to handle returning values from callback interface methods.  This removes the need for multiple `invoke_callback_*` methods and fixes #1547.
Removed the swift code that wrote an string to the RustBuffer for flat errors.  No other bindings do that and we just ignored it on the Rust side.
Implemented the lift/lower/read/write for the unit struct.  We now call these methods in the callback interface code.
=> Callback interface returns

Cargo.toml, fixtures/type-limits/Cargo.toml, fixtures/type-limits/README.md, fixtures/type-limits/build.rs, fixtures/type-limits/src/lib.rs, fixtures/type-limits/src/type-limits.udl, fixtures/type-limits/tests/bindings/test_type_limits.py, fixtures/type-limits/tests/test_generated_bindings.rs, fixtures/type-limits/uniffi.toml, uniffi_bindgen/src/bindings/python/templates/Int16Helper.py, uniffi_bindgen/src/bindings/python/templates/Int32Helper.py, uniffi_bindgen/src/bindings/python/templates/Int64Helper.py, uniffi_bindgen/src/bindings/python/templates/Int8Helper.py, uniffi_bindgen/src/bindings/python/templates/RustBufferHelper.py, uniffi_bindgen/src/bindings/python/templates/UInt16Helper.py, uniffi_bindgen/src/bindings/python/templates/UInt32Helper.py, uniffi_bindgen/src/bindings/python/templates/UInt64Helper.py, uniffi_bindgen/src/bindings/python/templates/UInt8Helper.py
Not spelling out the numbers as numbers is fine, CPython optimizes it out:
```py
>>> import dis
>>> dis.dis("not -2**63 <= value < 2**63")
0           0 RESUME                   0
1           2 LOAD_CONST               0 (-9223372036854775808)
4 LOAD_NAME                0 (value)
6 SWAP                     2
8 COPY                     2
10 COMPARE_OP               1 (<=)
16 JUMP_IF_FALSE_OR_POP     5 (to 28)
18 LOAD_CONST               1 (9223372036854775808)
20 COMPARE_OP               0 (<)
26 JUMP_FORWARD             2 (to 32)
>>   28 SWAP                     2
30 POP_TOP
>>   32 UNARY_NOT
34 RETURN_VALUE
```
The exception thrown imitates the one of the `struct` module:
```py
>>> import struct
>>> struct.pack("<I", 2**32)
Traceback (most recent call last):
File "<stdin>", line 1, in …
```
=> Check for integer overflows in Python bindings

uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt
Without this a user could pass a null value, which isn't correct. This prevents compiler errors when I try to use the new UniFFI version with application-services.
=> Kotlin: Add an upper-bound for UniFfiHandleMap

uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_bindgen/src/bindings/python/templates/RustBufferTemplate.py
That's an artifact from Python 2, Python 3 does that automatically.
=> Don't explicitly derive from `object` in Python

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.rb, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/python/templates/ErrorTemplate.py
Fixes #1555.
Before:
```
>>> libtw2_huffman.decompress(b"")
Traceback (most recent call last):
[…]
libtw2_huffman.UniFFIExceptionTmpNamespace.InvalidInput: DecompressionError.InvalidInput('input is not a valid huffman compression')
```
After:
```
>>> libtw2_huffman.decompress(b"")
Traceback (most recent call last):
[…]
libtw2_huffman.DecompressionError.InvalidInput: input is not a valid huffman compression
```
=> Improve error outputs for Python code

CHANGELOG.md, Cargo.toml, docs/manual/src/udl/interfaces.md, fixtures/trait-methods/Cargo.toml, fixtures/trait-methods/build.rs, fixtures/trait-methods/src/lib.rs, fixtures/trait-methods/src/trait_methods.udl, fixtures/trait-methods/tests/bindings/test.py, fixtures/trait-methods/tests/test_generated_bindings.rs, fixtures/uitests/src/trait_methods_unknown_trait.udl, fixtures/uitests/tests/ui/trait_methods_no_trait.rs, fixtures/uitests/tests/ui/trait_methods_no_trait.stderr, fixtures/uitests/tests/ui/trait_methods_unknown_trait.rs, fixtures/uitests/tests/ui/trait_methods_unknown_trait.stderr, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_bindgen/src/bindings/python/templates/macros.py, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/macros.rs, uniffi_macros/src/lib.rs
This is a POC for supporting "magic" methods in foreign bindings. In the included test, we show Python generating `__repr__`, `__str__`, `__eq__` and `__hash__` for a uniffi exposed object, each with the correct semantics. I haven't implemented any languages other than Python, but hopefully it's clear how Kotlin might work as requested in #1286.
It's a bit hacky, bit it turned out better than I was expecting.
* The "trait names" are just strings, which we assume are among a "well known" set and currently match Rust trait names (eg, `Display`, `PartialEq`, etc). 
* In all cases, we generate "custom" ffi signatures in the rust crate, and these signatures are assumed to be known by the bindings - ie, there's no way to communicate that the ffi hash function has a signature of …
=> Implement magic "trait methods"

docs/manual/src/proc_macro/index.md, fixtures/metadata/src/tests.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/error.rs, uniffi_bindgen/src/interface/literal.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_core/src/metadata.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/record.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/reader.rs
=> Add support for field defaults to proc-macro frontend

CHANGELOG.md, uniffi_macros/src/util.rs
These are some small changes related to a couple PRs:
I was hoping to implement the system described in  https://github.com/mozilla/uniffi-rs/issues/1531, but I realized that
wouldn't be easy for UDL files.  Currently, any `record` or `enum`  defined in a UDL file can be a remote type and there's no distiction  made between the two.  I don't want to put in the work to change that, so I just tried to document things and explain the differences.
I realized that we introduced a couple breaking changes in corner cases with external types and documented them:
- We discussed this some in https://github.com/mozilla/uniffi-rs/pull/1516#discussion_r1198960326, but I realize that the `ExternalTypes.rs` template also uses the external type crate name.  So I decided that it does deserve a line in the …
=> Adding some documentation for external types

uniffi_bindgen/Cargo.toml
This accompanies #1495 in upgrading so we transitively depend less on syn v1, and more on syn v2.
The 2 PRs are independent, but need to be both in the next release to land on m-c.
=> Upgrade to askama v0.12

CHANGELOG.md, fixtures/type-limits/src/lib.rs, fixtures/type-limits/src/type-limits.udl, fixtures/type-limits/tests/bindings/test_type_limits.py, uniffi_bindgen/src/backend/types.rs, uniffi_bindgen/src/bindings/python/gen_python/callback_interface.rs, uniffi_bindgen/src/bindings/python/gen_python/compounds.rs, uniffi_bindgen/src/bindings/python/gen_python/custom.rs, uniffi_bindgen/src/bindings/python/gen_python/enum_.rs, uniffi_bindgen/src/bindings/python/gen_python/error.rs, uniffi_bindgen/src/bindings/python/gen_python/executor.rs, uniffi_bindgen/src/bindings/python/gen_python/external.rs, uniffi_bindgen/src/bindings/python/gen_python/miscellany.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/object.rs, uniffi_bindgen/src/bindings/python/gen_python/primitives.rs, uniffi_bindgen/src/bindings/python/gen_python/record.rs, uniffi_bindgen/src/bindings/python/templates/BooleanHelper.py, uniffi_bindgen/src/bindings/python/templates/Float32Helper.py, uniffi_bindgen/src/bindings/python/templates/Float64Helper.py, uniffi_bindgen/src/bindings/python/templates/Int16Helper.py, uniffi_bindgen/src/bindings/python/templates/Int32Helper.py, uniffi_bindgen/src/bindings/python/templates/Int64Helper.py, uniffi_bindgen/src/bindings/python/templates/Int8Helper.py, uniffi_bindgen/src/bindings/python/templates/RustBufferHelper.py, uniffi_bindgen/src/bindings/python/templates/UInt16Helper.py, uniffi_bindgen/src/bindings/python/templates/UInt32Helper.py, uniffi_bindgen/src/bindings/python/templates/UInt64Helper.py, uniffi_bindgen/src/bindings/python/templates/UInt8Helper.py, uniffi_bindgen/src/bindings/python/templates/macros.py
The error messages mirror the ones used in Python itself. E.g.:
```python
>>> chr(1.0)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
>>> class A:
...     def __index__(self):
...             return 1.0
...
>>> chr(A())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: __index__ returned non-int (type float)
```
and
```python
>>> math.sqrt("1")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: must be real number, not str
>>> class A:
...     def __float__(self):
...             return "1"
...
>>> math.sqrt(A())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: A.__float__ returned non-float (type str)
``` …
=> Stricter type checking for Python integers and floats

fixtures/futures/tests/bindings/test_futures.py
I can't reproduce the kotlin failure we sometimes see on CI, but Python regularly fails for me. The test seems to assume that sleeping for X ms means we will wake up almost exactly after X ms, which isn't really how things work. There are still a couple of questionable tests left IMO, but didn't want to go *too* far - LMK if you think I should just kill the ones I flagged as being suspect too, or we can just wait and kill them if they remain intermittent on CI?
=> Fix intermittent failures in the futures Python fixture

examples/custom-types/uniffi.toml
Somehow I've ended up with java 20 or something, and this example is failing due to deprecated use of the url constructor. Hopefully this new way works with the older versions.
=> Fix custom type demo usage of deprecated URL constructor in kotlin

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, uniffi_bindgen/src/interface/enum_.rs, uniffi_macros/src/error.rs
The `is_flat` semantics for enums and errors was confusing me (mainly because that's entirely the wrong term which should be used), so I tried to capture the semantics and expand some comments on it.
It mainly adds additional coverall tests for enums and error, and adds matching enum and error definitions via proc_macros, and ensures the semantics are the same.
=> Clarify the semantics of Enums and Errors

docs/manual/src/udl/callback_interfaces.md
When working on proc-macros I thought about this and I'm pretty sure it's an issue.  Am I missing something here or is this something we should have been warning about from the start?
=> Added warning about Send + Sync and callback interfaces

fixtures/type-limits/tests/bindings/test_type_limits.rb, fixtures/type-limits/tests/test_generated_bindings.rs, fixtures/type-limits/uniffi.toml, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/Helpers.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb, uniffi_bindgen/src/bindings/ruby/templates/macros.rb, uniffi_bindgen/src/bindings/ruby/templates/wrapper.rb
The exception thrown is [`RangeError`](https://docs.ruby-lang.org/en/master/RangeError.html), like e.g. when doing `256.chr`.
```
> 256.chr
(irb):1:in `chr': 256 out of char range (RangeError)
from (irb):1:in `<main>'
from /usr/lib/ruby/gems/3.0.0/gems/irb-1.4.2/exe/irb:11:in `<top (required)>'
from /usr/bin/irb:25:in `load'
from /usr/bin/irb:25:in `<main>'
```
=> Check for integer overflows in Ruby bindings

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt, uniffi_bindgen/src/bindings/kotlin/templates/CustomTypeTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/BridgingHeaderTemplate.h, uniffi_bindgen/src/interface/ffi.rs, uniffi_bindgen/src/interface/types/mod.rs
This exists in `uniffi_bindgen::interface` but is only used internally by kotlin and swift - it's not used by the rest of `uniffi_bingen` or any other bindings.
It creates a complicated relationship between the bindings and the core, so it's better the complications live purely inside the bindings that need it.
=> Remove `FfiType::canonical_name()`

CHANGELOG.md
These are the commits likely to cause the most pain for bindings authors.
=> Changelog notes for binding authors

fixtures/type-limits/src/lib.rs, fixtures/type-limits/src/type-limits.udl, fixtures/type-limits/tests/bindings/test_type_limits.py, fixtures/type-limits/tests/bindings/test_type_limits.rb, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/Helpers.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb
This would be UB on the Rust side. Add some tests verifying that this is caught in both Ruby and Python.
=> Don't pass non-UTF-8 bytes as string from Ruby to Rust

fixtures/type-limits/tests/bindings/test_type_limits.py, fixtures/type-limits/tests/bindings/test_type_limits.rb, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/Helpers.rb
There are implicit integer conversions using `to_int` and no conversions for floats. This is correct according to
https://idiosyncratic-ruby.com/54-try-converting.html and Ruby's Discord https://discord.com/channels/518658712081268738/788748516352458752/1118618993276760105.
=> Be more picky about int/float arguments in Ruby

fixtures/trait-methods/tests/bindings/test.py, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py
`NotImplemented` is what these methods should return, see https://docs.python.org/3/library/constants.html#NotImplemented The interpreter is then responsible for doing the right thing.
Unfortunately this means "manually" implementing these methods in the template instead of relying on the convenient macros.
=> Python: For eq/ne handle types differing from the one we're implementing

CHANGELOG.md
We might be missing some docs here and there, though that we can do in followups without blocking the release.
=> Update changelog with notable changes since the last release

docs/release-process.md, release.toml
That file was ultimately not added in #1445.
We keep only a single changelog, listing all changes.
=> Release process: Remove step to touch uniffi/CHANGELOG.md

uniffi_bindgen/src/bindings/python/templates/wrapper.py
Also this broke Python 3.6 compatibility
=> Python: Remove unused import

fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.kts, fixtures/futures/tests/bindings/test_futures.py, fixtures/futures/tests/bindings/test_futures.swift, uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt
Seems like it probably fixes #1611 but I'm really not sure what I am doing :) cc @Hywan, does this look OK to you?
=> Fix Kotlin error handling in async functions

uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py
Otherwise we might call it with the wrong ABI.
This so far wasn't an issue on platforms UniFFI tests on, but can be observed on Windows (at leats in Wine), where suddenly the checksums won't match, e.g.
39784 is expected, but the call gets 33135464 back. The former is 0x9b68 and fits well within a 16-bit unsigned integer. The latter is 0x1f99b68 which does not fit (but it has the same suffix, guess why...)
=> Delay contract checks until after all functions are defined

CHANGELOG.md
Updating the gecko-js bindings made me realize this was another breaking change for external bindings authors.
=> Adding a CHANGELOG entry for the callback interface ABI change

docs/manual/src/SUMMARY.md, docs/manual/src/proc_macro/index.md
I think it's safe to say procmacros are no longer "experimental" but are here to stay, so I've tried to soften that language. @jplatte , WDTY?
=> Update proc-macro docs to note they are no longer experimental

fixtures/proc-macro/src/callback_interface.rs, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_bindgen/src/interface/mod.rs
Using `#[uniffi::export(callback_interface)]` on a trait which has methods taking `Option<T>` arguments currently fails because `FfiConverterOptional$T` is not defined in the generated Kotlin code (at least).
Here a failing test is added to the `proc-macro` fixtures and then fixed by registering the types in the CB related path of `ComponentInterface::add_trait_method_meta`.
I did try just making it call `ComponentInterface::add_method_meta` but this hit the "object ... not found" assertion in there. Perhaps I should have done a deeper refactoring to also allow more consolidation?
@bendk you recently consolidated some code in ba28e9d50cef1ed857599e939e39782eddc7365b which I think is related, although by inspection I think the issue was already present before that.
=> Callback interface via export missing method argument types

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/simple-iface/build.rs, fixtures/simple-iface/src/lib.rs, fixtures/simple-iface/src/simple-iface.udl, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/scaffolding_template.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/setup_scaffolding.rs, uniffi_meta/src/lib.rs
- Added a `setup_scaffolding` proc-macro.  This does things like generate `crate::UniffiTag` and export the rustbuffer scaffolding functions.
- Updated the Askama scaffolding template to call `setup_scaffolding!()`
- Removed the scaffolding check that `uniffi_bindgen` and `uniffi` have the same version.  I don't think this is needed anymore now that users only depend on `uniffi` and get their `uniffi_bindgen` dependency transitively.  Note: we still need a similar check in the bindings, but this commit only changes the scaffolding generation.
- Updated `fixtures/simple-iface` to test the new system
- Updated docs
=> Allows crates to use only proc-macros and not UDL

uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
The `generate_external_bindings` is the main function used by all external binding generators to generate bindings for their appropriate language. After the recent updates with proc-macros, UniFFI allowed for type definitions to be extracted from dynamic libraries. This was reflected in `generate_bindings` but not in `generate_external_bindings`. 
This PR extends the support for extraction of definitions from dynamic libraries to external generators by aligning the interface and implementation of `generate_bindings` and `generate_external_bindings`.
=> Allow external generators to extract definitions from dynamic libraries.

fixtures/futures/src/lib.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/scaffolding.rs
This allows
```rust
#[uniffi::export(async_runtime = "tokio")]
impl Foo {
fn just_a_regular_fn(&self) { /* ... */ }
async fn my_async_fn(&self) { /* run within the context of a tokio runtime */ }
}
```
which used to complain that "this attribute is only allowed on async functions" (pointing to the `"tokio"` string).
=> Improve async-related sanity checks in scaffolding generation

docs/manual/src/udl/interfaces.md
The introduction to interfaces is wrong - it uses `&mut self` in a place where it can't be used.
=> Fix documentation so it doesn't use an invalid `&mut self`

docs/manual/src/internals/lifting_and_lowering.md, docs/manual/src/udl/builtin_types.md, examples/rondpoint/src/rondpoint.udl, fixtures/regressions/fully-qualified-types/src/test.udl, uniffi_udl/src/resolver.rs
Someone mentioned the `DOMString` references in the docs confused them, and I'm not surprised!
=> Remove almost all references to `DOMString`

uniffi_meta/Cargo.toml, uniffi_meta/src/lib.rs, uniffi_meta/src/metadata.rs, uniffi_meta/src/reader.rs
In m-c we're running into linking issues in `uniffi_macros`, where it's missing symbols coming from `uniffi_core`:
/bin/ld: uniffi_foreign_executor_callback_set: undefined version:
/bin/ld: failed to set dynamic section sizes: bad value
That's most likely this issue on Rust:
https://github.com/rust-lang/rust/issues/111888
It's called out that this likely actually broke because of another PR: https://github.com/rust-lang/rust/pull/99944
Despite this bug there's a bit of an issue in UniFFI to begin with: We're exporting `extern "C"` functions from a crate that is a dependency of some other crates, including `uniffi_macros`, and thus the symbols land in a part where they are not needed.
However for `uniffi_meta` in particular we don't need much from `uniffi_core`, so for now we just copy the …
=> Hack: Copy metadata module to avoid uniffi_core dependency

fixtures/ext-types/guid/src/lib.rs, fixtures/ext-types/proc-macro-lib/src/lib.rs, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.py, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.swift, uniffi_bindgen/src/bindings/swift/templates/CustomType.swift
If a Custom Type doesn't have a custom foreign type (as specified in uniffi.toml), Swift fails to export the custom type meaning it can't be used externally.
In this example, Swift is treating the `Guid` as a plain string, which didn't export the public FFI functions.
=> Fix export of Swift custom types which don't have a foreign type

CHANGELOG.md, uniffi_macros/src/lib.rs, uniffi_macros/src/util.rs
It's another "hack" but needed to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1846223 for now
=> Bug 1846223 - uniffi_macros: Force-include the `Cargo.toml` to read

uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_bindgen/src/bindings/python/templates/RecordTemplate.py, uniffi_bindgen/src/bindings/python/templates/TopLevelFunctionTemplate.py
I'm beginning to make use of the generated Python bindings for a few of the things that I am building and have noticed that the generated bindings are missing type hints in some areas:
1. Instance variables on classes (UniFFI records, not objects) and their associated `__init__` method.
2. Instance variables on non-flat enum variants and their associated `__init__` method.
3. In the returns of top-level functions.
For the first two points, this PR adds type hints to classes in accordance to PEP-526's section on "[Class and instance variable annotations](https://peps.python.org/pep-0526/#class-and-instance-variable-annotations)" where the type hints are added as seen below:
```py
class Human:
name: "str"
age: "int"
country: "Country"
def __init__(self, name: "str", age: "int", country: …
```
=> Python: Type Hints for class instance variables & other type hints

uniffi_bindgen/src/library_mode.rs
This makes library mode work when the dependent crate doesn't include "lib" in their `crate-type` list.  I think that check was leftover from older code and isn't needed anymore.
=> Allow different crate types when using library mode

CHANGELOG.md, fixtures/futures/tests/bindings/test_futures.kts, uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt
When we execute a future on Kotlin, we create a `jni.Callback` instance that Rust calls when the Future is ready.  We need to hold a reference to that object or else the JVM will finalize it and when Rust tries to invoke the callback bad things will happen. In the unit tests this causes them to stall because the Kotlin coroutine continutation is never completed.
The `callbackHolder` variable was intended to hold a reference, but it doesn't seem to be working (see [arg0d's analysis](https://github.com/mozilla/uniffi-rs/pull/1677#issuecomment-1660663156)). I belive the issue is that variable isn't actually used anywhere so Kotlin frees it before the coroutine has completed and the reason #1684 fixes the issue is that it uses the variable in the completion handler …
=> Fix Kotlin callback handler reference handling

docs/manual/src/proc_macro/index.md, fixtures/ext-types/proc-macro-lib/src/lib.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_macros/src/lib.rs
I forgot to re-push before landing that PR. I think the new names are better and I'd like to get this in before contributors start playing with it.
=> Followup to #1680, update macro names for custom type macros.

fixtures/ext-types/proc-macro-lib/src/lib.rs, uniffi_macros/src/custom.rs
After moving `NewtypeHandle` in the fixture to a submodule I got:
error[E0433]: failed to resolve: use of undeclared type `UniffiCustomTypeConverter`
--> fixtures/ext-types/proc-macro-lib/src/lib.rs:168:5
|
168 |     uniffi::custom_newtype!(NewtypeHandle, i64);
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type `UniffiCustomTypeConverter`
|
= note: this error originates in the macro `uniffi::custom_newtype` (in Nightly builds, run with -Z macro-backtrace for more info)
Giving the full path to the type defined in the scaffolding resolves this.
---
/cc @mhammond as mentioned in https://github.com/mozilla/uniffi-rs/issues/1639#issuecomment-1669784472
Fixes: #1639
=> Allow use of `uniffi::custom_newtype!` from non-root modules

uniffi_bindgen/src/bindings/swift/templates/DataHelper.swift
```
uniffi-fixture-coverall-af68e6307d32e36f/coverall.swift:490:16: warning: 'init(bytes:)' is deprecated: replaced by 'init(_:)'
return Data(bytes: try readBytes(&buf, count: Int(len)))
^
uniffi-fixture-coverall-af68e6307d32e36f/coverall.swift:490:16: note: use 'init(_:)' instead
return Data(bytes: try readBytes(&buf, count: Int(len)))
^    ~~~~~~~
```
According to the docs for the [deprecated][] method and the [replacement][] method the replacement is available in all the same versions as the deprecated function, so there should be no risk in removing.
AFAICT the deprecation was in 2018/19 timeframe.
[deprecated]: https://developer.apple.com/documentation/foundation/data/3020550-init
[replacement]: https://developer.apple.com/documentation/foundation/data/2852972-init
=> swift: Move away from deprecated `Data` constructor

uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
Determined from https://docs.swift.org/swift-book/documentation/the-swift-programming-language/lexicalstructure/#Keywords-and-Punctuation
Previously lots of warning were generated of the form:
```
/tmp/target/tmp/uniffi-example-custom-types-2b18f735d09116c0/custom_types.swift:427:13: warning: keyword 'url' does not need to be escaped in argument list
`url`: FfiConverterTypeUrl.read(from: &buf),
^   ~
```
When compiling generated Swift code.
Swift appears to be fairly tollerant of keyswords in some contexts, in particular:
* only a small subset of keywords need to be quoted when a name is used as an argument label when calling a function.
* enum variant names do not need to be quoted when they are used, only when they are defined.
Fixes: #1460
---
TBH I'm a bit worried about this PR re the …
=> swift: Only quote keywords in contexts where that is required

uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift
```
uniffi-fixture-callbacks-129de7ccace1172c/fixture_callbacks.swift:1067:26: warning: no calls to throwing functions occur within 'try' expression
let result = try swiftCallbackInterface.fromSimpleType(
^
```
NB: the `swift::try` macro is concerned with the containing function calling subfunctions (it expands to `try` or `try!`) which is not what is needed here, we care about whether the subfunction being called throws.
=> swift: Avoid generating `try` on function calls which do not throw

README.md
I built a little cargo plugin, that helps with packaging a UniFFI project as Swift Package. The motivation behind this is to allow using Rust code in iOS and macOS apps without requiring additional build scripts or configuration. Building a Swift Package seems to be a good solution for this, since the Swift Package Manager is well integrated into XCode.
Additionally, this enables to distribute Rust + UniFFI crates as Swift Packages for use by other people unfamiliar with Rust or UniFFI.
I would appreciate it if my plugin would be listed in the README.
=> swift: Add cargo swift to "External resources" section

CHANGELOG.md, docs/uniffi-versioning.md, fixtures/futures/Cargo.toml, fixtures/futures/build.rs, fixtures/futures/examples/kotlin/Makefile, fixtures/futures/examples/python/Makefile, fixtures/futures/examples/swift/Makefile, fixtures/futures/src/futures.udl, fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.kts, fixtures/futures/tests/bindings/test_futures.py, fixtures/futures/tests/bindings/test_futures.swift, uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt, uniffi_bindgen/src/bindings/kotlin/templates/ForeignExecutorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/python/templates/ForeignExecutorTemplate.py, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py, uniffi_bindgen/src/bindings/swift/templates/BridgingHeaderTemplate.h, uniffi_bindgen/src/bindings/swift/templates/ForeignExecutorTemplate.swift, uniffi_core/src/ffi/foreignexecutor.rs, uniffi_core/src/ffi/rustbuffer.rs, uniffi_core/src/ffi/rustfuture.rs, uniffi_meta/src/lib.rs
This adds better support for cancelling Futures (#1669).  The basic issue is that our Rust code leaks an Arc/Box when scheduling calls, expecting to reverse that leakage when the scheduled call is invoked.  However if the foreign executer is cancelled, then the scheduled call is never invoked and the Rust Future is leaked in the middle of the operation.  If that Future is holding on to some shared resource like a Mutex then deadlocks will start happening.
Now, the foreign language code now informs Rust that a scheduled call has been cancelled and the Rust code drops the Arc/Box.
When implementing this I noticed some more issues with our basic async system:
- Swift uses a new `Task` to schedule calls, which means that we give up on structured concurrency.  Cancelling the top-level task …
=> Avoid memory leaks with async cancellation

fixtures/keywords/swift/src/keywords.udl, fixtures/keywords/swift/src/lib.rs, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift
This fixes the issue I've spotted in #1713, by adding quotes until the generated swift bindings compile.
=> swift: add quotes as required for enum variants (fixes #1713)

Cargo.lock
I could have sworn I updated the new Cargo.lock, but apparently not!
=> Fixup Cargo.lock to reflect changes in how serde is used

Cargo.lock, uniffi_core/Cargo.toml, uniffi_core/src/ffi/callbackinterface.rs, uniffi_core/src/ffi/foreigncallbacks.rs, uniffi_core/src/ffi/foreignexecutor.rs, uniffi_core/src/ffi/mod.rs
This PR contains a variety of code cleanups related to the async and callback interface code.  This is prep work for a couple of improvements I hope to make in the near future.
I think the only change that might be controversial is the first commit that adds the `oneshot` dependency.  Here's my justification from the commit message:
> `oneshot` seems like a reasonable dependency to add.  It's small,
fairly popular, and replaces a lot of messy code.
>
> I doubt the performance matters, but FWIW I think it should perform much
better than my naive mutex-based implementation for sending/receiving
the value.  We do lose one optimization: `RunFuture` stored the closure
alongside the rest of the future internals which meant one less heap
allocation.  However, even that optimization comes at the …
=> Async cleanups

uniffi_bindgen/src/bindings/kotlin/templates/ForeignExecutorTemplate.kt, uniffi_bindgen/src/bindings/python/templates/ForeignExecutorTemplate.py, uniffi_bindgen/src/bindings/swift/templates/ForeignExecutorTemplate.swift, uniffi_bindgen/src/interface/mod.rs, uniffi_core/Cargo.toml, uniffi_core/src/ffi/foreignexecutor.rs, uniffi_core/src/ffi/rustbuffer.rs, uniffi_macros/src/setup_scaffolding.rs
Not mangling these functions cause duplicate symbol errors when
attempting to link 2 static libraries containing different uniffi
versions. The error also appears when linking 2 static libraries
containing the same uniffi version, but when the libraries are
compiled on different architecture machies, e.g. MacOS Intel and MacOS
Arm.
These Rust buffer functions are already exposed with a namespace prefix
in RustBuffer.
---
This is the alternative to #1718 that should help us land this in m-c as well (I still need to test this).
=> Mangle rustbuffer & foreign_executor_callback_set functions

uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt
This check should be outside of `rustCall()` to handle panics correctly. If `ci.ffi_rustbuffer_alloc` fails, then it's expected for the `RustBuffer.data` field to be null.
Moved the check outside of the `rustCall()` call to avoid running it if the Rust function panics.
=> Move the RustBuffer.alloc() check

fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, fixtures/uitests/tests/ui/interface_trait_not_sync_and_send.stderr, uniffi_core/src/ffi_converter_traits.rs
Without this, it is possible to send types that contain non-threadsafe constructs like `RefCell` over FFI, and call methods that use them from multiple threads.
Both Send and Sync are required on the inner type for Arc to implement Send itself, which is what we must guarantee to be able to move an Arc over FFI, since we can't guarantee it is kept on the same thread inside the calling code.
=> Require Send + Sync for object types

docs/manual/src/kotlin/gradle.md
Only a doc change, no tests needed. I noticed this dependency while setting up a nix flake to run my own tests generated using your macros.
=> Add note about coroutines dependency

fixtures/metadata/src/tests.rs, fixtures/proc-macro/src/callback_interface.rs, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_meta/src/reader.rs
Based on the discussion in #1638, I'm not sure what the overall consensus there was (we got a little sidetracked by the concept of a default) but this is the very simplest thing which happens to satisfy my use-case in the hopes of making things a little more concrete.
Based on the discussion I think these are the other possibilities which were in the mix, in increasing order of (what I think is the) complexity
1. Plumb through the selection to a global option in `uniffii.toml` affecting all languages (conceptually simple but there's a lot of layers to plumb through to get to `MetadataReader::new()` and pass in the choice I think).
2. Plumb through the selection to a per-language option in `uniffii.toml` (not much different to 1 in terms of complexity I think?)
3. Add a …
=> Render `Vec<u8>` via proc macros as `bytes` not `sequence<u8>`.

uniffi_bindgen/src/interface/enum_.rs, uniffi_udl/src/converters/mod.rs
This seems reasonable to me because if you're handling an `Enum` you're treating these special names as identifiers. At the same time it feels very hacky, and I couldn't tell where further up the chain was causing `Error` to be treated specially here. I tried testing with other `NonAnyTypes` like `Promise` and they end up in the same code as `Identifier` correctly.
=> Catch special case of `Error` enum variant

uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt
Since associated functions are unsupported as of now, an alternative to associated functions would be using (prefixed) global functions instead. A developer could then utilize the generated, global functions and wrap them within target-language specific type-associated extension functions.
While it's possible without any further ado to simply extend Protocols, Classes & Structs in Swift even with associated functions and generated properties, any Kotlin type is required to provide a companion object in order to mimic or enable such extensions (there's no static or associated in Kotlin, hence a companion object is required).
Kotlin does not provide a capibility to attach a companion object from anywhere but the types's declaration itself.
This PR therefore attaches a `companion object` to …
=> Provide Kotlin companion objects for generated types

uniffi_bindgen/src/bindings/kotlin/templates/MapTemplate.kt
there was todo to use buildMap, it is stable since Kotlin 1.6
implemented todo
note - I was not able to run tests from doker image with 
```
error: failed to open: /mounted_workdir/target/debug/.cargo-lock
Caused by:
Permission denied (os error 13)
```
But I hope they will run in PR flow now.
=> implemented buildMap todo for kotlin

docs/manual/src/proc_macro/index.md
This pull request fixes a minor bug in the proc-macro documentation's [custom type macro section](https://mozilla.github.io/uniffi-rs/proc_macro/index.html#the-unifficustom_type-and-unifficustom_newtype-macros).
The current example code for the custom_type macro uses url::Url as "custom type" in the macro, even though the rest of the code features a custom Uuid type. As I understand the example, it is intended to use the Uuid type as "custom type" here.
=> Fix (possibly) inconsistent example code in proc-macro docs

docs/manual/src/udl/ext_types_external.md, fixtures/ext-types/lib/src/ext-types-lib.udl, fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/lib/tests/bindings/test_imported_types.py, fixtures/ext-types/lib/tests/bindings/test_imported_types.swift, fixtures/ext-types/proc-macro-lib/build.rs, fixtures/ext-types/proc-macro-lib/src/ext-types-lib.udl, fixtures/ext-types/proc-macro-lib/src/lib.rs, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.py, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.swift, fixtures/ext-types/uniffi-one/Cargo.toml, fixtures/ext-types/uniffi-one/src/lib.rs, fixtures/ext-types/uniffi-one/src/uniffi-one.udl, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ExternalTypeTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/python/templates/ExternalTemplate.py, uniffi_bindgen/src/bindings/python/templates/Types.py, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/library_mode.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_checksum_derive/src/lib.rs, uniffi_meta/src/group.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/types.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/finder.rs
This improves coverage and functionality sharing external types between crates and between UDL and proc-macro implementations.
=> Fix external types namespace/crate_name confusion.

docs/manual/src/udl/builtin_types.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.py, uniffi_core/src/ffi_converter_impls.rs
[Non-string keys already have tests](https://github.com/mozilla/uniffi-rs/blob/7acfce022c1c394d9f91c390874557e611b47385/fixtures/coverall/src/coverall.udl#L156-L157), added almost-passing procmacro tests.
=> Update docs and tests for HashMap<>/record<>

fixtures/futures/src/lib.rs, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
`async fn` methods without extra parameters (other than `self`) worked previously, regressed in #1767.
New test previously failed Swift compilation with
```
<dir>/uniffi/target/tmp/uniffi-fixture-futures-dba82f227cc858a5/futures.swift:502:17: error: unexpected ',' separator
)
^
```
because `self.pointer` as the only argument had a comma after it in the argument list, which is not allowed in Swift.
=> Fix Swift codegen for async object methods without extra parameters

CHANGELOG.md, Cargo.lock, docs/manual/src/udl/interfaces.md, fixtures/metadata/Cargo.toml, fixtures/metadata/src/tests.rs, fixtures/trait-methods/src/lib.rs, fixtures/trait-methods/tests/bindings/test.py, fixtures/uitests/tests/ui/trait_methods_no_trait.stderr, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/library_mode.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/macros.rs, uniffi_core/src/metadata.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/attributes.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/util.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/metadata.rs, uniffi_meta/src/reader.rs, uniffi_udl/src/converters/interface.rs
The proc-macro mechanism is also used for UDL which allows a lot of scaffolding to be removed.
Fixes #1750, fixes #1548.
=> Allow uniffi_traits to be used with procmacros.

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
The dependency between `lib.rs` and `library_mode.rs` is a bit convoluted, but I think this turned out quite elegant.
=> Allow library mode to be used by external generators

docs/manual/src/SUMMARY.md, docs/manual/src/bindings.md, docs/manual/src/kotlin/configuration.md, docs/manual/src/python/configuration.md, docs/manual/src/swift/configuration.md, docs/manual/src/udl/ext_types_external.md, examples/custom-types/src/lib.rs, examples/fxa-client/README.md
Better docs for `uniffi.toml`, in preparation for a Python enhancement.
=> Update docs re uniffi.toml and tweaks to a couple of examples

uniffi_core/src/ffi/rustfuture.rs
If wake() is called while we are in the middle of polling a future, then we should immediately call our continuation function to schedule another poll.
=> Fix async wake behavior

CHANGELOG.md, docs/manual/src/udl/callback_interfaces.md, uniffi_core/src/ffi/callbackinterface.rs, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_core/src/lib.rs, uniffi_macros/src/custom.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
This is in preparation of #1578 -- allowing foreign languages to implement traits.
One issue there is that if we want to allow foreign languages to implement traits, then any Result return types need to implement `LiftReturn`, and that impl currently has a bound on `E: From<UnexpectedUniFFICallbackError`.  IOW, it's only implemented for errors that can be converted from UnexpectedUniFFICallbackError.
This makes sense when the trait is actually used by the foreign languages, however some traits are only intended to be implemented by Rust code.  For that matter, some libraries may be fine panicking in the the face of unexpected callback errors.
By using the auto-ref specialization hack, we're able to convert the error if there's a `From<UnexpectedUniFFICallbackError>` impl, but use a …
=> Make From<UnexpectedUniFFICallbackError> optional

docs/manual/src/SUMMARY.md, docs/manual/src/foreign_traits.md, docs/manual/src/udl/callback_interfaces.md, examples/callbacks/README.md, examples/callbacks/src/callbacks.udl, examples/callbacks/src/lib.rs, examples/callbacks/tests/bindings/test_callbacks.kts, examples/callbacks/tests/bindings/test_callbacks.py, examples/callbacks/tests/bindings/test_callbacks.swift
The main point of that is to somewhat de-emphasize callbacks and put them on an even keel with foreign traits. It doesn't go so far as to deprecate callbacks, but I think ultimately that's where we are likely to end up.
=> Add an example of and better docs for foreign traits.

fixtures/ext-types/proc-macro-lib/src/lib.rs, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.py, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.swift, fixtures/ext-types/uniffi-one/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/swift/templates/Async.swift
* Kotlin: fixed external types with async functions (#1798)
* Swift: fixed compile error when multiple crates define async functions
=> Fixed a couple issues with async code and multiple crates

.circleci/config.yml, README.md, docs/manual/book.toml, docs/manual/src/Overview.md, docs/manual/src/SUMMARY.md, docs/manual/src/internals/lifting_and_lowering.md, docs/manual/src/kotlin/configuration.md, docs/manual/src/proc_macro/index.md, docs/manual/src/python/configuration.md, docs/manual/src/swift/configuration.md, docs/manual/src/tutorial/Prerequisites.md, docs/manual/src/tutorial/udl_file.md, docs/manual/src/udl/callback_interfaces.md
Also arrange for mdbook-linkcheck to be used to check the links which should fail CI if broken links are re-added.
The manual has many broken links - many of which were added by me. Hopefully this fixes them!
=> Update README and fix broken links in the manual.

.circleci/config.yml
Docs used to be generated directly in `docs/manual/book`. Now that there's a new "target" for link-checking we have `docs/manual/book/html` and `docs/manual/book/linkcheck`
(at least I think that's what's going on :)
=> Fix doc generation - they are now generated in docs/manual/html

CHANGELOG.md, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.py, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.swift, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/Async.kt, uniffi_bindgen/src/bindings/python/templates/Async.py, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/Async.swift, uniffi_bindgen/src/interface/mod.rs, uniffi_core/src/ffi/rustfuture.rs, uniffi_macros/src/setup_scaffolding.rs, uniffi_meta/src/lib.rs
A single global callback won't work if there are multiple foreign modules.  Instead, input the callback in `poll()`.
Added some tests for this in `fixtures/ext-types/proc-macro-lib`. Things worked on Swift and Python for me because that code was based on leaking a pointer and it happened to work if the pointer came from another module.  It just halted on Kotlin though and I think the same would happen if I wasn't on CPython and the alternate PointerMangager was used.
=> Fix for multiple crates defining async functions

uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs
This is part of #1791, which was merged just after the `0.25.0` release was made.  We wanted to give that code a bit of time in main before releasing it.  However, this part is useful for traits implemented in Rust.
=> Backporting fix for trait methods that throw exceptions

CHANGELOG.md, fixtures/ext-types/proc-macro-lib/src/lib.rs, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.py, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.swift, fixtures/ext-types/uniffi-one/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/swift/templates/Async.swift, uniffi_core/src/ffi/rustfuture.rs, uniffi_core/src/lib.rs, uniffi_macros/src/setup_scaffolding.rs
Backporting a couple async fixes to the `0.25` release branch.
The tricky part here was the second commit.  In `main` this is handled with a breaking FFI change which we can't take in the release branch.  However, we can still fix the issue by adding a workaround in the scaffolding code.
=> Multi crate async 0.25

docs/manual/src/bindings.md, uniffi/src/cli.rs, uniffi_bindgen/src/bindings/kotlin/test.rs, uniffi_bindgen/src/bindings/python/test.rs, uniffi_bindgen/src/bindings/ruby/test.rs, uniffi_bindgen/src/bindings/swift/test.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
Instead of replacing `uniffi.toml` with override config entirely, merge the override config into `uniffi.toml`. The merge recursively upserts TOML keys.
This strategy seems pretty standard everywhere when it comes to configuration. Merging allows the configuration to be selectively changed, without having to duplicate the entire default configuration.
The main use case for this would be to allow "global" configuration across multiple crates in a library. Some configuration options should be the same for all crates in a library, without having to duplicate these options across all crates. Right now I can think of a few use cases of such configuration:
- In Swift generator, `omit_argument_labels`. I'm not entirely sure if anyone is actually using this, but it seems like an option that …
=> Merge override config with `uniffi.toml`

uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/object.rs
Other standard library types were already using a fully qualified name, but that wasn't the case for the `Send` and `Sync` bounds, which will cause issues in any code that has types named `Send` or `Sync` and is using the `uniffi` proc macros.
=> Fully qualify Send and Sync trait in generated code

uniffi_bindgen/src/bindings/swift/templates/Helpers.swift
Closes #1824.
This fix was discussed in briefly in matrix. https://github.com/mozilla/uniffi-rs/pull/1768 has some related work.
I've tested this work fix in https://github.com/liveview-native/liveview-native-core/pull/43
Is there a CI check I should add to prevent this in the future?
=> Replaced CancellationError with fatalError

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/python/templates/RecordTemplate.py, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/interface/record.rs
As seen in #1760, Kotlin can't have empty data classes, `object`s are used instead. In this PR, I modified the `RecordTemplate.kt` to produce objects for records with no fields, which should take care of that issue. Also, I had to fix some unknown issues when using empty records in other languages  (Swift, Python).
This means something like:
```rust
#[derive(uniffi::Record)]
pub struct MyEmptyRecord {}
```
Will produce:
```kotlin
object MyEmptyRecord {}
```
To be honest, I'm not 100% sure my changes to the `TypeConverters` for these record types make sense.
Also, being able to use `data object` instead of `object` would be nice, but it's only compatible with Kotlin 1.9+, and I'm not sure how to create a flag for that, or if it's possible at all.
=> Kotlin: allow exporting empty records

uniffi_bindgen/src/bindings/swift/templates/Helpers.swift
`fatalError()` just causes a crash, there's no need to throw it.  This removes some warnings when building the swift code.
=> Removing redundant `throw` in `Helpers.swift`

README.md
Add a 3rd party language "Dart".
This creates valid dart and I am using this this to generate the bindings for `matrix-rust-sdk` for use in my project.
=> Add Dart to the readme

CHANGELOG.md, fixtures/trait-methods/tests/bindings/test.kts, fixtures/trait-methods/tests/bindings/test.swift, fixtures/trait-methods/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
This brings those language to parity with Python.
Note that Kotin is using `Display` for `toString()` and there's no obvious way to expose `Debug`, so it isn't. Swift does seem to have a sensible way of exposing both `Debug` and `Display`.
Neither language seems to need `ne` so that's unused.
=> Rust traits `Display`, `Hash` and `Eq` exposed to Kotlin and Swift.

docs/manual/src/futures.md, docs/manual/src/udl/functions.md, fixtures/futures/src/futures.udl, fixtures/futures/src/lib.rs, fixtures/futures/src/uniffi_futures.udl, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/TopLevelFunctionTemplate.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/converters/callables.rs
If I realized it was this easy, I would have done this before.  `uniffi_udl` is great. Fixes #1716.
=> Adding UDL async support

fixtures/coverall/tests/bindings/test_coverall.kts, uniffi_bindgen/src/bindings/kotlin/templates/ObjectRuntime.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt
This PR is an alternative implementation of #1782 , with the 1st approach @bendk proposed [here](https://github.com/mozilla/uniffi-rs/pull/1782#issuecomment-1771432020):
> We could make the concrete type open. It's slightly risky because if you don't have an actual handle to a Rust object, then calling a UniFFI function will fail. But I would be okay with saying that users accept that risk if they extend the generated class. For your use case of only creating the objects if the native library isn't available, it seems like it should work fine.
The implementation changes are:
- `FFIObject.pointer` is now nullable. I know it's not great, but it's necessary as far as I can tell and I haven't seen any issues with it so far.
- `FFIObject` now has an alternate `constructor(noPointer: …
=> [Kotlin] Generate open classes and methods

docs/manual/src/proc_macro/index.md, docs/manual/src/tutorial/Rust_scaffolding.md, docs/manual/src/tutorial/foreign_language_bindings.md
=> Improve docs re: proc macros

fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, uniffi_macros/src/error.rs
We noticed a regression in `0.25.x` where dictionaries containing flat errors caused code not to be compiled.  We never officially supported compound types that stored errors, but it seems better to allow the code to compile in this case.
The reason this isn't supported is that we can't lift flat errors, so therefore we can't lift the dictionary.  A better fix for this would be to not implement `Lift` on the dictionary in this case, which would cause a compile error rather than a runtime panic.  However, that's actually not so simple as noted in the comment so I went for an easier way.
This brings this very close to how they worked in `0.24.x` where we would generate an `FfiConverter` implementation for flat errors, but the lift half of it would just be panics.
=> Implement `Lift` for flat errors

CHANGELOG.md
#1791 was incorrectly described as being in 0.25, add some other missing entries for .next.
=> Fixes and tweaks to the changelog

CHANGELOG.md, docs/manual/src/udl/ext_types.md, docs/manual/src/udl/ext_types_external.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/src/proc-macro.udl, fixtures/proc-macro/tests/bindings/test_proc_macro.py, uniffi_bindgen/src/interface/mod.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/finder.rs
People who want to slowly move away from UDL, or wish to stick with UDL but use some features available only to procmacros are a little stuck as currently it's impossible for UDL to reference types defined by procmacros in this crate. This PR makes that possible.
=> procmacro implemented types can be used in UDL.

docs/adr/0008-freeing-objects-and-resources.md
We've been discussing this one quite a bit lately and it seems like a great time to make a decision.  Here's the start of an ADR which lays out all the possibilities I've heard so far, I'd love to hear what others think.  I'm including everyone that I can remember having a discussion about this, but all voices are welcome.
=> ADR-0008: Freeing objects and resources

CHANGELOG.md, docs/manual/src/udl/ext_types_external.md, fixtures/ext-types/lib/src/ext-types-lib.udl, fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/uniffi-one/src/lib.rs, fixtures/ext-types/uniffi-one/src/uniffi-one.udl, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/external.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ExternalTypeTemplate.kt, uniffi_bindgen/src/bindings/python/gen_python/external.rs, uniffi_bindgen/src/bindings/python/templates/ExternalTemplate.py, uniffi_bindgen/src/bindings/swift/gen_swift/external.rs, uniffi_bindgen/src/interface/ffi.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_meta/src/types.rs, uniffi_udl/src/attributes.rs
Fixes #1831
Also fixes naming problem bindings with external types with unusual names.
=> Allow external traits to be used in UDL.

Cargo.lock, Cargo.toml, examples/README.md, examples/arithmetic-procmacro/Cargo.toml, examples/arithmetic-procmacro/src/lib.rs, examples/arithmetic-procmacro/tests/test.py, examples/arithmetic-procmacro/tests/test_generated_bindings.rs
I figured it made sense for someone who got pointed to our `examples` directory to be able to see what procmacros look like.
=> Add an arithmetic-procmacro example and tweaks to the examples README

fixtures/docstring-proc-macro/src/lib.rs, uniffi_core/src/metadata.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_meta/src/reader.rs
Fixes #1874
Docstrings are now using a u16 for length encoding to remove the 255 character limit. This should be more than enough for the buffer size that is used.
Implemented using separate long_string encoding to avoid increasing the size of the rest of the metadata.
=> Support docstrings longer than 255 characters

docker/cargo-docker.sh, fixtures/version-mismatch/kotlin-contract-mismatch.sh, fixtures/version-mismatch/kotlin-macro-mismatch.sh, fixtures/version-mismatch/kotlin-udl-mismatch.sh, fixtures/version-mismatch/python-contract-mismatch.sh, fixtures/version-mismatch/python-macro-mismatch.sh, fixtures/version-mismatch/python-udl-mismatch.sh, fixtures/version-mismatch/swift-contract-mismatch.sh, fixtures/version-mismatch/swift-macro-mismatch.sh, fixtures/version-mismatch/swift-udl-mismatch.sh
Search the path for `bash` vs expecting it at `/bin`. Just something small that I kept having to fix locally.
=> Switch to portable bash shebang

uniffi_macros/src/util.rs
We avoid storing useless spaces in proc-macros metadata.
=> fix(proc-macros): trim docstring lines

CHANGELOG.md, docs/manual/src/proc_macro/index.md, docs/manual/src/udl/interfaces.md, fixtures/proc-macro/src/lib.rs, uniffi_macros/src/object.rs
When reviewing #1662 I felt like I would be very annoyed to always have to wrap error objects with `Arc::new()`, this is an attempt to see if can avoid that.  It contains a general `FfiConverter` implementation for the struct itself, that simply wraps the value in `Arc::new()` then forwards the call to the normal `Arc<>` impl.
For constructors and other methods that return an object, UniFFI can wrap the object in an `Arc<>` just fine, the library doesn't need to do this.  Allowing the library to skip the wrapping can improve ergonomics, especially if we start to allow interfaces as errors.
=> Don't require objects to always be wrapped in `Arc<>`

Cargo.lock, uniffi_core/Cargo.toml
After trying a couple times to vendor our code into moz-central using a patch in `Cargo.toml`, I think this is a better solution.  I'm hoping to merge this into the `0.25.x` branch, release `0.25.3`, and use that.
This will test our release strategy a bit.  We should be able to upgrade moz-central to using `0.25.3` without changing Glean or app-services.
=> Depend on the patched oneshot version (#1736)

fixtures/ext-types/guid/tests/bindings/test_guid.py
This has been long deprecated and was removed in Python 3.12
=> Remove assertEquals calls

uniffi_macros/src/object.rs
We have found an issue - a compilation error, when using `Object` macro on some struct which uses type alias for `Result` as function return.
Affected version: `main` from commit: [59c1e3ef15b1ea5143402e25264e933dbf8d1a1f](https://github.com/mozilla/uniffi-rs/commit/59c1e3ef15b1ea5143402e25264e933dbf8d1a1f).
Proposed fix by @0xOmarA is to add full type path to the return `Result` in `lower_return()` function (content of this PR). 
Minimal program to reproduce this error (for simple reproduction it can be put in newly created `uniffi/tests/lib.rs` file):
```
pub struct UniFfiTag;
#[test]
fn error_reproduction() {
use uniffi::Object;
use std::sync::Arc;
pub type Result<T> = ::std::result::Result<T, u8>;
#[derive(Object)]
pub struct Foo;
impl Foo {
pub fn function() -> Result<Arc<Self>> { …
```
=> Error fix proposal for missing type path to returned Result in Object macro

uniffi_bindgen/src/scaffolding/mod.rs, uniffi_bindgen/src/scaffolding/templates/CallbackInterfaceTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_macros/src/export.rs, uniffi_macros/src/lib.rs
This makes it so the scaffolding templates use `export_for_udl` rather than generating their own code.
Split off from #1818 since I think this can land independently.
=> Always use `uniffi_macros` to generate callback interface scaffolding

uniffi_bindgen/src/bindings/kotlin/templates/Async.kt, uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt
PollResult is an `i8` in Rust, but was incorrectly specified as a `Short` in Kotlin.  Things seem to be working accidentally, but this should be fixed.
=> Fixing the Kotlin async function signatures

fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_core/src/ffi_converter_impls.rs
This is needed to allow these to work with proc-macros.
This is not needed for UDL, because there we generate a scaffolding function than inputs `&String`, then pass that value to the Rust function than inputs `&str`.  Rust can handle that conversion automatically.  However, with proc-macros the scaffolding function types are always exactly the same as the source function types.
=> Implement LiftRef for str and [T]

Cargo.lock
This brings in the `into_raw` and `from_raw` methods that we may want to use to pass oneshot senders over the FFI.  It still uses my patched version to avoid #1736.
=> Update oneshot-uniffi to 0.1.6

uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/templates/ObjectTemplate.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferStream.rb
Let's always use `uniffi`, `Uniffi`, or `UNIFFI`. Before some of the variable names had leading underscores, which seems redundant and not idomatic Kotlin.  My guess is that it comes from copy and pasted Python code.
I think the general contract with our users should be that we own the `uniffi` prefix.  If they want to name something `UniffiFoo`, then they take the risk of a name collision.
This is my personal take on the matter, but I'm fine with any naming scheme.  I just think we should be consistent about it.
=> Be more consistent with Ruby variable prefixes

uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs, uniffi_bindgen/src/scaffolding/templates/TopLevelFunctionTemplate.rs
Some of these were out of date.  I think the best policy is to point to the macro code and use that as the source of truth.
=> Update the scaffolding template comments to point to the macro code

docs/manual/src/udl/enumerations.md, fixtures/ext-types/external-crate/src/lib.rs, fixtures/ext-types/lib/src/ext-types-lib.udl, fixtures/ext-types/lib/src/lib.rs, fixtures/metadata/src/tests.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/util.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/reader.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/converters/enum_.rs
UDL types can now have the `[NonExhaustive]` attribute.  If present, we add a default branch arm to make things compile correctly with non-exhaustive enums.  I didn't want to make this the default behavior, since in the normal case we want missing variants to result in compile errors.
In theory, this also adds the `non_exhaustive` attribute for proc-macros.  However, there's no way to test this because `non_exhaustive` only matters for types defined in remote crates and there's currently no proc-macro support for those.
One slightly silly part of this is the flow of metadata.  It doesn't make much sense as a metadata field, since it doesn't affect bindings generation at all.  However, it needs to be because of the way that data flows from `uniffi_udl` -> `uniffi_meta` -> `uniffi_bindgen` …
=> Add support for non-exhaustive enums (#1593)

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/Async.kt, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceImpl.kt, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceRuntime.kt, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/README.md, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
Let's always use `uniffi`, `Uniffi`, or `UNIFFI`. Before some of the variable names had leading underscores, which seems redundant and not idomatic Kotlin.  My guess is that it was copy and pasted from Python.
I think the general contract with our users should be that we own the `uniffi` prefix.  If they want to name something `UniffiFoo`, then they take the risk of a name collision.
This is my personal take on the matter, but I'm fine with any naming scheme.  I just think we should be consistent about it.
=> Be more consistent with Kotlin variable prefixes

docs/manual/src/udl/interfaces.md
=> fix doc for exposing methods from standard Rust traits

fixtures/docstring-proc-macro/src/lib.rs, fixtures/docstring-proc-macro/tests/bindings/test_docstring.kts, fixtures/docstring-proc-macro/tests/bindings/test_docstring.py, fixtures/docstring-proc-macro/tests/bindings/test_docstring.swift, fixtures/docstring/src/docstring.udl, fixtures/docstring/src/lib.rs, fixtures/docstring/tests/bindings/test_docstring.kts, fixtures/docstring/tests/bindings/test_docstring.py, fixtures/docstring/tests/bindings/test_docstring.swift, uniffi_bindgen/src/bindings/python/gen_python/mod.rs
Uniffi docstrings can currently produce invalid python code if the rust comment contains double quotes.
To avoid this the python docstring implementation has been adjusted slightly.
* Always use multi-line docstrings.
* Escape `"""` with `\"\"\"`.
The following comment:
```rust
/// This is a docstring with "quotes" in it.
/// It also has a triple quote: """
/// And a even longer quote: """"""
```
Will produce the following python code:
```py
"""
This is a docstring with "quotes" in it.
It also has a triple quote: \"\"\"
And a even longer quote: \"\"\"""
"""
```
I believe this leaves the comments mostly intact which is in my opinion important since it's one of the few parts of the generated code that will be visible to consumer through intellisense. I would have preferred longer sequences …
=> Escape """ in python docstrings

uniffi_core/Cargo.toml, uniffi_core/src/ffi/rustbuffer.rs
I believe this was only used when integrating UniFFI in the mozilla-central reposition.  However, now that
https://bugzilla.mozilla.org/show_bug.cgi?id=1872200 is implemented it's not used there either.
=> Removing the extern-rustbuffer feature

fixtures/docstring-proc-macro/src/lib.rs, fixtures/docstring-proc-macro/tests/bindings/test_docstring.swift, fixtures/docstring/src/docstring.udl, fixtures/docstring/src/lib.rs, fixtures/docstring/tests/bindings/test_docstring.swift, fixtures/metadata/src/tests.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_core/src/metadata.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_meta/src/group.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/metadata.rs, uniffi_meta/src/reader.rs, uniffi_udl/src/collectors.rs, uniffi_udl/src/converters/enum_.rs
This means that we determine whether a name is used as an error by checking if, well, it's used as an error - it's not impacted by how the name is declared. This has been done primarily for future "objects as errors" work where we don't want to force an object to be declared specially to have it be able to be used as an error.
This has a side-effect which should be invisible to most users but is visible in our test suites - some of our test UDL declares an enum with `[Error]` but doesn't actually use that enum as an error. Previously this enum would get error semantics, whereas now it has been necessary to change these fixtures to use the object as an error. This should be invisible to real users because objects declared as being an error are either (a) used as an error or (b) unused, …
=> Remove uniffi_meta::ErrorMetadata.

fixtures/metadata/src/tests.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/reader.rs, uniffi_udl/src/converters/enum_.rs
Towards #1792 we should record the type of enum discriminants - python doesn't care, but others do.
=> Allow enum discriminant type to be specified

fixtures/uitests/tests/ui/export_attrs.rs, fixtures/uitests/tests/ui/export_attrs.stderr, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/attributes.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/lib.rs, uniffi_meta/src/lib.rs
Allows for better UX because attributes which don't make sense in a particular context are rejected rather than ingored.
Replaces ExportAttributeArguments with multiple structs, one per export context (ie, a struct, fn, trait, etc)
Also removes the undocumented `uniffi::export(constructor)` attribute on an impl block, just use `uniffi::constructor` on each fn.
=> Reject [uniffi::export()] arguments used in invalid contexts.

docs/manual/src/kotlin/gradle.md
Using JNA's Cleaner API in https://github.com/mozilla/uniffi-rs/pull/1869, which has been merged to main, needs at least JNA `v5.12.0` as we discovered later [here](https://github.com/mozilla/uniffi-rs/pull/1869#issuecomment-1902237867).
When I asked in the UniFFI Matrix room @badboy said the docs should be updated, so this should take care of that.
=> Update min supported JNA version in docs

fixtures/proc-macro/src/callback_interface.rs, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/util.rs
The easy part was implementing `LiftReturn`.  The hard part was figuring out how to handle TYPE_ID_META in the metadata code.  In general, we have an issue: should we get that from `Lift`/`LiftReturn` or `Lower`/`LowerReturn`.
As mentioned in the `fnsig` code, I feel like this is a bid of a band-aid.  However, I think a real fix would require significant changes to the FFI trait system and I don't want to do that so close to the v0.26 release.
=> Allow callback interfaces to return other callback interfaces (#1947)

CHANGELOG.md
I consolidated a few of the new entries and moved the instructions for upgrading to 0.23+ down to the 0.23 section. I failed to think of anything else we should call out, so I think this should then be fine for the release?
=> Update the changelog for the forthcoming 0.26.0 release

uniffi_udl/Cargo.toml, weedle2/Cargo.toml
After merging the changes, `cargo publish` failed for me.  I'm pretty sure it's because it's not pulling in the new weedle changes.  I believe we can fix this by bumping the weedle version, publishing that, then publishing the rest of the crates.
=> One more change for the 0.26.0 release

uniffi_core/src/ffi/callbackinterface.rs
The argument buffer being passed to the foreign callback is never destroyed, leading to a memory leak every time it's invoked
=> Destroy argument buffer after invoking a foreign callback

Cargo.lock, uniffi_udl/Cargo.toml, weedle2/Cargo.toml, weedle2/README.md
(Backported from the release-v0.26.x branch)
This was previously published as weedle 4.0.1, but this change was actually breaking:
https://github.com/mozilla/uniffi-rs/commit/bf9097cc2f8ef0ec37fd37795a0eeb3e26bbffe5#diff-389c79acae386eb845b5e78c7a4b3e284837370f5afb4e31daf5455c8cb200f9R238
I yanked the 4.0.1 release, let's release this with a new major version instead.
=> Bump weedle2 to 5.0.0

fixtures/uitests/tests/ui/export_attrs.rs, fixtures/uitests/tests/ui/export_attrs.stderr, uniffi_macros/src/lib.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
I added some more explicit errors when uniffi attributes are used incorrectly.
I started out seeing if I could do the same for `#[uniffi::constructor]`, but I don't think I can. I updated the comments for this attribute - I *think* the old comment was stale, but I'm really not sure how accurate my new comment is - after updating the uitest I realized I really don't understand things well at all.
@jplatte do you mind checking that the comments I removed were indeed stale, and that the comments I added are at least an improvement? Any insights to make the comments more accurate would obviously be welcome too.
=> Add more errors when #[uniffi] attributes are used incorrectly.

examples/arithmetic-procmacro/Cargo.toml
Since there is no `build.rs` file, I don't think the build dependency has any effect.
=> Try removing build dependency in procmacro example

fixtures/simple-fns/src/lib.rs, fixtures/simple-fns/tests/bindings/test_simple_fns.py, uniffi_bindgen/src/bindings/python/gen_python/compounds.rs, uniffi_bindgen/src/bindings/python/templates/wrapper.py
This adds type hints to Python dicts.
I couldn't find official documentation indicating what Python versions uniffi supports, so I wrote it to support 3.8+ as that's the oldest version not EOL.
In 3.8, the correct way to do this would be `typing.Dict[X, Y]`. Then in 3.9, support was added for `dict[X, Y]` and the original way was deprecated. By importing `from __future__ import annotations`, we can support the current way on 3.8 as well.
=> Add type hints to Python dict

uniffi_core/Cargo.toml
I added contributed a new feature for this one to convert between `Sender` and a raw pointer.  I want to use this to handle foreign-implemented async trait methods.
=> Upgrade oneshot to 0.1.6

CHANGELOG.md, Cargo.lock, docs/manual/src/futures.md, fixtures/futures/Cargo.toml, fixtures/futures/src/futures.udl, fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.kts, fixtures/futures/tests/bindings/test_futures.py, fixtures/futures/tests/bindings/test_futures.swift, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_macros/src/export/trait_interface.rs
This was pretty easy, it mostly meant not hard coding that we don't support async methods and which order to apply `#[uniffi::export]` vs `#[async_trait::async_trait]`.
The next step is foreign-implemented traits.
=> Adding support for Rust async trait methods

fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.py, uniffi_bindgen/src/bindings/python/templates/TopLevelFunctionTemplate.py, uniffi_bindgen/src/bindings/python/templates/macros.py
As discussed in #1970, uniffi currently doesn't put a return type on generated async functions in Python. 
This is my attempt at correcting the function signatures it generates. Because the diff is a bit bad, I'll summarize the changes:
- For async functions, match on if they have a return type
a. If they do, add `async` to the front of the function, add the `-> ___` return type, and add `await` to the return statement.
b. If they don't, still add `async` to the front of the function and `await` to the return.
- Remove the `match meth.return_type()` cases from the body of the function, as it's now being checked outside of the function
The changes are repeated in `macros.py` and `TopLevelFunctionTemplate.py`
`b.` technically could remain unchanged, but it seemed more correct to make the …
=> Add Python return type for async functions

uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
With https://github.com/mozilla/uniffi-rs/pull/1918 in limbo and based on [this comment](https://github.com/mozilla/uniffi-rs/pull/1918#issuecomment-1872161231) I went ahead and extracted out only the bits that open up generated swift classes. 
This shouldn't be controversial and will allow us to mock client side.
Previously done for Kotlin here https://github.com/mozilla/uniffi-rs/pull/1815
=> Swift open classes

uniffi_bindgen/src/bindings/kotlin/templates/SequenceTemplate.kt
The `forEach` here was not introduced until API level 24, this small tweak helps to maintain compatibility.
Tested via `cargo test` as well as in our own project (https://github.com/xmtp/libxmtp).
=> Use iterator in generated Kotlin to maintain Android API level 22 compatibility

fixtures/futures/tests/bindings/test_futures.py, fixtures/simple-fns/tests/bindings/test_simple_fns.py
edit: As @badboy points out, we probably do want strings - sorry about that. It turns out `typing.get_type_hints()` does the magic we need to make the tests sane and able to check against actual types.
=> Use typing.get_type_hints() in python type tests

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/uitests/tests/ui/export_attrs.rs, fixtures/uitests/tests/ui/export_attrs.stderr, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_macros/src/export.rs, uniffi_macros/src/export/attributes.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/util.rs
Fixes #1753
While #1753 talks just about the constructor, I noticed that we already had the capability of using different names for exported items but just lacked a way to express that.
=> Allow procmacro exported items to be renamed.

uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
It seems that #1918 and implicitly #1975 missed one important aspect when opening up classes for mocking:
- the current deinit implementation shouldn't be called for mocked/subclassed objects because the internal `pointer` is nil in those cases and doing so will result in a `Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`
- deinit is also not overridable in Swift so this is not something that can be worked around downstream
This PR attempts to fix the problem by introducing a guard to check that `pointer` is not nil before trying to free it.
=> Prevent Swift objects' `deinit` from trying to free a nil pointer when subclassed for mocking

uniffi_bindgen/src/bindings/kotlin/test.rs, uniffi_bindgen/src/bindings/python/test.rs, uniffi_bindgen/src/bindings/ruby/test.rs, uniffi_bindgen/src/bindings/swift/test.rs
Joining “.” with anything ought to be the same as using anything directly.
=> Simplify path in bindings tests

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/BridgingHeaderTemplate.h, uniffi_bindgen/src/interface/ffi.rs, uniffi_bindgen/src/interface/mod.rs
This was not quite a pure refactor, because some of the code generation for FFI definitions changed.  AFAICT, it should be equivalent far all current FFI definitions though.
Added the `FfiDefinition` enum, which can hold any type of FFI definition (struct, function, or callback function).  Added `ComponentInterface::ffi_definitions` to iterate over all of the definitions.  The reason for this is that FFI definitions can have complicated dependencies and some languages require that the dependencies come first in source order.  By defining a single function to output all definitons, we can ensure that they come out in the right order.
Factored out the Rust FFI return types calculation into its own function.  I want to use it in some other places.
Updated the codegen for FFI definitions:
- …
=> Refactor FFI definition code

uniffi_bindgen/src/bindings/kotlin/templates/Async.kt
Fixes https://github.com/mozilla/uniffi-rs/issues/1995
I'm not exactly sure why but certain java runtimes can't distinguish between `uniffiRustFutureContinuationCallback` and `UniffiRustFutureContinuationCallback`. the issue manifests in various ways but I was getting `java.lang.NoClassDefFoundError`:
```
java.lang.NoClassDefFoundError: uniffi/<crate>/uniffiRustFutureContinuationCallback (wrong name: uniffi/<crate>/UniffiRustFutureContinuationCallback)
```
I patched in this version of uniffi and verified that it's fixed
=> Rename kotlin uniffiRustFutureContinuationCallback to uniffiRustFutureContinuationCallbackImpl

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/manual/src/proc_macro/index.md, fixtures/enum-types/Cargo.toml, fixtures/enum-types/build.rs, fixtures/enum-types/src/enum_types.udl, fixtures/enum-types/src/lib.rs, fixtures/enum-types/tests/bindings/test_enum_types.kts, fixtures/enum-types/tests/bindings/test_enum_types.py, fixtures/enum-types/tests/bindings/test_enum_types.swift, fixtures/enum-types/tests/test_generated_bindings.rs, fixtures/enum-types/uniffi.toml, uniffi_bindgen/src/backend/filters.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/interface/enum_.rs
Part of #1792 
I started with proc macros as trying to get the types in UDL is painful (without trying to hackily do stuff like putting the type into the string, etc). I still would like to write up some documentation on this but wanted to get the PR up for early eyes!
=> Generate underyling enum variant literals for swift and kotlin

fixtures/enum-types/src/lib.rs, fixtures/enum-types/tests/bindings/test_enum_types.py, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py
The generated Python code didn't raise an exception after checking all variants. Without the fix the new test fails with:
> enum_types.InternalError: Failed to convert arg 'a': not enough bytes remaining in buffer (0 < 4)
Also upgrades the test to a unittest.
=> Fix Python checking for invalid enum values.

fixtures/uitests/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_macros/Cargo.toml, uniffi_macros/src/lib.rs
As far as I can see, the dependency on uniffi_build is not needed for the macros used by regular clients of UniFFI — it is only used to create a convenience macro for the UI tests.
I named the new feature “trybuild” after the description of the macro. Please let me know if you have preferences for a better name.
The overall goal here is to minimize the number of crates I need to vendor to use UniFFI — I’m hoping to get away with checking in the generated target language sources, so I’m currently focusing on the dependencies in the rest of the code base.
=> Make `uniffi_build` optional in `uniffi_macros`

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/enum-types/src/lib.rs, fixtures/enum-types/tests/bindings/test_enum_types.kts, fixtures/enum-types/tests/bindings/test_enum_types.py, fixtures/enum-types/tests/bindings/test_enum_types.swift, fixtures/uitests/tests/ui/enum_discriminants.rs, fixtures/uitests/tests/ui/enum_discriminants.stderr, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_macros/src/enum_.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/reader.rs
Also now generates an error rather then silently ignoring when a discriminant value is an expression or anything else we can't handle.
=> Allow enum discriminants to be signed.

CHANGELOG.md, docs/manual/src/udl/enumerations.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift, uniffi_bindgen/src/interface/enum_.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/util.rs
These are represented in the CI as enum variants with nameless fields.
Part of #1078, although no support for UDL yet.
=> procmacros support tuple-enums

uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/fnsig.rs
This is a refactor to enable some future work.  By tracking the parameter names and types separately we get some extra flexibility, for example iterating over the types only.
=> Split up ScaffoldingBits.params

fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/primitives.rs
=> Allow enum variants etc to be Kotlin type names

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, fixtures/uitests/tests/ui/export_attrs.rs, fixtures/uitests/tests/ui/export_attrs.stderr, uniffi_macros/src/default.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/attributes.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/record.rs, uniffi_meta/src/reader.rs
- Renamed `FieldDefault` to `DefaultValue` and shared it between the field and argument code.
- Updated the function argument metadata to support a default value.
- Added `FnArgAttributeArguments` which is currently exactly the same as `FieldAttributeArguments`.  I figure the repeated code is fine for now and these structs may diverge in the future.
- Changed `expand_export` to return the source item as well.  This allows it to modify the source item and strip away the defaults
- Fixed Python argument checking when there's a default.
=> Allow defaults for proc-macro function arguments

fixtures/docstring-proc-macro/tests/test_generated_bindings.rs, fixtures/docstring/tests/test_generated_bindings.rs, fixtures/swift-bridging-header-compile/tests/clang.rs, uniffi/src/cli.rs, uniffi/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/test.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/test.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/test.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/test.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
De-couple TargetLanguage from the `generate_external_bindings` calls. This will allow 3rd-party BindingGenerators to use the methods.
I'm not 100% certain this is the way to go, and I'm very open to feedback. cc @bendk @mhammond
Related to https://github.com/mozilla/uniffi-rs/issues/299
=> Allow for arbitrary BindingGenerator

examples/async-api-client/README.md, examples/async-api-client/src/api_client.rs, examples/async-api-client/src/async-api-client.udl, examples/async-api-client/src/lib.rs, examples/async-api-client/src/tasks.rs, examples/async-api-client/src/test_data.rs, examples/async-api-client/tests/bindings/test_async_api_client.kts, examples/async-api-client/tests/bindings/test_async_api_client.py, examples/async-api-client/tests/bindings/test_async_api_client.swift
When discussing  #1837, @mhammond asked me a great question:  should  blocking task queues be UniFFI's responsibility?  This is my attempt to see what would happen if we decided it wasn't.
The code here implements more-or-less the same feature as #1837, but without changing any UniFFI code.  Instead it leverages async callback methods to implement it.
Benefit of this approach:
- No new code needed
- No new features to commit to supporting
- Somewhat more flexible.  With #1837, Python users need to use `futures.executor.ThreadPoolExecutor`.  With this approach, they can use whatever technology they want.
Downsides of this approach:
- Tasks need to be `'static` and cannot use references from their local scope.  [This makes the code somewhat …
=> Blocking task queue without specialized code

CHANGELOG.md, docs/manual/src/swift/configuration.md, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
Make it possible to mark Swift value types as [`Sendable`](https://developer.apple.com/documentation/swift/sendable) - which is needed for Swift 6.
* Add new config for Swift: `sendable_value_types` (false by default)
* which if true (`sendable_value_types: true`) will mark:
- (`[uniffi::Record]`) Swift `struct`s which does not contain object references as `Sendable`
- (`[uniffi::Enum]`) Swift `enums`s which does not contain object references as `Sendable`
This will make it possible for Swift devs to [skip having to add `@unchecked Sendable` all over the place](https://github.com/search?q=repo%3Aradixdlt%2Fsargon%20%40unchecked%20Sendable&type=code)
I was unable to add a meaningful fixture though, since it is not possible to "unit test" this. The only way to "test" it is to ensure that …
=> Swift: Make it possible to mark value types as `Sendable` with `sendable_value_types` config

uniffi_meta/src/reader.rs
Since #1672 was merged, we support both `Arc<Self>` and `Self` return types.
This fixes the confusing error message that we're discussing in #2051
=> Make the proc-macro constructor error more precise

CHANGELOG.md, fixtures/uitests/tests/ui/export_attrs.stderr, uniffi_macros/src/export.rs, uniffi_macros/src/export/attributes.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/fnsig.rs
These were basically the same, so using 1 struct simplifies the code.
The one difference was that ExportFnArgs allowed an async runtime to be specified.  Now that the 2 are merged, it's possible to specify an async runtime for constructors/methods.  If present that runtime will override the one specified in the impl attribute.
=> Combine ExportedImplFnArgs and ExportFnArgs

fixtures/keywords/kotlin/src/keywords.udl, fixtures/keywords/kotlin/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/templates/Async.kt, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt
If a Rust enum is named `Error`, it becomes `Exception` in the generated Kotlin. The problem is that this class inherits from `Exception`, which I think it supposed to be a built-in Kotlin type:
```kotlin
sealed class Exception : Exception() {
class Foo() : Exception() {
override val message
get() = ""
}
companion object ErrorHandler : UniffiRustCallStatusErrorHandler<Exception> {
override fun lift(error_buf: RustBuffer.ByValue): Exception = FfiConverterTypeError.lift(error_buf)
}
}
```
If I use `FooError` instead on the Rust side, the code above changes to `class FooException : Exception`.
=> `Error` creates Kotlin inheritance loop

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.swift, fixtures/futures/src/lib.rs, fixtures/futures/tests/bindings/test_futures.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
#2048 regressed swift constructors which throw. Fixes #2058
I need to look over this some more, but got this up for early feedback. I'll land it and cut a new release tomorrow.
=> Fix fallible constructors for swift.

uniffi_core/src/ffi/rustfuture/mod.rs
Currently, `rust_future_free` doesn't properly release memory, leading to a memory leak. This happens because `get_arc` increases the reference count of RustFuture without decreasing it afterward. By using `consume_handle` we do not increase it anymore before giving the ownership to `ffi_free`.
I have tested this fix in my project and confirmed that it resolves the memory leak. Let me know if I missed something.
=> RustFuture: fix memory leak

docs/manual/src/tutorial/udl_file.md
The proc-macro method is now mentioned upfront, instead of as a bottom note. 
This provides a clearer context for new users.
=> improves the "Describing The Interface" page for clarity

fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.py
#1774 said it doesn't work but it does if you pass the correct type
=> Demonstrate passing a hashmap to a procmacro function.

CHANGELOG.md, fixtures/benchmarks/benches/benchmarks.rs, fixtures/docstring-proc-macro/tests/test_generated_bindings.rs, fixtures/docstring/tests/test_generated_bindings.rs, uniffi/src/cli.rs, uniffi/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/test.rs, uniffi_bindgen/src/bindings/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/python/test.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/test.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/bindings/swift/test.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
Previously there were internal `Config` details which only worked with
builtin bindings types. This leans in to the `BindingGenerator` trait
to make things less coupled with the builtin bindings and better
for external bindings.
=> Allow the binding generator to not depend on builtin bindings.

fixtures/metadata/src/tests.rs, fixtures/uitests/tests/ui/invalid_types_in_signatures.stderr, uniffi/tests/ui/proc_macro_arc.stderr, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_core/src/lib.rs, uniffi_macros/src/custom.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs
The metadata code now uses this trait to get the `TYPE_ID_METADATA` rather than Lift/Lower.  This feels cleaner, since it was often not clear which trait to use before. This removes the hacky handling of type id metadata for callback interfaces that I added in #1950.
Let's not merge this until after 0.26.0 is released.  It feels like too big of a change at this point in the process.
=> Adding the `TypeId` FFI trait

fixtures/error-types/src/lib.rs, fixtures/error-types/tests/bindings/test.swift, uniffi_bindgen/src/bindings/swift/templates/Async.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/Helpers.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
Solves https://github.com/mozilla/uniffi-rs/issues/2079
This PR makes it possible to name a type `Error` at let it be exported into Swift. It is is a quite simple PR which adds `Swift.` disambiguation.
=> Swift: Enable error types to be named `Error`

uniffi_macros/src/custom.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/ffiops.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
Put these all in one module in preparation of updating how this code works. I'm hoping to rework custom type handling and also drop the `UniFfiTag` param. By factoring these into their own module and away from the specific usages, future changes like that should be easier to understand.
I think there are no functional changes here. In a couple places I replaced `FfiConverterArc<Self>` with `SomeFfiTrait<Arc<Self>>`, but those should be equivalent.
=> Factor out FFI converter operations

fixtures/ext-types/custom-types/src/lib.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs
I tried to consume the change from #2075 today and noticed that it didn't cover my use case, where a type alias is used as the key for a HashMap which also is an alias. I added a test showing this and made a change to the sorting algorithm to fix this. 
The current algorithm for ordering type aliases is: "if the typename I'm inserting into the sorted list _is the type_ for something already in the list, put this item in front of it".
My proposed new algorithm is: "if the typename I'm inserting into the sorted list is _included in the nested types_ for something already in the list, put this item in front of it".
=> Add more functionality to get_custom_type_aliases sorting

fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ErrorTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs, uniffi_macros/src/derive.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_macros/src/util.rs
This is prep work for implementing the system for remote / custom / external types as described in #2087.  The generated code should stay exactly the same, this just refactors how it's generated.
Consolidated the `derive_*_for_udl` macros into a single `udl_derive` macro and added the `DeriveOptions` struct.  I think that we can update UDL-generation to create blanket FFI trait impls by just tweaking which flags we set.  We can also re-use the same pattern to implement remote types (which will have `generate_metadata: true, local_tag: true`).
Changed the specific derive code to use `DeriveOptions` plus an item struct.  For example  RecordItem, which represents the parsed DeriveInput for the record. This will make future changes easier since we only need to modify one of these structs, not …
=> Refactor the derive macro code

Cargo.lock, uniffi_bindgen/Cargo.toml, uniffi_udl/Cargo.toml
Docstrings rarely have unicode characters so these are not adding much value.  They present an issue for the downstream moz-central crate (https://bugzilla.mozilla.org/show_bug.cgi?id=1894888), so let's remove them.
=> Remove the unicode-linebreak / unicode-width dependencies

Cargo.lock, examples/arithmetic/Cargo.toml, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/ffi_buffer_scaffolding_test.rs, fixtures/coverall/src/lib.rs, fixtures/ext-types/lib/Cargo.toml, fixtures/futures/Cargo.toml, fixtures/proc-macro/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/src/interface/ffi.rs, uniffi_core/Cargo.toml, uniffi_core/src/ffi/ffiserialize.rs, uniffi_core/src/ffi/mod.rs, uniffi_core/src/ffi/rustbuffer.rs, uniffi_core/src/ffi/rustcalls.rs, uniffi_core/src/lib.rs, uniffi_macros/Cargo.toml, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/util.rs, uniffi_meta/src/ffi_names.rs
These are alternate versions of the current scaffolding functions that use u64 buffers to handle their input/output.
The main use case is the gecko-js bindings used in Firefox.  This allows us to replace the generated C++ code with static code, since the scaffolding functions now always have the exact same signature.
I added ffi buffer versions of all generated scaffolding functions.    I didn't make them for "static" functions, like the rust_buffer FFI functions.  I don't think we need them there since the signature is always the same.
Added `do not merge` because I want to test that this will actually work first, but the code is ready for review.
=> Added ffi-buffer scaffolding functions

CHANGELOG.md, docs/manual/src/udl/errors.md, fixtures/error-types/src/error_types.udl, fixtures/error-types/src/lib.rs, fixtures/error-types/tests/bindings/test.kts, fixtures/error-types/tests/bindings/test.py, fixtures/error-types/tests/bindings/test.swift, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_core/src/lib.rs, uniffi_macros/src/error.rs, uniffi_macros/src/ffiops.rs, uniffi_macros/src/object.rs
This specifies how types are lowered when they are the `E` side of `Result<T, E>`.  The main reason for the trait is that it lets us specialize the handling for interfaces by auto-wrapping the value in an Arc.
This makes using interfaces as errors much more ergonomic.
Also, replace the `Error` bound on the `E` types with `Display + Debug`. I just found out that `anyhow::Error` doesn't actually implement `Error` for some obscure reason.
=> Adding the `LowerError` trait

CHANGELOG.md, Cargo.lock, uniffi_core/Cargo.toml, uniffi_core/src/ffi/foreignfuture.rs, uniffi_core/src/lib.rs, uniffi_core/src/oneshot.rs
Implemented our own oneshot channel using a Mutex.  It's not quite as efficient as the `oneshot` one, but I think it should be fine for our purposes.  My gut feeling is that the loss of overhead is neglibable compared the other existing overhead that UniFFI adds.
The API of the new oneshot is basically the same, except send/recv are not failable.
=> Remove the oneshot dependency (#1736)

.circleci/config.yml, mkdocs.yml, tools/requirements_docs.txt
=> mkdocs: Use pymdown-extensions to get syntax highlighting in the docs

CHANGELOG.md, Cargo.lock, examples/arithmetic/Cargo.toml, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/ffi_buffer_scaffolding_test.rs, fixtures/coverall/src/lib.rs, fixtures/ext-types/lib/Cargo.toml, fixtures/futures/Cargo.toml, fixtures/proc-macro/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/src/interface/ffi.rs, uniffi_core/Cargo.toml, uniffi_core/src/ffi/ffiserialize.rs, uniffi_core/src/ffi/foreignfuture.rs, uniffi_core/src/ffi/mod.rs, uniffi_core/src/ffi/rustbuffer.rs, uniffi_core/src/ffi/rustcalls.rs, uniffi_core/src/lib.rs, uniffi_core/src/oneshot.rs, uniffi_macros/Cargo.toml, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/util.rs, uniffi_meta/src/ffi_names.rs
I'm hoping to get these changes released so that Firefox can consume them.  Does this make sense for a 0.27.2 release?  Are there any other changes that should go in there?
=> Changes for the `0.27.2`

docs/manual/src/futures.md, fixtures/futures/tests/bindings/test_futures.py, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/Async.py, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceImpl.py, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceRuntime.py, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceTemplate.py, uniffi_bindgen/src/bindings/python/templates/HandleMap.py, uniffi_bindgen/src/bindings/python/templates/wrapper.py
=> Prefix newly added globals in Python with underscores

docs/manual/src/tutorial/udl_file.md
Just fixing a couple of small typos in the Getting Started guide ❤️
=> Fix typos in user guide tutorial udl_file

fixtures/enum-types/src/lib.rs, fixtures/enum-types/tests/bindings/test_enum_types.kts, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
As reported in issue #2089 there is a bug generating non-compiling Kotlin code. This happens when exporting a Enum with an associated value that is a `Arc<Object>`. This led to non-compiling Kotlin code:
```
Disposable.destroy(
this.``)
```
I recreated this by adding a Enum in fixtures and got the same compile-time error:
```
#[derive(uniffi::Enum)]
pub(crate) enum AnimalAssociatedType {
Dog(Arc<AnimalObject>),
Cat,
}
```
This issue was caused by the `destroy_fields` macro. Previously there was no checks if the `field.name()` was empty leading to the macro creating empty methods in cases where some fields had a name and some didn't.
I added a check for `field.name().is_empty()` and in such cases no `destroy` method will be generated by the macro.
No additional tests were added since this …
=> Bugfix: Enum with associated value generates non compiling Kotlin code

CHANGELOG.md, uniffi/src/cli.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/bindings/swift/test.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
This is a breaking change for BindingGenerators, and follows up on other breaking changes made for this release (#2078). Between them, it is intended to offer a better framework for binding generators for future versions and break unintentional coupling between uniffi_bindgen and the builtin bindings.
This patch updates the `BindingGenerator` trait to give binding generators more control over the binding generation process and to simplify the interactions between the generator and `uniffi_bindgen`.
The trait `BindingsConfig` has been removed and replaced with a new method on `BindingGenerator` which passes the generator the entire list of all `ComponentInterface` and `Config` objects to be used in the generation, which the generator can modify as necessary. The binding generator is also …
=> Update the BindingGenerator trait and remove BindingsConfig.

CHANGELOG.md, fixtures/error-types/tests/bindings/test.kts, fixtures/error-types/tests/bindings/test.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
Also some extra error string semantics tests for kotlin.
Fixes #2110
=> Add localizedDescription support to swift errors.

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/error-types/src/lib.rs, fixtures/error-types/tests/bindings/test.kts, fixtures/error-types/tests/bindings/test.py, fixtures/error-types/tests/bindings/test.swift, uniffi_bindgen/src/bindings/kotlin/templates/ErrorTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_bindgen/src/bindings/python/templates/ErrorTemplate.py, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift
Follows on from #2004 which allowed tuple enums in plain enums, it's now possible to use tuple enums for errors.
=> Allow errors to be tuple enums.

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs
Both bindings supply a default for package_name/cdylib which is different to the default actually and unconditionally applied.
(I found this commit from a while ago and dusted it off - I think less confusion is good.)
=> Remove unused and incorrect defaults in Kotlin and Swift.

uniffi_bindgen/src/bindings/python/templates/Async.py, uniffi_bindgen/src/bindings/python/templates/Helpers.py, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_bindgen/src/bindings/python/templates/README.md, uniffi_bindgen/src/bindings/python/templates/RustBufferTemplate.py, uniffi_bindgen/src/bindings/python/templates/macros.py
Always use `uniffi`, `Uniffi`, or `UNIFFI` for module-level names.  Add a leading underscore for private class members.  I think this is the most Pythonic naming style. Because we define `__all__` for modules, there's no chance that users will accidentally import the UniFFI items with `from module import *`
Before there were lots of leading underscores, but I don't see the point and it doesn't feel Pythonic to me.
I think the general contract with our users should be that we own the `uniffi` prefix.  If they want to name something `UniffiFoo`, then they take the risk of a name collision.
This is my personal take on the matter, but I'm fine with any naming scheme.  I just think we should be consistent about it.
=> Be more consistent with Python variable prefixes

.circleci/config.yml, docs/manual/src/internals/crates.md, docs/manual/src/swift/overview.md
The generation of these docs generates a lot of churn in the gh-pages branch - even when nothing has changed - so instead we skip building and publishing them and link to the generated pages on docs.rs.
This will mean that once versioned docs land, most doc publish jobs will be no-ops.
=> Stop building and publishing Rust API docs.

docs/manual/src/README.md, docs/release-process.md, mkdocs.yml, tools/make_old_docs_symlinks.py, tools/requirements_docs.txt
This causes the version selector to be rendered into the pages, however they will not be shown until we actually deploy version information.
Includes a script to help generate redirects for all our "old" pages.
On the path to #2016. Actual deployment using this system to follow once these are landed.
=> Introduce `mike` to the doc generation process.

docs/manual/src/kotlin/gradle.md
discovered in https://github.com/rustls/rustls-platform-verifier/pull/63#issuecomment-2125127857
It will help uniffi's callback performance.
=> docs(kotlin): mention `AttachCurrentThread`

docs/manual/src/tutorial/foreign_language_bindings.md
Overview.md got dropped with the mkdoc change and doc builds keep warning about it.
=> Fix broken overview link in docs

uniffi_core/src/ffi/handle.rs
=> Clarify pointer alignment for `Handle`

uniffi_bindgen/src/bindings/swift/templates/RustBufferTemplate.swift
This avoids unnecessary copies between FFI and Swift.
Tests are apparently entirely unaffected (i.e. no changes to their results) by this change. `deallocator` is set to `.none` since the `FfiConverterRustBuffer` extension function `lift(_:)` ensures deallocation on it's own.
=> Use Data(bytesNoCopy:size:deallocator:) for conversion between RustBuffer and Data

uniffi_core/src/ffi/rustbuffer.rs
The method is used from outside of this module, so the comment seems unnecessary: the method should either be private or it should be public.
=> Make `RustBuffer::from_raw_parts` comment more precise

docs/manual/src/proc_macro/index.md
`Option<&T>` was never supported as far as I can tell.  I added some tests on top of e10a7f95d6b5bd8b4788d8f0eb77aea20dfb655b, where that documentation was added and it didn't work.
See https://github.com/mozilla/uniffi-rs/issues/2149 for some more discussion around this.
=> Fix the documentation around references

uniffi_core/src/ffi/ffiserialize.rs, uniffi_core/src/ffi/foreignfuture.rs, uniffi_core/src/ffi/rustcalls.rs, uniffi_core/src/ffi/rustfuture/tests.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_macros/src/export/callback_interface.rs
`error_buf` is owned by the foreign side. Because we assume it has been initialized we use `ManuallyDrop` instead of `MaybeUninit`, which clarifies ownership and avoids unsafe code.
Fixes #2168
=> `RustCallStatus::error_buf` is now `ManuallyDrop` and not `MaybeUninit`.

uniffi_core/src/ffi/ffiserialize.rs, uniffi_meta/src/types.rs
=> Use fully-qualified names to the stdlib's `core` library

Cargo.lock, Cargo.toml, fixtures/proc-macro-no-implicit-prelude/Cargo.toml, fixtures/proc-macro-no-implicit-prelude/build.rs, fixtures/proc-macro-no-implicit-prelude/src/callback_interface.rs, fixtures/proc-macro-no-implicit-prelude/src/lib.rs, fixtures/proc-macro-no-implicit-prelude/src/proc-macro.udl, fixtures/proc-macro-no-implicit-prelude/uniffi.toml, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_core/src/ffi/callbackinterface.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_core/src/lib.rs, uniffi_macros/src/custom.rs, uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/fnsig.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_macros/src/setup_scaffolding.rs, uniffi_macros/src/test.rs
This is what I was talking about in #2177. I think you weren't missing anything @mhammond, it's a bunch of boilerplate so I put it in a new fixture instead of `proc-macro`. It's a copy of that one though.
Note that there is still the language prelude that is _not_ disabled by this attribute (which contains primitive types such as `u8` and I think `str` as well, plus lots of macros like `#[align]`, `#[allow]`, `#[automatically_derived]`, ...). Because some of these things can nevertheless be shadowed, this test doesn't catch all potential name confusions within macro code. It it pretty good at it though, as you can see in the first commit 😄 (the few `::std::primitive` insertions were drive-by improvements and not steered by error messages)
=> Create fixture proc-macro-no-implicit-prelude

docs/manual/src/kotlin/configuration.md, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt
Since Kotlin `1.9`, the `.entries` property is generated at build time for enum classes. Unlike `Enum.values()`, this property doesn't instantiate a new array with every enum case every time it's used, instead a single List instance is reused.
This should improve performance a tiny bit for Kotlin bindings. However, note this will only be supported since Kotlin 1.9, I don't know if there is a min version the project wants to support.
=> Kotlin: use `Enum.entries` instead of `Enum.values()`

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs
We're moving towards making this an optional dependency.
=> Don't use cargo_metadata to parse version numbers

uniffi_core/src/ffi/rustcalls.rs, uniffi_core/src/ffi/rustfuture/future.rs, uniffi_core/src/ffi/rustfuture/mod.rs, uniffi_core/src/ffi/rustfuture/tests.rs, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/object.rs
This avoids crashing for consumers that set panic=abort (Firefox).
- Updated the Err type for `rust_call`.  The closure can now return an internal error.  The only way to signal an internal error before was to panic.
- Reworked the `LowerReturn` trait and the future code to work with the new system.
- Added a type for argument lift errors, this makes the rustfuture signatures nicer.
=> Don't panic for try_lift errors

fixtures/benchmarks/Cargo.toml, fixtures/benchmarks/benches/benchmarks.rs, uniffi/Cargo.toml, uniffi/src/lib.rs, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/mod.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/ruby/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/library_mode.rs, uniffi_macros/src/test.rs
The `uniffi_test` crate unconditionally depends on `cargo_metadata`, and this will be difficult to change. This means that because `uniffi_test` is an unconditional dependency of `uniffi_bindgen`, the `cargo_metadata` feature doesn't actually prevent `uniffi_bindgen` from depending on `cargo_metadata`.
The top level `uniffi` create already has a feature `bindgen-tests`. This patch introduces a feature of the same name to `uniffi_bindgen`. Enabling that feature also enables the metadata feature. This means that if you do not enable either of these features you should be able to avoid `cargo_metadata`.
This patch also renames the new `cargo_metadata` feature to be `cargo-metadata` to be more consistent with our existing features and Rust feature naming in general.
This is on the path to …
=> Fix so cargo_metadata isn't a dependency without the cargo_metadata feature

CHANGELOG.md, Cargo.lock, fixtures/docstring-proc-macro/Cargo.toml, fixtures/docstring-proc-macro/tests/test_generated_bindings.rs, uniffi/Cargo.toml, uniffi/src/cli.rs, uniffi_bindgen/src/bindings/kotlin/test.rs, uniffi_bindgen/src/bindings/python/test.rs, uniffi_bindgen/src/bindings/ruby/test.rs, uniffi_bindgen/src/bindings/swift/test.rs, uniffi_bindgen/src/cargo_metadata.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs, uniffi_testing/src/lib.rs
This continues the cargo_metadata feature work but making the execution of cargo_metadata the resonsibility of the uniffi_bindgen callers rather that executing it implicitly. This means the CLI, which in-turn means the top-level uniffi crate also gets a `cargo-metadata` feature.
This reverts what we did to fix #2183 - by making `no_deps` the default, it means we will be unable to support reuse of UniFFI components, because it means we only support all components being in the same workspace. While this is a common use-case, it's not the only use-case we want to support. So grabbing all dependencies from cargo_metadata is again the default, but there's a new command-line option to avoid it.
It also replaces some of #2195.
@skeet70, does this make sense to you? Please feel free to bikeshed …
=> Move cargo_metadata execution out to the edges (ie, to the cli)

CHANGELOG.md
I'm hoping to do a 0.28.1 release and these would be good to have in it.
I also considered adding an entry for the work that @mgeisler has been doing, but I couldn't think of a good wording for that.  @mgeisler do you have any suggestions for changelog entry text?
=> Adding changelog entries for merges since 0.28.0

docs/manual/src/futures.md, docs/manual/src/tutorial/foreign_language_bindings.md, docs/manual/src/udl/ext_types.md
Had some minor doc tweaks stacked up, then saw @bendk's matrix notes re async cancellation, so might as well get em all in.
=> Future cancellation docs and other minor doc tweaks.

uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs
The generate_bindings docs mentioned wanting to expose a function that just finds ComponentInterface and config tables for each component and leaves the rest to the external bindings generator.  This is exactly what I want to use for uniffi-bindgen-gecko-js.
The `find_components` function was pretty much exactly what we wanted. I made some minor changes to it and exposed it as a pub function.
=> Expose the find_components function

Cargo.lock, uniffi_core/Cargo.toml
It seems like it's not used by `uniffi_core` but causes `camino` to be include as transitive dependency when crate relies on `uniffi`.
=> Remove unused camino dependency from uniffi_core.

fixtures/callbacks/tests/bindings/test_callbacks.kts, fixtures/callbacks/tests/bindings/test_callbacks.py, fixtures/callbacks/tests/bindings/test_callbacks.swift
Added test to ensure callback references are counted correctly. We are just now discovering that callback references are counted incorrect in v0.25.0 for Kotlin, C#, and Go.
=> Test callback lifetime

uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
There are some Rust docstrings (`///`) left in Swift templates, which hurts when we generate documentation for Swift. These places show up in the docs, whereas they should not. 
This PR replaces them with normal comments (`//`).
=> Remove docstrings in Swift templates

CHANGELOG.md, uniffi_bindgen/src/cargo_metadata.rs
See https://github.com/mozilla/uniffi-rs/pull/2175/files#r1749374986. That PR added a filter on `cargo_metadata`'s `is_lib`. While it makes sense to ignore non-library targets here, `is_lib` only returns `true` if the crate has the `lib` type, but not e.g. for `staticlib`, `cdylib` etc. In that case none of the targets match and the crate's `uniffi.toml` gets ignored.
=> Do not ignore uniffi.toml for crates without a lib type

uniffi/src/lib.rs
I want to use this in a CLI tool that I'm building.  The uniffi crate currently re-exports `generate_bindings`, but not `library_mode::generate_bindings`.
=> Re-export library mode items in uniffi

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.rb, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/python/gen_python/callback_interface.rs, uniffi_bindgen/src/bindings/python/gen_python/custom.rs, uniffi_bindgen/src/bindings/python/gen_python/enum_.rs, uniffi_bindgen/src/bindings/python/gen_python/error.rs, uniffi_bindgen/src/bindings/python/gen_python/external.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/object.rs, uniffi_bindgen/src/bindings/python/gen_python/record.rs, uniffi_bindgen/src/interface/visit_mut.rs, uniffi_bindgen/src/lib.rs
I hit this one when trying to upgrade application-services to 0.28.1.  It's kind of surprising that this is the first we're hearing of it, but I guess the Python bindings users are a minority.
=> Fix Python error name regression

uniffi_core/src/lib.rs
`.len()` on `str` already returns the length in bytes.
=> Do not use `.as_bytes().len()` on strings

uniffi_bindgen/src/macro_metadata/extract.rs
The `n_sect` field is 1-based with `0` meaning `NO_SECT` meaning the symbol is not present in any section in the library.  This change fixes the index mismatch.
Reference: https://github.com/aidansteele/osx-abi-macho-file-format-reference#nlist_64, 
The code was mostly working before because of the way we calculate the offset (https://github.com/mozilla/uniffi-rs/blob/2e3b59cf6dbcb46983028b08afc6e0ee51183f2e/uniffi_bindgen/src/macro_metadata/extract.rs#L106).  Because of this, even if we were off by one when picking the section, things would still work as long as the two sections involved lined up correctly.
Thanks to 0c0w3 for pointing this out and sending me the patch.
=> Fix for Mach-O symbol extraction

uniffi_macros/src/util.rs
In our setup, we've found that uniffi's MetadataBuffer generated by the proc macros were being embedded into our output binary, adding 4KB (we currently run on v0.26) of binary size per struct/impl/method. Starting from v0.27, this [increases to 16KB](https://github.com/mozilla/uniffi-rs/blob/69ecfbd7fdf587a4ab24d1234e2d6afb8a496581/uniffi_core/src/metadata.rs#L87).
In our case, this amounts to 2.6MB of superfluous binary space, or about 666 instances of metadata buffers being preserved in the binary. In v0.27, this would increase to 10.4MB.
The MetadataBuffer is kept around because it's referenced directly in the checksum method, which is needed at runtime, and rustc does not (always?) do constant evaluation for this specific method.
This diff ensures:
1. The checksum is computed at …
=> Force const evaluation to avoid leaking metadata buffers to the binary

Cargo.lock, uniffi_udl/Cargo.toml
Removes the unused `uniffi-testing` dependency from `uniffi-udl`, which also prevents using UniFFI in a cargoless setup as it's looking for the `CARGO` env var at compile time.
=> Remove unused dependency

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/src/traits.rs, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/keywords/kotlin/src/lib.rs, fixtures/keywords/rust/src/lib.rs, fixtures/metadata/src/tests.rs, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.py, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_bindgen/src/bindings/python/templates/Types.py, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_core/src/metadata.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/item.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/metadata.rs, uniffi_meta/src/reader.rs, uniffi_meta/src/types.rs
Record metadata for a struct implementing a trait.
```
#[uniffi::export]
impl MyTrait for MyObject { ... }
```
Previously worked as it ignored `MyTrait`. This adds new metadata to record it,
allowing foreign bindings to implement things like inheritance.
Includes Python generating an inheritance chain to reflect this relationship.
This will not generate correct code if a struct declares more than 1 trait,
and there's some undesirable re-wrapping when traits from these objects gets
passed back and forward, but seems to work surprisingly well.
On the path to #2196.
=> Record metadata for a struct implementing a trait.

fixtures/proc-macro/tests/bindings/test_proc_macro.py, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_bindgen/src/bindings/python/templates/wrapper.py
A followup to where I accidentally used these filters. It turns out the bindings were slightly inconsistent in how variant names were used. This fixes that and as a result, enums now have 2 `is_*` methods - the `is_VARIANT()` we thought and commented that we wrote, and the `is_variant()` we actually wrote.
=> Remove Python var_name and class_name filters

CHANGELOG.md, Cargo.lock, uniffi/Cargo.toml, uniffi_core/Cargo.toml, uniffi_core/src/ffi/rustcalls.rs, uniffi_core/src/ffi/rustfuture/future.rs, uniffi_core/src/ffi/rustfuture/scheduler.rs, uniffi_core/src/lib.rs, uniffi_macros/src/export/scaffolding.rs
@timboudreau hasn't gotten around to making a changelog entry for #2227 and I just merged #2210, so I went ahead and reworked his PR to use the new `ffi-trace` feature.  This totally removes the `log` dependency.
Instead we can use the `trace!` macro to log details about FFI calls. By default, it's compiled out but the `ffi-trace` feature can be used to enable it. These tracing printouts are only really useful for debugging failures when writing scaffolding/bindings code.
Addresses #2224 - even disabled logging can have overhead depending with some backends, and in very high frequency calls, generates unacceptable overhead and log-spam.
=> Remove log crate dependency

uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceImpl.kt, uniffi_bindgen/src/bindings/kotlin/templates/CustomTypeTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Interface.kt, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceImpl.py, uniffi_bindgen/src/bindings/python/templates/CustomType.py, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py, uniffi_bindgen/src/bindings/python/templates/ObjectTemplate.py, uniffi_bindgen/src/bindings/python/templates/RecordTemplate.py, uniffi_bindgen/src/bindings/python/templates/TopLevelFunctionTemplate.py, uniffi_bindgen/src/bindings/python/templates/Types.py, uniffi_bindgen/src/bindings/python/templates/macros.py, uniffi_bindgen/src/bindings/ruby/templates/RustBufferBuilder.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferStream.rb, uniffi_bindgen/src/bindings/ruby/templates/RustBufferTemplate.rb, uniffi_bindgen/src/bindings/swift/templates/BridgingHeaderTemplate.h, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceImpl.swift, uniffi_bindgen/src/bindings/swift/templates/CustomType.swift, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/Types.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
Mostly using `{ .. }`, `if let`, and `when Some with (x)` -> `when Some(x)`
I did this really just to play with some of the features and pattern matching always made me grumpy.
On the way I made some errors in the templates, and the error messages from rinja are *vastly improved* over askama - not only having very precise details about the error but often suggestions for how to fix (eg, with mismatched tags) - so thanks @GuillaumeGomez!
=> Update template pattern matching to leverage rinja.

CHANGELOG.md, uniffi_bindgen/src/macro_metadata/extract.rs
Symbol table entries store a 16-bit index for their section header.  If the index overflows 16-bits then it's stored in a separate section instead.
References:
- https://refspecs.linuxbase.org/elf/gabi4+/ch4.symtab.html
- https://docs.oracle.com/cd/E19683-01/817-3677/chapter6-94076/index.html
=> Fix metadata extraction for large ELF files (#2285)

uniffi_bindgen/src/bindings/swift/templates/wrapper.swift
more correctly handles swift6 data race concerns
fixes the specific issue in #2279, but may not be all of the changes needed or desired for swift6 compatibility
=> render global variable as a constant

uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/object.rs
All the callable types implement this, so let's add it to the trait.  I want to use this eventually for the Gecko JS bindings.
=> Add `Callable::ffi_func`

uniffi_core/src/ffi/rustbuffer.rs
The panic condition seems to be a mismatch between the foregin code and the size of `usize` on the platform.
=> Make panic section more precise for `RustBuffer::len`

CHANGELOG.md, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/keywords/kotlin/src/keywords.udl, fixtures/keywords/kotlin/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_meta/src/types.rs
Builds on #2204 which landed the metadata and Python support.
=> Kotlin classes can inherit from traits.

uniffi_bindgen/src/bindings/swift/mod.rs
Currently `swiftformat` is called to format generated Swift code. This PR adds a few more `swift-format` command candidates. Here are the new commands:
* `xcrun --find swift-format`. This command is available in Xcode 16. I expect it to be available in all future Xcode releases.
* `swift-format`. This command is the official command name. See [the README](https://github.com/swiftlang/swift-format?tab=readme-ov-file#command-line-usage).
* `swift format`. This command is a shorthand for `swift-format` (similar to how `git subcommand` is the same as `git-subcommand`)
=> Try different commands to run `swift-format`

uniffi_bindgen/src/scaffolding/templates/UdlMetadata.rs
Suggestion to ignore this rule, assuming the empty line and doc comments are there for a reason. If not, I happily remove the empty line or convert the doc comment to a normal comment
=> Ignore clippy::empty_line_after_doc_comments in generated code

uniffi_bindgen/src/bindings/swift/templates/Async.swift
Like many other types in the generated binding files, `UniffiForeignFutureTask` should be declared as `fileprivate` or `private`. It's currently causing conflicts when multiple libraries have public async functions.
=> Declare `UniffiForeignFutureTask` as fileprivate

docs/manual/src/swift/configuration.md, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
In Swift, all generated error types conform to `LocalizedError`. The implementation uses a compiler generated string, which is not an appropriate `LocalizedError` implementation.
This PR adds a new config to "uniffi.toml": `error_types_conform_to_localized_error`. When not set, its config value is `true`, which means existing code is not affected by this change.
I looked into adding unit tests, but couldn't find how. Happy to add some though, if anyone can point me to the right direction.
=> Add a configuration to allow removing `LocalizedError` conformation

uniffi/src/cli/mod.rs, uniffi_bindgen/src/macro_metadata/extract.rs
Alternative would be ":#" which is more concise, but will not give us tracebacks, and is the default if you return an Err from main()
Fixes #2324
=> Have the bindgen tool print the "debug" format of the error.

uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/interface/mod.rs
This PR solves #2340 Kotlin bug which is caused by a limit in JNA causing Kotlin generated code to throw `MethodTooLargeException` at runtime.
> [!NOTE]
> The name `MethodTooLargeException` is a red herring! This is super confusing since it is, in fact, not at all
> any method being too large, it is an **interface** being too large, specifically the `UniffiLib`.
> [!TIP]
> Apart from all unit tests passing locally:
> I've asserted that this change works. See [failing Kotlin (JVM) tests in Sargon CI before this fix](https://github.com/radixdlt/sargon/actions/runs/12163143241/job/33921636969) (many `jdk.internal.org.objectweb.asm.MethodTooLargeException` all over the place) and [see successful CI when I use my UniFFI fork with this …
=> Fix JNA bug `MethodTooLargeException` by splitting big `UniffiLib` interface

docs/manual/src/internals/async.md, mkdocs.yml
I've been meaning to document the async internals for a while now, here's my first draft.
=> Async internal docs

docs/manual/src/Upgrading.md, docs/manual/src/tutorial/foreign_language_bindings.md, docs/manual/src/types/remote_ext_types.md, docs/manual/src/udl/external_types.md, fixtures/ext-types/lib/src/ext-types-lib.udl, fixtures/proc-macro-no-implicit-prelude/src/proc-macro.udl, fixtures/uitests/src/typedef_extern.udl, fixtures/uitests/tests/ui/typedef_extern.rs, fixtures/uitests/tests/ui/typedef_extern.stderr, mkdocs.yml, uniffi_meta/src/group.rs, uniffi_meta/src/lib.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/collectors.rs, uniffi_udl/src/finder.rs
This consolidates how external types are expressed in UDL. Instead of
```
[External="crate_name"]
typedef extern MyEnum
[ExternalInterface="crate_name"]
typedef extern MyInterface
```
you would use:
```
[External="crate_name"]
typedef enum MyEnum
[External="crate_name"]
typedef interface MyInterface
```
See the docs and upgrading notes in this commit for more.
It also takes the opportunity to use Type::External far less often in uniffi_udl, instead using the actual type of the object.
=> Stop supporting `typedef extern`, `[ExternalInterface=...]` in UDL etc.

CHANGELOG.md, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
Builds on #2196, #2204 and #2297. Closes #2169.
=> Swift classes can inherit from traits

fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/lib/tests/bindings/test_imported_types.py, fixtures/ext-types/lib/tests/bindings/test_imported_types.swift, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/Async.swift, uniffi_bindgen/src/bindings/swift/templates/Helpers.swift, uniffi_bindgen/src/bindings/swift/templates/wrapper.swift, uniffi_bindgen/src/interface/callbacks.rs
Fixed a tricky case from Swift:  Because of it's C lineage, it doesn't have a way to run initialization code when the module is imported so instead it runs a one-time initialization function the first time a FFI call is run.  This system failed when external types were used before the external module ever made an FFI call.  I believe this is Swift only, but it might affect other C-like external bindings as well.
@crazytonyli thanks for the great test case for this, I shrunk it down to a mimimal test and added it to the existing fixture.  When I rebase your test suite on top of this and run it with `ISSUE_2343=1 cargo test --package uniffi-fixture-ext-types-sub-lib` it passes.   I don't think we need the all of the tests, but tell me if you think the other ones are still worth adding.
=> Initialize VTables for external types (#2343)

Cargo.lock, tools/publish-release.sh, uniffi_bindgen/src/interface/enum_.rs, uniffi_internal_macros/Cargo.toml, uniffi_internal_macros/src/lib.rs, uniffi_meta/Cargo.toml, uniffi_meta/src/lib.rs
Added `Enum::variant_discr_iter` and use that to implement `variant_discr`. This provides a simple and efficient way for other code to get a Vec of discriminants.
Renamed `uniffi_checksum_derive` -> `uniffi_internal_macros`.  This way we can use the same crate for future internal macros.
This is prep work for the bindings IR patch I'm hoping to land.
=> Bindgen refactors

CHANGELOG.md, docs/manual/src/Upgrading.md, docs/manual/src/types/custom_types.md, fixtures/ext-types/lib/src/ext-types-lib.udl, fixtures/uitests/tests/ui/typedef_extern.stderr, uniffi_udl/src/attributes.rs, uniffi_udl/src/finder.rs
Previously they were declared with the `External` attribute, but this mean UniFFI could not know the underlying type, leading to issues like #2025.
This PR does not however fix any such issues, it instead allows UniFFI metadata to carry enough information to fix in the future. This is primarily being done now to include this breaking change in with all other breaking changes we are making in the next release.
=> External custom types in UDL must use the [Custom] attribute

uniffi_bindgen/src/library_mode.rs, uniffi_meta/src/group.rs, uniffi_meta/src/lib.rs, uniffi_udl/src/finder.rs
This is a refactor of the group.rs converter/walker - it tries to split the "walking" from the "converting". It should have no functional changes, but should make it easier to perform different kinds of walking in the future.
=> Refactor group type converter

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ExternalTypeTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/python/templates/ExternalTemplate.py, uniffi_bindgen/src/bindings/python/templates/Types.py, uniffi_bindgen/src/interface/ffi.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/library_mode.rs, uniffi_meta/src/group.rs, uniffi_meta/src/types.rs
This is needed only by bindings and can be determined as they are generated. This makes truly external types easier to support.
=> Stop carrying the namespace around in ExternalFfiMetadata and Type.

uniffi_bindgen/src/interface/universe.rs, uniffi_meta/src/types.rs
For apparently historical reasons, we added, eg, `Type::U8` as a named type with name `u8`. This doesn't make sense for various reasons (these names are never actually treated as names, and if they were, they'd never be correct for all bindings).
This is just a cleanup to help simplify our ComponentInterface. It did however uncover two bugs:
* Type::iter_types neglected to include the CustomType builtin
* Type::get_name() returned None for a CallbackInterface even though they are named.
=> Don't add builtins and composite types as named types

uniffi_bindgen/src/bindings/swift/gen_swift/external.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/CallbackInterfaceTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
This means the calls are identical for internal and external types. Also writes the public functions for error types, which was the only named type without this support.
=> Swift always calls the public versions of lift and lower for named types

CHANGELOG.md, fixtures/ext-types/custom-types/src/lib.rs, fixtures/ext-types/custom-types/tests/bindings/test_guid.py, fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/lib/tests/bindings/test_imported_types.kts, fixtures/ext-types/lib/tests/bindings/test_imported_types.py, fixtures/ext-types/lib/tests/bindings/test_imported_types.swift, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceImpl.kt, uniffi_bindgen/src/bindings/kotlin/templates/CustomTypeTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceImpl.py, uniffi_bindgen/src/bindings/python/templates/NamespaceLibraryTemplate.py, uniffi_bindgen/src/bindings/python/templates/Types.py, uniffi_bindgen/src/bindings/python/templates/macros.py, uniffi_bindgen/src/bindings/swift/templates/Types.swift, uniffi_bindgen/src/interface/ffi.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/universe.rs, uniffi_meta/src/group.rs
The bindings all work when the Type::Custom has a different module_path and external bindings will need to do the same.
Fixes #2025
(There's no urgency at all with this, just wanted to get it up as I was happy to see how close things are getting to killing `Type::External`!)
=> CustomTypes are no longer turned into ExternalTypes

uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/object.rs
Was playing with external errors and stumbled on this.
I tried adding `iter_types` to `Callable`, but got a bit stuck with lifetimes, so here we are
=> Callables now iterate their "throws" type.

uniffi/Cargo.toml
Fix the following issue: "the package `<package>` depends on `uniffi`, with features: `uniffi_bindgen` but `uniffi` does not have these features."
=> Fix optional features in `uniffi` Cargo.toml

CHANGELOG.md, Cargo.lock, fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/lib/tests/bindings/test_imported_types.py, fixtures/ext-types/lib/tests/bindings/test_imported_types.swift, fixtures/ext-types/uniffi-one/Cargo.toml, fixtures/ext-types/uniffi-one/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/templates/ExternalTemplate.py, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
Almost - Swift+Python work. Kotlin doesn't work (#2392), however it works around failing simply by declining to render any functions with external errors, which seems reasonable for now.
=> Get external errors working for Swift and Python

CHANGELOG.md, uniffi/Cargo.toml, uniffi/src/lib.rs, uniffi_build/src/lib.rs
It's a direct re-export of uniffi_bindgen::generate_component_scaffolding and behind the 'bindgen' feature. For this reason it's not actually used in build scripts - they use 'uniffi::generate_scaffolding' which is correctly behind the 'build' feature.
We can't commit the "bindgen" feature to generating scaffolding, and it's kinda confusing, so let's kill it.
=> Remove uniffi::generate_component_scaffolding

uniffi_macros/src/setup_scaffolding.rs, uniffi_macros/src/util.rs, uniffi_meta/src/ffi_names.rs
The `nightly` version of the `mod_path()` function does not do the same thing as the one reading `Cargo.toml`.
We'll only ever get the crate name from `Cargo.toml`, but the `core::module_path!()` macro will return the module path, with components separated by `::`, as the Rust convention goes.
The problem is that the crate name is the first element of `core::module_path!()` macro, and the current impl does not consider that. This might not have been visible if tested from the `lib.rs` of a crate, since the `module_path == crate_name`, but UniFFI objects in nested modules will pose issues.
If the desire is to hold on to the full module path, then we could at least replace the `::` with `_` as otherwise `syn` complains that identifiers are not valid. Let me know if that's a better approach …
=> make `mod_path()` consistent with/without nightly feature

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/enum-types/src/lib.rs, fixtures/enum-types/tests/bindings/test_enum_types.kts, fixtures/enum-types/tests/bindings/test_enum_types.py, fixtures/enum-types/tests/bindings/test_enum_types.swift, uniffi_udl/src/converters/callables.rs
proc-macros already support this, as verified by new tests.
Fixes #1372
=> Allow UDL to define Enums with objects

CHANGELOG.md, docs/manual/src/kotlin/configuration.md, docs/manual/src/swift/configuration.md, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/wrapper.swift
This code started showing up in profiles, so my motivation to get this in our next release went up.
Kinda hate "omit" (it seems a somewhat obscure word?) so open to all bikesheds. Started with "skip_checksums", but then saw "omit" in swift so reluctantly went for consistency there.
Doesn't always avoid generating the checksum functions, but does avoid calling them.
Fixes #2255
=> Add config option to omit the checking of library checksums.

CHANGELOG.md, docs/manual/src/kotlin/configuration.md, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ObjectCleanerHelper.kt
Add option to kotlin configuration which allows disabling use of java.lang.ref.Cleaner class. This will keep the generated code compatible with Java 8
=> Allow disabling java.lang.ref.Cleaner

CHANGELOG.md, uniffi_core/src/ffi/rustfuture/future.rs, uniffi_core/src/ffi/rustfuture/mod.rs
Fixes #2417.
This PR introduces a marker trait for the Futures that uniffi supports.
This is a small refactor which tidies up 7 places where it was used:
```rust
pub trait FutureResult<T, E>: Future<Output = Result<T, E>> {}
#[cfg(not(target_arch = "wasm32"))]
impl<T, F, E> FutureResult<T, E> for F where F: Future<Output = Result<T, E>> + Send + 'static {}
```
It also adds a second `impl`, only active during `wasm32`:
```rust
// `Promise`s cannot be sent to or from WebWorkers, but `JsValue` is not `Send`.
#[cfg(target_arch = "wasm32")]
impl<T, F, E> FutureResult<T, E> for F where F: Future<Output = Result<T, E>> + 'static {}
```
I am not sure:
- naming: should it be `RustFutureResult` or `UniffiFutureResult` or … something else?
- how to introduce wasm32 into the existing CI to verify …
=> Relax `Send` bound for `Future` for wasm32 targets.

uniffi_bindgen/src/bindings/python/templates/ExternalTemplate.py
This is purely aesthetic and has no functional changes.
=> Fixup comments and whitespace in generated Python code.

.cargo/config.toml, Cargo.lock, uniffi_internal_macros/Cargo.toml, uniffi_meta/Cargo.toml
This is a newish crate, and wasn't added to the list of crates where we bump the version. I updated the list and ran `cargo release-backend-crates`.
=> Add uniffi-internal-macros release-backend-crates list

uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
This method’s comments indicates it shouldn’t be public API, so let’s exclude it from documentation generation.
=> Hide `init(unsafeFromRawPointer)` from docs

CHANGELOG.md, uniffi/Cargo.toml
This is a WIP, but I expect something like this might be necessary to use uniffi-bindgen in m-c to avoid the many deps required by the clap `color` feature. An alternative would be to duplicate the cli parsing in m-c and avoid that dependency there.
@badboy @bendk, thoughts?
=> Remove clap color feature

uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift
When the `omit_localized_error_conformance` configuration (added in https://github.com/mozilla/uniffi-rs/pull/2319) is turned on, the `Error` conformance was also removed because it was previously implied by the `LocalizedError`.
This PR makes sure error types in Swift bindings always conform to `Swift.Error`, regardless of whether they conform to `LocalizedError`.
=> Error types in the swift binding conforms to the Error protocol

uniffi_bindgen/src/cargo_metadata.rs, uniffi_bindgen/src/lib.rs
This is a way to get just the path to the TOML file, without trying to parse it.  I want to use this in some of my bindings IR experiment.
=> Adding BindgenCrateConfigSupplier::get_toml_path

fixtures/ext-types/custom-types/tests/bindings/test_custom_types.py, fixtures/ext-types/custom-types/tests/test_generated_bindings.rs
The name mismatch has tricked me more than once...
=> Legacy test filename test_guid.py renamed to test_custom_types.py

docs/manual/src/Upgrading.md
We forgot to include this in the Upgrading doc, but I'm pretty sure it's a new requirement.  At least that's what it seemed like when I tried upgrading `places` to the new UniFFI.
=> Upgrading doc fix

CHANGELOG.md, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py
=> Python: fix using Vecs and other composite types in tuple enums.

uniffi_core/src/ffi/rustfuture/future.rs, uniffi_core/src/ffi/rustfuture/mod.rs, uniffi_core/src/ffi/rustfuture/tests.rs
These changes will reduce the monomorphization of the futures code, resulting in a reduction of the binary size.
In my case, the binaries for android targets have become 100/200kb smaller.
=> core: reduce monomorphization of the futures code

README.md
The original UniFFI KMP bindings project is forked to another repo.
@benkuly
=> Update KMP bindings project link

fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/lib/tests/bindings/test_imported_types.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
`<ErrorType>.lift` Swift functions are private API and are referenced in `errorHandler: {{ e|ffi_error_converter_name }}.lift`. That would cause compiling issues in Swift bindings of a crate that uses external error types in async functions.
The first commit reproduces the issue, and the second commit fixes the problem.
=> Fix compiling issue in Swift bindings for async throw functions

fixtures/ext-types/lib/tests/bindings/test_imported_types.swift
@crazytonyli merged a change from me, but CircleCI wasn't running in his PR so we didn't catch that this line got left out.
=> Fix test_imported_types.swift

uniffi_bindgen/src/scaffolding/templates/Checksums.rs, uniffi_bindgen/src/scaffolding/templates/ReexportUniFFIScaffolding.rs, uniffi_bindgen/src/scaffolding/templates/UdlMetadata.rs
Hey,
I know, I know - Rust 2024 just dropped, and I’m not trying to rush anything. But after upgrading to the Rust 2024 edition, I ran into the following build error:
```rust
error: unsafe attribute used without unsafe
--> /Users/martinmose/project/target/debug/build/project_shared-0c37e55cf0c6dc4f/out/project_shared.uniffi.rs:96:3
|
96 | #[no_mangle]
|   ^^^^^^^^^ usage of unsafe attribute
|
help: wrap the attribute in `unsafe(...)`
|
96 | #[unsafe(no_mangle)]
|   +++++++         +
```
I found this [Unsafe Attributes](https://doc.rust-lang.org/edition-guide/rust-2024/unsafe-attributes.html)
This seems like a simple fix - just wrapping `#[no_mangle]` in `#[unsafe(...)]`. But maybe there is something I’m unaware of?
It looks like it fixes my upgraded Rust project at least 😅
=> fix: `#[no_mangle]` error in Rust 2024 Edition

uniffi_macros/src/export/callback_interface.rs
Without these changes, there are new false positives for `missing_docs` when running `cargo clippy`.
I have not added tests for the changes, as I saw no other example for testing on this functionality.
I have not added an entry to the changelog as it is really a minor fix.
Any feedback/suggestions are very welcome!
---
Example code:
```rust
//! Crate documentation
#![warn(missing_docs)]
uniffi::setup_scaffolding!();
/// Documentation is here
#[uniffi::export(with_foreign)]
pub trait MyTrait: Send + Sync {}
```
Observed behavior:
```
cargo clippy --all-targets --all-features 
Checking missing_uniffi_docs v0.1.0 (/home/theo/tmp/missing_uniffi_docs)
warning: missing documentation for a struct
--> src/lib.rs:6:1
|
6 | #[uniffi::export(with_foreign)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: …
```
=> Fix false positive for missing_docs for trait impl

CHANGELOG.md, fixtures/coverall/src/coverall.udl, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.kts, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/coverall/tests/bindings/test_coverall.rb, fixtures/coverall/tests/bindings/test_coverall.swift, uniffi_bindgen/src/bindings/kotlin/templates/Types.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
Fixes #2467.
- Made `Disposable.destroy` handle list or maps of interfaces.
- Replaced `.filterIsInstance` in `Disposable.destroy` with a plain for loop, as `.filterIsInstance` allocates an ArrayList.
- Made macro `destroy_fields` call `Disposable.destroy` only once.
- Modified `SimpleDict` in fixture `coverall` to test list/map interface deallocation.
=> Fix Kotlin interfaces in Lists and Maps being not destroyed

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/manual/src/swift/configuration.md, fixtures/swift-link-frameworks/Cargo.toml, fixtures/swift-link-frameworks/build.rs, fixtures/swift-link-frameworks/src/lib.rs, fixtures/swift-link-frameworks/src/swift-link-frameworks.udl, fixtures/swift-link-frameworks/uniffi.toml, uniffi/src/cli/swift.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/ModuleMapTemplate.modulemap
When including another static library in the form of an xcframework (C++/C), the resulting Rust library also takes a dependency on the frameworks that are linked as part of that xcframework. This change allows specifying the frameworks so that this contract is upheld.
=> uniffi_bindgen: Add support for specifying extra link frameworks in generated modulemap file

CHANGELOG.md, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/object.rs, uniffi_macros/src/setup_scaffolding.rs, uniffi_macros/src/util.rs
As noted in #2459 and #2475, the `uniffi_reexport_scaffolding!` macro doesn't work in Rust 2024.
=> Allow `uniffi_reexport_scaffolding!` macro to work in Rust 2024

uniffi_bindgen/src/bindings/swift/mod.rs
This makes it easier for consumers to construct these, when they only care about some of the fields.
=> Derive Default for SwiftBindingsOptions

uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceImpl.py
The change to `ffi_type_label` from
`https://github.com/mozilla/uniffi-rs/pull/2385` also needs to be applied here.
See https://github.com/mozilla/uniffi-rs/issues/2508 for details.
I didn't add a test case for this one since I'm planning to revive https://github.com/mozilla/uniffi-rs/pull/2348 and start a whole new set of test fixtures soon.  I can definitely add one though if you think it's needed.
=> Python: fix `ffi_default_value`

.circleci/config.yml, tools/requirements_docs.txt
This PR bumps 3 Material for MkDocs-related dependencies, in the hope to enable the search bar as envisioned by #2509.
I also took the liberty of fixing a typo in naming of a step the CI workflow.
I built the site locally using both the following commands:
```shell
mkdocs serve
mike deploy next
```
And both render the search bar well.
=> Update docs-related Python dependencies (follow up to #2509)

uniffi_bindgen/src/bindings/swift/templates/ModuleMapTemplate.modulemap
The generated Swift header file uses stdbool, stddef and stdint. In certain build environments, the Swift module is unable to be generated due to these headers being missing from the modulemap dependencies.
=> Add builtin headers to modulemap

.circleci/config.yml, Cargo.lock, Cargo.toml, docs/manual/src/wasm/configuration.md, fixtures/wasm-unstable-single-threaded/.cargo/config.toml, fixtures/wasm-unstable-single-threaded/Cargo.toml, fixtures/wasm-unstable-single-threaded/README.md, fixtures/wasm-unstable-single-threaded/src/lib.rs, mkdocs.yml, uniffi/Cargo.toml, uniffi_core/Cargo.toml, uniffi_core/src/ffi/rustfuture/future.rs, uniffi_core/src/ffi/rustfuture/mod.rs, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/ffi_converter_traits.rs, uniffi_macros/Cargo.toml, uniffi_macros/src/object.rs
This is a followup to #2417, #2418.
This PR provides a [test](https://github.com/mozilla/uniffi-rs/blob/96a3a8de28cd84f233cac5f767f0f7273d23d522/fixtures/wasm-arc-futures/src/lib.rs) which was failing to compile, and the fix.
=> Relax `Send` bound for objects containing `Future`s for wasm32 targets

uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_core/Cargo.toml, uniffi_internal_macros/Cargo.toml, uniffi_macros/Cargo.toml, uniffi_meta/Cargo.toml, uniffi_pipeline/Cargo.toml, uniffi_testing/Cargo.toml, uniffi_udl/Cargo.toml
I was reading source code on docs.rs and realized that the feature was not enabled, so here it is. :)
Enabling this feature makes your source code pages generate links on items so you can jump to where they're defined.
You can this feature in action in [`syn`](https://docs.rs/syn/latest/src/syn/lib.rs.html#986-1010) for example.
=> Build docs.rs documentation with rustdoc "jump to definition" feature enabled

Cargo.lock, fixtures/wasm-unstable-single-threaded/Cargo.toml, fixtures/wasm-unstable-single-threaded/src/lib.rs, uniffi_macros/src/export/callback_interface.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/object.rs, uniffi_macros/src/util.rs
Fixes #2511 
This is a followup for #2418 and #2497.
It does not add anything fundamentally new, just doing the same as the other PRs but for `ForeignFuture`s.
=> wasm-unstable-single-threaded: Relax `Send` for `async_trait` for `ForeignFuture`.

docs/manual/src/internals/bindings_ir.md, docs/manual/src/internals/bindings_ir_pipeline.md, uniffi_pipeline/src/node.rs
Lists need to be separated by a blank line from other paragraphs to be rendered correctly.
=> docs: Fixing typos and list indentation

docs/manual/src/internals/bindings_ir_pipeline.md, uniffi_bindgen/src/pipeline/general/callback_interfaces.rs, uniffi_bindgen/src/pipeline/general/checksums.rs, uniffi_bindgen/src/pipeline/general/enums.rs, uniffi_bindgen/src/pipeline/general/ffi_async_data.rs, uniffi_bindgen/src/pipeline/general/ffi_functions.rs, uniffi_bindgen/src/pipeline/general/ffi_types.rs, uniffi_bindgen/src/pipeline/general/mod.rs, uniffi_bindgen/src/pipeline/general/modules.rs, uniffi_bindgen/src/pipeline/general/nodes.rs, uniffi_bindgen/src/pipeline/general/objects.rs, uniffi_bindgen/src/pipeline/general/records.rs, uniffi_bindgen/src/pipeline/general/rust_buffer.rs, uniffi_bindgen/src/pipeline/general/rust_future.rs, uniffi_bindgen/src/pipeline/general/sort.rs, uniffi_bindgen/src/pipeline/general/type_nodes.rs, uniffi_bindgen/src/pipeline/initial/mod.rs, uniffi_pipeline/src/node.rs
This were the result of me implementing the Python bindings using the new pipeline system.  There were a handful of things I realized I needed/wanted there that didn't come up when I was implementing the JS bindings.
Add `FfiTypeNode`. I didn't originally have this as part of the general pipeline, since it wasn't needed there.  However, virtually all language pipelines are going to want to add it so we may as well do it in shared code.
Determine enum discriminants for the bindings. This uses basically the same algorithm as from `ComponentInterface`. The one difference is that for enums without a specified `repr`, this calculates the smallest integer width needed to store the variants.
I used a new pipeline technique for the enum discriminents: the old/optional `discr` field gets renamed …
=> General pipeline updates

uniffi_bindgen/src/pipeline/general/callback_interfaces.rs
Adding the module name to the exported FFI functions. So that we can make unique trait interfaces work on the JS side.
=> Uniffi 309 unique trait interfaces

uniffi_core/src/ffi/handle.rs, uniffi_core/src/ffi/rustcalls.rs, uniffi_core/src/ffi/rustfuture/future.rs, uniffi_core/src/ffi/rustfuture/mod.rs, uniffi_core/src/ffi/rustfuture/tests.rs, uniffi_macros/src/setup_scaffolding.rs
(This is based on top of https://github.com/mozilla/uniffi-rs/pull/2574.  Let's merge that one first.  This PR is just for the second commit).
#2406 made `RustFuture` is store a `Box<dyn Future>` rather than a concrete type.  That change was focused on binary size, but this also gives us an opportunity to simplify some other code:
* `RustFuture` and `WrappedFuture` only need 1 generic parameter: the FFI return type.
* We can drop the entire `RustFutureFfi` trait and just use `RustFuture` directly.
* The Arcs we pass across the FFI now store `RustFuture` directly, which is `Sized`.  No more need for an double-arc wrapping.
* We don't need to implement `Send` for `WrappedFuture`, which didn't seem correct to me.  This makes it more likely that Rust can catch errors in the future as we …
=> Simplify RustFuture to only have 1 generic param

uniffi/Cargo.toml
I accidentally introduced a filename collision with my previous change. It turns out, `cargo doc` doesn't like having two binaries in one project with the same name, which caused it to raise an error when I tried to generate the documentation, conflicting `uniffi/uniffi-bindgen.rs` with `examples/app/uniffi-bindgen-cli/uniffi-bindgen.rs`. To fix it, I have marked the binary with `doc = false`.
=> Fix a documantation output filename conflict

uniffi_bindgen/src/bindings/python/pipeline/nodes.rs, uniffi_bindgen/src/pipeline/general/callback_interfaces.rs, uniffi_bindgen/src/pipeline/general/checksums.rs, uniffi_bindgen/src/pipeline/general/nodes.rs, uniffi_bindgen/src/pipeline/general/rust_future.rs, uniffi_bindgen/src/pipeline/general/sort.rs
This simplifies the dupe removal and I think it'll make future work easier.  For example, this would make  it easier to factor out common FFI definitions into a shared module.
=> Use IndexSet for FFI definitions

uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/python/pipeline/nodes.rs, uniffi_bindgen/src/bindings/python/templates/InterfaceTemplate.py, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/pipeline/general/nodes.rs, uniffi_bindgen/src/pipeline/general/objects.rs
It's becoming apparent that the `Vec<UniffiTrait>` is a pita and this seems in the spirit of pipelines.
=> Flatten `UniffiTrait` objects into individual methods in the pipeline

fixtures/uitests/tests/ui/trait_methods_no_trait.stderr, uniffi_bindgen/src/library_mode.rs, uniffi_bindgen/src/pipeline/initial/mod.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/utrait.rs, uniffi_macros/src/lib.rs
This means we don't have special handling in various places to filter out these dupes, which causes confusion and complexity.
It does mean there's a new macro used here - `export_for_udl_derive()` is similar to `export_for_udl`, but is used whenever `udl_derive()` or `udl_remote()` is going to be used on the object. This macro keeps the input tokens as they need to be seen by `udl_derive()` etc.
=> Avoid emitting duplicate metadata for uniffi traits.

CHANGELOG.md, Cargo.lock, Cargo.toml, fixtures/gh-2600/Cargo.toml, fixtures/gh-2600/README.txt, fixtures/gh-2600/src/lib.rs, fixtures/gh-2600/tests/bindings/test_gh_2600.kts, fixtures/gh-2600/tests/bindings/test_gh_2600.py, fixtures/gh-2600/tests/bindings/test_gh_2600.swift, fixtures/gh-2600/tests/test_generated_bindings.rs, fixtures/gh-2600/uniffi.toml, uniffi_macros/src/object.rs
Before we were calling `Arc::increment_strong_count` with a `*const ::std::ffi::c_void`, rather than the correct type.  I'm not sure why but this sometimes causes objects to be dropped early (#2600).
=> Cast object pointers to the correct type in `clone`/`free`

Cargo.lock, Cargo.toml, fixtures/gh-2600/Cargo.toml, fixtures/gh-2600/README.txt, fixtures/gh-2600/src/lib.rs, fixtures/gh-2600/tests/bindings/test_gh_2600.kts, fixtures/gh-2600/tests/bindings/test_gh_2600.py, fixtures/gh-2600/tests/bindings/test_gh_2600.swift, fixtures/gh-2600/tests/test_generated_bindings.rs, fixtures/gh-2600/uniffi.toml
Copied this test from the release-v0.29.x branch. I also generalized it a bit after figuring out a little more about the bug. The bug triggers on any type that's aligned to 32 bytes (probably more as well, but I didn't test).  Now the test uses that rather than the x86-specific 256 bit int type.
=> Porting fixture/gh-2600 to main

fixtures/ext-types/lib/tests/bindings/test_imported_types.kts, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/ExternalTypeTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
Fixes: #2392
This PR adds support for throwing external Kotlin errors by generating additional "delegating" error handlers in `ExternalTypeTemplate.kt`. If a function throws an external error, the "delegating" error handler is passed to `uniffiRustCallWithError` or `uniffiRustCallAsync` instead of the original one.
=> Support throwing external Kotlin error

CHANGELOG.md, fixtures/coverall/src/lib.rs, fixtures/coverall/tests/bindings/test_coverall.py, fixtures/futures/tests/bindings/test_futures.py, uniffi_bindgen/src/bindings/python/pipeline/types.rs, uniffi_bindgen/src/bindings/python/templates/InterfaceTemplate.py, uniffi_bindgen/src/bindings/python/templates/Module.py, uniffi_bindgen/src/bindings/python/templates/Protocol.py
=> Python: methods now have typing annotations for return values.

fixtures/metadata/src/tests.rs, fixtures/trait-methods/src/lib.rs, fixtures/trait-methods/src/trait_methods.udl, fixtures/uitests/tests/ui/trait_methods_no_trait.rs, fixtures/uitests/tests/ui/trait_methods_no_trait.stderr, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/pipeline/general/callable.rs, uniffi_bindgen/src/pipeline/general/callback_interfaces.rs, uniffi_bindgen/src/pipeline/general/checksums.rs, uniffi_bindgen/src/pipeline/general/ffi_functions.rs, uniffi_bindgen/src/pipeline/general/mod.rs, uniffi_bindgen/src/pipeline/general/nodes.rs, uniffi_bindgen/src/pipeline/general/objects.rs, uniffi_bindgen/src/pipeline/general/uniffi_traits.rs, uniffi_bindgen/src/pipeline/initial/from_uniffi_meta.rs, uniffi_bindgen/src/pipeline/initial/nodes.rs, uniffi_bindgen/src/scaffolding/templates/EnumTemplate.rs, uniffi_bindgen/src/scaffolding/templates/ObjectTemplate.rs, uniffi_bindgen/src/scaffolding/templates/RecordTemplate.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/utrait.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/converters/enum_.rs, uniffi_udl/src/converters/interface.rs, uniffi_udl/src/converters/mod.rs
This is towards Enums and Records exposing `Debug`, `Eq` etc. None of the bindings support it yet, but the tests show how this is setup for the scaffolding.
(I do have all the bindings supporting it in [here](https://github.com/mhammond/uniffi-rs/tree/all-uniffi-traits) though :)
=> Metadata for Enums and Records carries uniffi-trait info.

uniffi_bindgen/src/macro_metadata/extract.rs
In https://github.com/mozilla/uniffi-rs/pull/2640/ I speculated that maybe external bindings would want to roll their own metadata-extraction functions.  I'm not sure if it'll work for that case, but it seems like a good thing in general.
Making these functions `pub` is a step in that direction.  I could see external bindings code try their specialized `extract_from_foo` function first, then fallback to calling `extract_from_bytes` to see if one of the standard cases works.
=> Make metadata extraction functions pub

uniffi_bindgen/src/bindings/python/templates/CallbackInterfaceImpl.py
=> Avoid shadowing param names with internal variabes in Python, fixes #2628

uniffi/Cargo.toml, uniffi/src/cli/swift.rs, uniffi/uniffi-bindgen-swift.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/library_mode.rs, uniffi_bindgen/src/loader.rs, uniffi_bindgen/src/macro_metadata/mod.rs, uniffi_meta/src/group.rs, uniffi_meta/src/lib.rs
I'm opening this based on our discussion in https://github.com/mozilla/uniffi-rs/pull/2640.
@paxbun can you take a look  at the new Swift code and tell me if you think this would work for Gobley?
---
This is a new way for binding generators to load the CIs, Configs, metadata, etc.  I'm hoping that this can replace the `generate_bindings` and `generate_external_bindings` functions, as well some other functions like `library_mode::find_components`.
The goal for the new design is to let bindings generators drive the process instead of a function like `generate_external_bindings`.  The advantage of this is that it's easier to customize and we don't need to keep adding new hook methods.  It also feels simpler overall to me.  See https://github.com/mozilla/uniffi-rs/pull/2640 for a discussion …
=> Adding BindgenLoader

fixtures/ext-types/lib/src/lib.rs, fixtures/ext-types/sub-lib/src/lib.rs, uniffi_bindgen/src/interface/mod.rs
Fixes #2636 by making `ComponentInterface::is_name_used_as_error` return `true` for unused external errors using `all_component_interfaces` introduced in #2612. `self.errors.contains(name) ||` is still required for cases where library mode is not used, which is the reason why 422442381d3a21764eeca0de418655b2914a2d33 has failed.
`self.error.insert` happens when the error enum itself is defined in the crate, or it is thrown from a function or a constructor. Since external errors are not defined in the crate, they are not registered through `self.error.insert` when it is not used. The check to determine whether an enum is an error requires an `EnumMetadata`, but `EnumMetadata` for external errors used in a variant of an enum is not being provided to CI.
=> Fix `is_name_used_as_error` returning `false` for unused external errors

uniffi_bindgen/src/bindings/python/filters.rs, uniffi_bindgen/src/bindings/python/templates/Module.py
Python 3.9+ use `from . import module`, and `import .module` throws `SyntaxError`.
=> Fix python relative import

uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt
Eg, when testing coverall I saw about 250 blank lines. This trivial patch removes them.
=> Prevent kotlin generating hundreds of blank lines

uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ErrorTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
In Swift, extension protocol conformance cannot be made public – it’s tied to the original module (and conformance can’t be re-declared later).
This has implications for cases where types from this library are part of the public API of another library.
For example, in the following setup:
```
+-----------------------------------------------------------+
| Application                                               |
|  (calls public API of FooLibrary)                         |
|                                                           |
|  +---------------------------------------------+          |
|  | FooLibrary (Library A)                      |          |
|  |  - Exports select Rust types                |          |
|  |  - Associated some free-floating functions  |          |
|  | …
```
=> Use root object protocol conformance

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/NamespaceLibraryTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt
According to https://github.com/java-native-access/jna/blob/master/www/DirectMapping.md direct mapping can improve performance substantially, maybe even that of custom JNI. Given we know all methods it's easy to switch it all over.
Note that I have not run any actual benchmark to see how it helps.
=> Kotlin: Switch to JNA direct mapping

uniffi_bindgen/src/bindings/python/pipeline/external_types.rs, uniffi_bindgen/src/pipeline/general/ffi_async_data.rs
The issue was that we were using the same name for both the local and external types, which lead to the one of them being lost when they were de-duped.
=> Python: Fix async functions that return external types (#2659)

uniffi_macros/src/export/scaffolding.rs
Added/clarified `trace!` usage during a scaffolding call.
=> Better FFI tracing
