examples/arithmetic/src/arithmetic.idl, examples/arithmetic/src/lib.rs, examples/arithmetic/tests/bindings/test_arithmetic.kts, examples/arithmetic/tests/bindings/test_arithmetic.py, examples/arithmetic/tests/bindings/test_arithmetic.swift, examples/geometry/src/lib.rs, examples/sprites/src/lib.rs, examples/todolist/src/lib.rs, uniffi/src/scaffolding.rs, uniffi/src/support/mod.rs
This should fix #34 and #35, although I've only added tests for the former.
There's a bunch of `pub`-changes here which I will explain in a comment, and which I'm not wedded to if they don't seem worthwhile. But I discovered a neat thing that I wanted to try out for the rust scaffolding.
=> Fix up support for booleans

examples/todolist/src/lib.rs, examples/todolist/src/todolist.idl, examples/todolist/tests/bindings/test_todolist.kts, examples/todolist/tests/bindings/test_todolist.swift, uniffi/src/scaffolding.rs
=> Fixes string sequences

uniffi/src/interface/mod.rs
Separates attribute parsing from #31
=> Adds attribute parsing

examples/rondpoint/src/lib.rs, examples/rondpoint/src/rondpoint.idl, examples/rondpoint/tests/bindings/test_rondpoint.kts, examples/rondpoint/tests/bindings/test_rondpoint.swift, uniffi/src/bindings/kotlin/templates/RustBufferHelpers.kt
Fixes https://github.com/mozilla/uniffi-rs/issues/35
=> Bool complete support

examples/geometry/src/geometry.idl, examples/geometry/src/lib.rs, examples/geometry/tests/bindings/test_geometry.swift, uniffi/src/bindings/kotlin/gen_kotlin.rs, uniffi/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi/src/bindings/python/gen_python.rs, uniffi/src/bindings/python/templates/RecordTemplate.py, uniffi/src/bindings/swift/templates/RecordTemplate.swift
This small PR mangles record members names in to the language specific variant.
It came about due to early feedback from #178.
=> Camel case for record members

.vscode/settings.json, examples/sprites/src/lib.rs, examples/sprites/src/sprites.idl, uniffi/src/interface/mod.rs, uniffi/src/templates/macros.rs
This PR add support to argument reference in Rust code
Closes #4
=> Support argument reference in Rust code

examples/sprites/src/sprites.idl, uniffi/src/interface/mod.rs
I'm not sure if it's the most efficient way to do this
Suggestions are welcome!
=> Error on duplicate attributes

examples/rondpoint/src/lib.rs, examples/rondpoint/src/rondpoint.idl, examples/rondpoint/tests/bindings/test_rondpoint.kts, examples/rondpoint/tests/bindings/test_rondpoint.swift, uniffi/Cargo.toml, uniffi/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt
Fixes https://github.com/mozilla/uniffi-rs/issues/227
=> Implement Liftable/Lowerable for all number primitives

examples/rondpoint/src/lib.rs, examples/rondpoint/src/rondpoint.idl, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
=> Properly snake-case Swift bindings

uniffi_bindgen/src/bindings/kotlin/templates/RustBufferHelpers.kt, uniffi_bindgen/src/bindings/swift/templates/RustBufferHelper.swift
=> Add missing primitives support

docs/manual/src/tutorial/Prerequisites.md, docs/manual/src/tutorial/Rust_scaffolding.md
Now that @rfk has published uniffi on crates.io we can do that.
=> Remove git dependencies

examples/README.md
=> Update examples readme for the latest command-line interface.

docs/manual/src/tutorial/Rust_scaffolding.md, uniffi/Cargo.toml, uniffi/src/ffi/foreignbytes.rs, uniffi/src/ffi/rustbuffer.rs, uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/interface/mod.rs, uniffi_build/Cargo.toml
Fixes https://github.com/mozilla/uniffi-rs/issues/290.
=> Release v0.2.0

uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml
Somehow my commit missed a couple of the Cargo.toml files that I had changed.  So this wants to land there too...
CC @linacambridge
=> Finish the fix for #301

uniffi/src/testing.rs, uniffi_bindgen/src/lib.rs, uniffi_bindgen/src/main.rs, uniffi_build/src/lib.rs
Fix https://github.com/mozilla/uniffi-rs/issues/304.
=> Allow the config path to be passed to uniffi-bindgen

uniffi_bindgen/src/lib.rs
This fixes some bustage on CI on current `main`. Also adds a test for completeness.
=> Consolidate and fix logic for guessing the crate root.

docs/manual/src/idl/interfaces.md, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
Fixes #315 
Adds simple bindings for kotlin and swift to add interfaces to allow for mocking, testing and previewing.
=> Adds public protocols/interfaces for Objects.

docs/manual/src/tutorial/Rust_scaffolding.md, examples/arithmetic/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
=> Prepare v0.4.0

uniffi_bindgen/src/bindings/kotlin/templates/RustBufferTemplate.kt
I need to understand better what's happening here, but pushing this for visibility.
@jhugman please let me know if this fixes the issue you were having with long strings in callbacks.
=> Flush struct memory when writing to a RustBuffer.

README.md, examples/arithmetic/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, release.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
I made a `v0.6.0` release using `cargo release`, and even with some rough edges it was still a big improvement over doing it manually! I've added some docs as part of this commit.
=> Release v0.6.0

uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/types.rs
Fixes #373.
Introduces more structure around the `Attributes` struct.
=> Refactor attributes to be validate IDL

uniffi/src/ffi/foreigncallbacks.rs
=> Fixup deprecated compare_and_swap

examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/threadsafe/Cargo.toml, examples/todolist/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
=> (cargo-release) version 0.8.0

uniffi_bindgen/src/interface/mod.rs
If there is a syntax error in the IDL, the error message offers almost zero clues.
This patch helps, but not by as much as would be ideal - while it shows what's the parser thinks is "remaining to be parsed", in reality the entire "block" being parsed it returned. For example, if there's a syntax error anywhere in an "interface" definition, the entire interface is reported as being remaining. This is still a little useful though - at least it narrows the problem down a little.
(while this makes it only marginally better than the status quo, that status quo is bad enough we might as well take this improvement IMO, but I don't feel that strongly)
=> Get marginally better parse errors

docs/manual/src/tutorial/Rust_scaffolding.md
I was testing some local changes on a-s and realized this documentation was missing.
=> Document the `builtin-bindgen` feature.

CHANGELOG.md, examples/README.md, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
This is the result from the discussion in Issue https://github.com/mozilla/uniffi-rs/issues/471
=> Change swift and kotlin bindings to be mutable by default

uniffi_bindgen/src/bindings/gecko_js/gen_gecko_js.rs, uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/bindings/mod.rs, uniffi_bindgen/src/bindings/python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/tests.rs, uniffi_bindgen/src/bindings/ruby/mod.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/interface/literal.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/finder.rs, uniffi_bindgen/src/lib.rs, uniffi_macros/src/lib.rs
Nightly clippy seems to have some helpful new lints about needless
borrows, this applies the automated fixes.
=> Apply Nightly Clippy fixes

uniffi_bindgen/src/interface/types/finder.rs
This particular test has been a PIMA; the bigger it gets, the further the test code gets from the UDL under test, and merge conflicts always bite here. I think this is short term pain (ie, conflicts) for longer term gain. Full disclosure - it has lost the check for the total count of the "known types", but I think that's OK (and avoids me ~explaining~ working out how `String` ended up there once `typedef` aliases land 😅
=> Refactor the tests for type finding in valid UDL

docs/manual/src/Motivation.md, docs/manual/src/SUMMARY.md, docs/manual/src/internals/design_principles.md
**[Rendered View](https://github.com/mozilla/uniffi-rs/blob/c6745aa0f4a9e80f25901a4874ef465b07fe1a23/docs/manual/src/internals/design_principles.md)**.
These are some of the things that I've been implicitly considering when building UniFFI, and I figured it would probably be useful to have them more explicit. It's also a great opportunity for us to decide that we don't agree with some of the things I've said here, and work on a replacement!
=> Document some high-level design principles of the tool.

README.md, docs/contributing.md
(considered renaming "matrix" to "element" because that's what my tab title seems to be, and I'm still confused what the difference is, but wiki.m.o still says "matrix", so 🤷 )
=> uniffi is all grown up so gets its own matrix room

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/wrapped.rs, uniffi_bindgen/src/bindings/swift/gen_swift/wrapped.rs
This fixes some fallout after merging #1091
=> Fixing some import issues after the last commit.

README.md
=> Added etymology and pronunciation guide.

docs/release-process.md
Things I learnt doing a point release. The git instructions can probably be simplified, especially in the "normal" case, but we can't assume that. Please let me know if you have suggestions.
=> Clarify some build instructions

docs/manual/src/tutorial/Prerequisites.md, docs/manual/src/tutorial/foreign_language_bindings.md
Note in the docs that you can `cargo run` uniffi-bindgen.
via #1112
=> docs: note that you can run uniffi-bindgen via cargo run

uniffi_bindgen/src/bindings/kotlin/gen_kotlin/miscellany.rs, uniffi_bindgen/src/bindings/swift/gen_swift/miscellany.rs
=> Use canonical_name in miscellany.rs instead of type label

fixtures/uitests/Cargo.toml, fixtures/uitests/README.md, fixtures/uitests/tests/ui/interface_cannot_use_mut_self.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr
Got very confused by uitest, so thought I'd offer clues to the next poor victim.
=> Update to uitest 1.0.53

CHANGELOG.md, examples/arithmetic/Cargo.toml, examples/callbacks/Cargo.toml, examples/custom-types/Cargo.toml, examples/geometry/Cargo.toml, examples/rondpoint/Cargo.toml, examples/sprites/Cargo.toml, examples/todolist/Cargo.toml, fixtures/callbacks/Cargo.toml, fixtures/coverall/Cargo.toml, fixtures/ext-types/guid/Cargo.toml, fixtures/ext-types/lib/Cargo.toml, fixtures/ext-types/uniffi-one/Cargo.toml, fixtures/external-types/crate-one/Cargo.toml, fixtures/external-types/crate-two/Cargo.toml, fixtures/external-types/lib/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/cdylib-dependency/Cargo.toml, fixtures/regressions/cdylib-crate-type-dependency/ffi-crate/Cargo.toml, fixtures/regressions/enum-without-i32-helpers/Cargo.toml, fixtures/regressions/fully-qualified-types/Cargo.toml, fixtures/regressions/kotlin-experimental-unsigned-types/Cargo.toml, fixtures/swift-omit-labels/Cargo.toml, fixtures/uitests/Cargo.toml, fixtures/uniffi-fixture-time/Cargo.toml, uniffi/Cargo.toml, uniffi_bindgen/Cargo.toml, uniffi_build/Cargo.toml, uniffi_macros/Cargo.toml
I just made the 0.17.0 release, now I think we need to merge the changes back into main.
Did I miss something, or should this be included in https://github.com/mozilla/uniffi-rs/blob/main/docs/release-process.md?
=> (cargo-release) version 0.17.0

uniffi_bindgen/src/lib.rs
Use &Path rather than AsRef<Path>.  We can call `as_ref()` before
calling into `BindingGenerator` and keep the implementation code simple.
Added code to extract the binding-specific config from the `uniffi.toml`
config that contains it.
Instead of leveraging `From<&ComponentInterface>` and `MergeWith`, have
some `BindingGeneratorConfig` methods that explicitly do what we need
them to do: update the values read from TOML with defaults from
`ComponentInterface`.
When implementing custom types, I wasn't sure how to properly implement
the `MergeWith` trait.  For example, what if we have 2 configs, each
with a custom type map should we try to take entries from both?  Having
methods specific to the actual process can avoid issues like that.  In
the custom types case, we never get custom types …
=> Couple updates to the BindingGenerator trait

uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/scaffolding/mod.rs
This will help the desktop JS project, since it will reduce the number of duplicate rust crates.
=> Upgrading heck to v0.4

fixtures/callbacks/src/lib.rs, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, rust-toolchain.toml, uniffi_bindgen/src/bindings/python/gen_python/compounds.rs, uniffi_bindgen/src/interface/callbacks.rs, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/interface/record.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_bindgen/src/lib.rs
mozilla-central is moving to this, so I figured it can't hurt to see what the fallout is here - ~~apparently there is none!~~ but of course there is some.
=> Upgrade to Rust 1.60

Cargo.toml, uniffi_bindgen/Cargo.toml, weedle2/.gitignore, weedle2/.travis.yml, weedle2/Cargo.toml, weedle2/LICENSE.md, weedle2/README.md, weedle2/src/argument.rs, weedle2/src/attribute.rs, weedle2/src/common.rs, weedle2/src/dictionary.rs, weedle2/src/interface.rs, weedle2/src/lib.rs, weedle2/src/literal.rs, weedle2/src/macros.rs, weedle2/src/mixin.rs, weedle2/src/namespace.rs, weedle2/src/term.rs, weedle2/src/types.rs, weedle2/src/whitespace.rs, weedle2/tests/defs/dom.webidl, weedle2/tests/defs/html.webidl, weedle2/tests/defs/interface-constructor.webidl, weedle2/tests/defs/mediacapture-streams.webidl, weedle2/tests/defs/streams.webidl, weedle2/tests/webidl.rs
Using `git-subtree` to import the https://github.com/badboy/weedle repository (squashed):
```
git subtree add --prefix weedle2 https://github.com/badboy/weedle.git main --squash
```
We could import the full git history if we really want that.
Fixes #1220
=> Vendor complete weedle2 codebase into this repository

uniffi_bindgen/src/bindings/python/templates/MapTemplate.py
In Python 3.7 and before the evaluation order in a dict comprehension
was not according to spec.
The spec says it's left to right: https://docs.python.org/3/reference/expressions.html#expression-lists
But the coveralls test failed with a "read past end of rust buffer"
uniffi exception, because its trying to read the value first.
This seems to have been a known bug back in the day: https://bugs.python.org/issue11205
For that specific instance of a dict literal it was fixed in 3.5
But for a dict comprehension it seems to not have been fixed in 3.7 yet
This can be tested with this short Python snippet:
def f(i):
print(i)
return i
{ f(i):f(10+i) for i in range(2) }
This should print "0 10 1 11" (as it does on Python 3.8.12),
but prints "10 0 11 1" on Python 3.7.12.
=> Python: Force correct order of evaluation when building the dict

uniffi_bindgen/src/bindings/kotlin/mod.rs, uniffi_bindgen/src/lib.rs
A few more refactorings to prepare for the addition of the first proc-macro frontend bits.
=> Some more proc-macro preparations

fixtures/regressions/missing-newline/tests/bindings/test.kts, fixtures/regressions/missing-newline/tests/bindings/test.rb, fixtures/regressions/missing-newline/tests/bindings/test.swift, fixtures/regressions/missing-newline/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/kotlin/templates/TopLevelFunctionTemplate.kt, uniffi_bindgen/src/bindings/ruby/templates/TopLevelFunctionTemplate.rb, uniffi_bindgen/src/bindings/swift/templates/TopLevelFunctionTemplate.swift
Should have done that to begin with. Followup to #1281
=> Extend regression test to Swift, Kotlin & Ruby

uniffi_bindgen/Cargo.toml, weedle2/Cargo.toml, weedle2/README.md, weedle2/src/argument.rs, weedle2/src/common.rs, weedle2/src/lib.rs, weedle2/src/literal.rs, weedle2/src/macros.rs, weedle2/src/term.rs, weedle2/src/whitespace.rs, weedle2/tests/webidl.rs
=> Upgrade weedle2 to nom 7

uniffi_bindgen/src/lib.rs
If rustfmt is not installed or otherwise not found in $PATH,
uniffi-bindgen now explains that it's rustfmt that wasn't found, instead
of a generic "file not found" error message. Context is also added for
when rustfmt fails to format the scaffolding.
I'm a newbie at Rust and UniFFI, so any feedback is much appreciated! :slightly_smiling_face:
=> Provide context to rustfmt-related errors

uniffi_bindgen/src/lib.rs
… to make it clear that staticlib files are also supported.
=> Rename uniffi_bindgen generate argument for native lib

Cargo.toml, fixtures/simple-iface/Cargo.toml, fixtures/simple-iface/README.md, fixtures/simple-iface/build.rs, fixtures/simple-iface/src/lib.rs, fixtures/simple-iface/src/simple-iface.udl, fixtures/simple-iface/tests/bindings/test_simple_iface.kts, fixtures/simple-iface/tests/bindings/test_simple_iface.py, fixtures/simple-iface/tests/bindings/test_simple_iface.swift, fixtures/simple-iface/tests/test_generated_bindings.rs, fixtures/simple-iface/uniffi.toml, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/metadata.rs, uniffi_macros/src/export/metadata/convert.rs, uniffi_macros/src/export/metadata/function.rs, uniffi_macros/src/export/metadata/impl_.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/lib.rs, uniffi_meta/src/lib.rs
=> Support impl blocks in proc-macro frontend

fixtures/simple-iface/src/lib.rs, fixtures/simple-iface/src/simple-iface.udl, uniffi/src/lib.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/object.rs, uniffi_bindgen/src/macro_metadata/ci.rs, uniffi_macros/src/export.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/object.rs, uniffi_macros/src/util.rs, uniffi_meta/src/lib.rs
… that generates a free function for an object/interface type.
Part of  #1257.
=> Add Object derive macro

fixtures/simple-iface/src/lib.rs, fixtures/simple-iface/tests/bindings/test_simple_iface.kts, fixtures/simple-iface/tests/bindings/test_simple_iface.py, fixtures/simple-iface/tests/bindings/test_simple_iface.swift, uniffi_macros/Cargo.toml, uniffi_macros/src/export.rs, uniffi_macros/src/export/metadata/convert.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/util.rs
=> proc-macro: Support Self type in methods

CHANGELOG.md, Cargo.toml, fixtures/keywords/README.md, fixtures/keywords/swift/Cargo.toml, fixtures/keywords/swift/build.rs, fixtures/keywords/swift/src/keywords.udl, fixtures/keywords/swift/src/lib.rs, fixtures/keywords/swift/tests/bindings/test_keywords.swift, fixtures/keywords/swift/tests/test_generated_bindings.rs, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs
Hoping to merge in the swift identifier changes that landed in the 0.19.x branch back into main.
=> Merge 0.19 branch

Cargo.toml, fixtures/regressions/swift-dictionary-nesting/Cargo.toml, fixtures/regressions/swift-dictionary-nesting/README.md, fixtures/regressions/swift-dictionary-nesting/build.rs, fixtures/regressions/swift-dictionary-nesting/src/lib.rs, fixtures/regressions/swift-dictionary-nesting/src/test.udl, fixtures/regressions/swift-dictionary-nesting/tests/bindings/test.swift, fixtures/regressions/swift-dictionary-nesting/tests/test_generated_bindings.rs
Thanks @bendk for merging my previous [PR](https://github.com/mozilla/uniffi-rs/pull/1363) so quickly, I was figuring out the best way to test the change so raising this as a separate PR
=> Add tests for dictionary nesting in Swift

uniffi_bindgen/src/interface/mod.rs
Follow-up to #1360, specifically the second commit. I was hitting one of the panics from that when returning `Vec<RecordTypeThatDerivesUniffiRecord>` from a `#[uniffi::export]`ed function.
=> proc-macro: Resolve unresolved types nested inside builtin generics

fixtures/coverall/src/lib.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/primitives.rs, uniffi_bindgen/src/bindings/python/gen_python/mod.rs, uniffi_bindgen/src/bindings/python/gen_python/primitives.rs, uniffi_bindgen/src/bindings/ruby/gen_ruby/mod.rs, uniffi_bindgen/src/bindings/swift/gen_swift/primitives.rs, uniffi_bindgen/src/bindings/swift/mod.rs, uniffi_bindgen/src/interface/attributes.rs, uniffi_bindgen/src/scaffolding/mod.rs, uniffi_testing/src/lib.rs
Automated with `cargo clippy --workspace --fix`.
=> Fix clippy lints

uniffi_bindgen/src/interface/mod.rs
With the proc-macro frontend, a lot of preconditions that were previously always true can no longer be relied on, sometimes leading to panics later in the code with bad error messages.
This should catch a few precondition violations earlier, and produce better error messages.
=> Add extra definition checks to ComponentInterface::check_consistency

uniffi_bindgen/Cargo.toml, uniffi_bindgen/src/macro_metadata/extract.rs
Changelog: https://github.com/m4b/goblin/blob/master/CHANGELOG.md#060---2022-10-23
=> Upgrade goblin to 0.6

README.md
Closes #1418 and maybe #441.
Please let me know if I should word some parts differently. I can't speak for #441 myself but I put part of its README in there (without mentioning future plans, which may or not happen, to avoid putting more pressure on the project).
=> Add External resources to the README

docker/Dockerfile-build
This makes the Dockerfile actually work and reduces its size a bit (down to "just" 6 GB). I'm working on getting us to use that again in CI properly (migrating away from rfkelly's personal docker image on docker hub)
=> Docker fixes (size reduction, deps)

.circleci/config.yml, docker/deploy-dockerhub.sh
=> Build and deploy the Docker image on `docker-vX` tag pushes

.circleci/config.yml, fixtures/futures/tests/test_generated_bindings.rs
This is still not the final destination, which will be mozilla/uniffi-ci.
Build from docker/Dockerfile-build
=> Switch to updated container image

docs/manual/src/proc_macro/index.md, fixtures/metadata/src/tests.rs, fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.py, uniffi_bindgen/src/interface/mod.rs, uniffi_bindgen/src/interface/types/mod.rs, uniffi_core/src/ffi_converter_impls.rs, uniffi_core/src/lib.rs, uniffi_macros/src/export.rs, uniffi_macros/src/export/item.rs, uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/object.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/reader.rs
This turned out fairly well - some unfortunate copy/paste which was hard to completely untangle due to visibility restrictions but I was excited to work out how to do this :)
=> Get traits working with procmacros

uniffi_macros/src/enum_.rs, uniffi_macros/src/error.rs, uniffi_macros/src/export.rs, uniffi_macros/src/object.rs, uniffi_macros/src/record.rs, uniffi_meta/src/lib.rs
Unrelated to the main change I'm working on, and small PRs are usually better IME :)
=> Small macro refactoring

uniffi_bindgen/src/library_mode.rs
=> Library Mode: correctly handle non-`lib` prefixed libraries

.circleci/config.yml, docker/Dockerfile-build, fixtures/benchmarks/src/cli.rs, fixtures/uitests/tests/ui/fieldless_errors_used_in_callbacks_cant_have_fields.stderr, fixtures/uitests/tests/ui/interface_not_sync_and_send.stderr, fixtures/uitests/tests/ui/non_hashable_record_key.stderr, fixtures/uitests/tests/ui/trait_methods_no_trait.stderr, rust-toolchain.toml, uniffi/tests/ui/proc_macro_arc.stderr, uniffi_bindgen/src/interface/object.rs
As per our Rust version policy:
https://github.com/mozilla/uniffi-rs/blob/main/docs/policies/rust-versions.md
I will re-deploy the Docker image when this is merged.
=> Update Rust to 1.69, MSRV to 1.66.0

README.md
Another alternative for generating multi-language bindings that I've come across is Interoptopus. I figured it ought to be listed here for completeness.
=> Add Interoptopus under alternative tools

uniffi_bindgen/src/interface/mod.rs
Running CI locally is hard, so I don't really know if CI will pass; let's see! 😅
=> Don't treat enum variant names as being part of a global namespace

CHANGELOG.md, docs/manual/src/proc_macro/index.md, fixtures/ext-types/proc-macro-lib/src/lib.rs, fixtures/ext-types/proc-macro-lib/tests/bindings/test_imported_types.py, uniffi_bindgen/src/scaffolding/templates/ExternalTypesTemplate.rs, uniffi_macros/src/custom.rs, uniffi_macros/src/lib.rs, uniffi_macros/src/setup_scaffolding.rs
=> Allow procmacros to define custom types

docs/manual/src/proc_macro/index.md
With this change code copied from the docs will work.
Ref: #1678
=> Update docs for proc-macro constructors

uniffi_bindgen/src/bindings/kotlin/templates/Helpers.kt
Copied from #1684 (thanks Hywan!)
=> Fix for Kotlin toChar deprecation (#1685)

uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceRuntime.kt, uniffi_bindgen/src/bindings/kotlin/templates/CallbackInterfaceTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ForeignExecutorTemplate.kt
=> Issue 1708: jna callback method "invoke" -> "callback"

fixtures/proc-macro/src/lib.rs, fixtures/proc-macro/tests/bindings/test_proc_macro.kts, fixtures/proc-macro/tests/bindings/test_proc_macro.py, fixtures/proc-macro/tests/bindings/test_proc_macro.swift
=> test(fixtures): remove potential duplicate in proc-macro fixture

.circleci/config.yml, examples/callbacks/src/lib.rs, fixtures/uitests/tests/ui/invalid_types_in_signatures.stderr, fixtures/uitests/tests/ui/non_hashable_record_key.stderr, rust-toolchain.toml, uniffi/src/lib.rs, uniffi/tests/ui/proc_macro_arc.stderr, uniffi_bindgen/src/interface/enum_.rs, uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/mod.rs, uniffi_core/src/ffi/foreignbytes.rs, uniffi_core/src/ffi/foreignexecutor.rs, uniffi_udl/src/attributes.rs, uniffi_udl/src/finder.rs
Had a 1.71 update unpublished in my local branches, so dusted it off. Not at all bothered if we want to wait before landing this.
=> Update rust to 1.72

uniffi_bindgen/src/lib.rs
`generate_external_bindings` was lacking `crate_name` field. This PR should ensure that in the future `generate_external_bindings` has all the same fields and functions identical to ` generate_bindings`.
=> Normalize 'generate_bindings' with 'generate_external_bindings'

docs/manual/src/kotlin/configuration.md, docs/manual/src/swift/configuration.md, uniffi_bindgen/src/bindings/kotlin/gen_kotlin/mod.rs, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/swift/gen_swift/mod.rs, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift
This isn't so much a finalised PR but more of a proposal and request for comments on how to enable immutable records in Kotlin and Swift. There's some previous discussion on why the records were changed to mutable by default in #471.
I agree that allowing mutability by default is the most flexible option, but it can cause issues with certain frameworks like Jetpack Compose in Kotlin, for example:
```kotlin
data class Sample(var num1: Int)
class SampleViewModel: ViewModel() {
// Create a state object. When used in a UI widget, any changes to sampleData will be automatically reflected in the UI
var sampleData by mutableStateOf(Sample(num1 = 0))
private set
fun onChange(newNum: Int) {
// This works, by copying the record and reassigning the reference, changes to sampleData are detected …
```
=> Add support for immutable records in Kotlin and Swift

uniffi_core/src/ffi/rustfuture/future.rs
The struct name changed in fbc6631953a889c7af6e5f1af94de9242589b75b, let's make the field name match it.
=> Rename RustFuture.callback_data to scheduler

README.md
PR as promised (+1 other project that I think deserves a link) ;)
https://hachyderm.io/@jer/111890149599873166
=> Add Cargo NDK and uniffi-starter project links

uniffi_bindgen/src/bindings/kotlin/templates/ObjectCleanerHelperAndroid.kt
=> Fix Android Cleaner version check

docs/manual/src/foreign_traits.md
This one tripped up a user in #uniffi today.
=> Manual fix for the foreign trait section

uniffi_bindgen/src/bindings/python/templates/RustBufferHelper.py, uniffi_bindgen/src/bindings/ruby/templates/RustBufferTemplate.rb
Noticed these while inspecting the generated files
=> Remove some unnecessary trailing whitespace

uniffi_bindgen/src/bindings/kotlin/templates/ObjectCleanerHelperAndroid.kt
=> fix: require Android API Level 34 for SystemCleaner

fixtures/coverall/tests/bindings/test_coverall.kts
coveralls fails locally for me more often than not. This change looks saner and has been reliable for me.
=> Fix GC/Cleaner intermittent test failures when run locally.

docs/manual/src/internals/rendering_foreign_bindings.md, uniffi_bindgen/src/bindings/README.md
The existing binding docs were getting out of date. I've tried to update them to make then more generally applicable.
=> Freshen up the docs for the bindings.

docs/manual/src/tutorial/Prerequisites.md, docs/manual/src/tutorial/Rust_scaffolding.md, docs/manual/src/tutorial/foreign_language_bindings.md, docs/manual/src/tutorial/udl_file.md
=> [User Guide] Make Tutorial section self-contained and self-explanatory

docs/adr/0009-remote-types-interfaces-and-proc-macros.md
@mhammond  raised this question when we were discussing https://github.com/mozilla/uniffi-rs/pull/2087 and I think it's a very good one.  Let's discuss and document our decision here.
@jplatte @Sajjon flagging you here since you were involved in that discussion.  If you have opinions, I'd love to hear them.
=> Remote types: interfaces and proc macros ADR

docs/manual/src/udl/errors.md
=> Remove extra character in document

examples/callbacks/README.md
=> Fix broken links in callbacks example

README.md
Add a 3rd party language "React Native".
=> Add React Native bindings to README.md

uniffi_bindgen/src/interface/function.rs, uniffi_bindgen/src/interface/object.rs
These are useful, but we've never exposed them.
=> Add couple methods to Constructor/Method

uniffi_macros/src/export/scaffolding.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/object.rs
I added these while trying to figure out the swift tests were failing on my machine.  It seems like it might actually be a swift issue (see #2305), but I still think these are useful.
=> More FFI tracing

CHANGELOG.md
This wasn't released in 0.28.2.
=> Fix logging entry in CHANGELOG (#2301)

uniffi_bindgen/src/bindings/swift/mod.rs
Fixing clippy error from #2320.
=> Clippy fix

mkdocs.yml
This renders us nice graphs.
Done as documented in https://squidfunk.github.io/mkdocs-material/reference/diagrams/
Fixes #2365
=> Docs: Enable mermaid in code blocks

uniffi_bindgen/src/bindings/kotlin/mod.rs
=> Print a message as ktlint formatting is started.

examples/callbacks/README.md
Small PR - Commit 4cbb8f10a1e8171d0b36114f126cb0abeea0f59a moved `callback_interfaces.md`. This PR adjusts sources to changes.
=> Update Callback interfaces reference

Cargo.lock, uniffi_macros/Cargo.toml, uniffi_meta/Cargo.toml
Remove `bincode` and `bytes` deps
=> Remove unused deps

uniffi/src/cli/uniffi_bindgen.rs
I want to use this in another subcommand.
=> Factor out the config-supplier code into it's own function

docs/release-process.md
Clarify things I wasn't sure about when cutting a release.
=> Few minor tweaks to the release process docs

uniffi_bindgen/src/macro_metadata/extract.rs
COFF is the object file format used by Visual C++ and MinGW. Though these two use different archive file formats (`.lib` and `.a`), both of them use COFF as entries in archives. This PR adds support for extracting metadata from COFF files.
=> Support extracting metadata from COFF files

mkdocs.yml
HI team! This PR fixes #2509.
Here is what it looks like when enabled:
=> Add search feature on documentation website

docs/manual/src/futures.md, docs/manual/src/internals/async-overview.md
mkdocs pointed out a broken link, then I found a few other trivial things
=> docs: async doc tweaks

docs/manual/src/tutorial/Rust_scaffolding.md, uniffi_bindgen/src/scaffolding/templates/ReexportUniFFIScaffolding.rs, uniffi_macros/src/setup_scaffolding.rs
=> Clarify semantics around uniffi_reexport_scaffolding! macro

.circleci/config.yml, examples/remote-types/Cargo.toml, uniffi_core/src/lib.rs, uniffi_macros/src/export/trait_interface.rs, uniffi_macros/src/object.rs
I broke this code at some point, but we never knew.  Added the `ffi-trace` feature to the CI job so that we'll catch this in the future.
=> ffi-trace fixes

CHANGELOG.md, fixtures/gh-2600/README.txt, fixtures/gh-2600/src/lib.rs
I figured out a bit more about the cause, so I figure we should put it in the changelog.
=> Updated CHANGELOG and test for #2600

fixtures/metadata/src/tests.rs, uniffi_bindgen/src/bindings/python/pipeline/nodes.rs, uniffi_bindgen/src/pipeline/general/nodes.rs, uniffi_bindgen/src/pipeline/initial/from_uniffi_meta.rs, uniffi_bindgen/src/pipeline/initial/nodes.rs, uniffi_macros/src/export.rs, uniffi_meta/src/lib.rs, uniffi_meta/src/reader.rs
It tricks you into thinking it is a path to #2430, but it's not. I've a fix for that on top of this which helps keep things clearer.
=> Remove ObjectTraitImpl::tr_module_name as it is never Some()

CHANGELOG.md, docs/manual/src/proc_macro/enumerations.md, docs/manual/src/proc_macro/functions.md, docs/manual/src/proc_macro/records.md, docs/manual/src/types/defaults.md, docs/manual/src/udl/enumerations.md, docs/manual/src/udl/records.md, fixtures/enum-types/src/lib.rs, fixtures/enum-types/tests/bindings/test_enum_types.kts, fixtures/enum-types/tests/bindings/test_enum_types.py, fixtures/enum-types/tests/bindings/test_enum_types.swift, mkdocs.yml, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_macros/src/enum_.rs, uniffi_macros/src/lib.rs
=> Allow default values in an enumeration, improve default value docs.

CHANGELOG.md, docs/manual/src/types/enumerations.md, docs/manual/src/types/interfaces.md, docs/manual/src/types/records.md, docs/manual/src/types/uniffi_traits.md, fixtures/trait-methods/tests/bindings/test.kts, fixtures/trait-methods/tests/bindings/test.py, fixtures/trait-methods/tests/bindings/test.swift, mkdocs.yml, uniffi_bindgen/src/bindings/kotlin/templates/EnumTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/ObjectTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/RecordTemplate.kt, uniffi_bindgen/src/bindings/kotlin/templates/macros.kt, uniffi_bindgen/src/bindings/python/pipeline/nodes.rs, uniffi_bindgen/src/bindings/python/templates/CallableBody.py, uniffi_bindgen/src/bindings/python/templates/EnumTemplate.py, uniffi_bindgen/src/bindings/python/templates/InterfaceTemplate.py, uniffi_bindgen/src/bindings/python/templates/RecordTemplate.py, uniffi_bindgen/src/bindings/python/templates/UniffiTraitImpls.py, uniffi_bindgen/src/bindings/swift/templates/EnumTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/ObjectTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/RecordTemplate.swift, uniffi_bindgen/src/bindings/swift/templates/macros.swift
=> Binding support + docs for uniffi-traits on data classes.
